from aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models import CreateAwsKmsKeyringInput
from aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.client import AwsCryptographicMaterialProviders
from aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.config import MaterialProvidersConfig
from aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_keystore.config import KeyStoreConfig


client = AwsCryptographicMaterialProviders(MaterialProvidersConfig())

import botocore.client.KMS
a = boto3.client("kms")
