includes = [
  "../dafny/Source/DafnyStandardLibraries/src/Std/BoundedInts.dfy",
  "../dafny/Source/DafnyStandardLibraries/src/Std/Collections/Seq.dfy",
  "../dafny/Source/DafnyStandardLibraries/src/Std/DynamicArray.dfy",
  "../dafny/Source/DafnyStandardLibraries/src/Std/Math.dfy",
  "../dafny/Source/DafnyStandardLibraries/src/Std/Relations.dfy",
  "../dafny/Source/DafnyStandardLibraries/src/Std/Wrappers.dfy"
]

[options]
# Options that help support more values of consuming context options
# (mostly turning on any more restrictive verification)
track-print-effects = true
enforce-determinism = false
reads-clauses-on-methods = true

# Options that differ from Dafny's
unicode-char = false

# Options important for sustainable development
# of the libraries themselves.
resource-limit = 1000000
# These give too many false positives right now, but should be enabled in the future
warn-redundant-assumptions = false
warn-contradictory-assumptions = false
