// Class __default
// Dafny class __default compiled into Java
package DDBKeystoreOperations_Compile;

@SuppressWarnings({"unchecked", "deprecation"})
public class __default {
  public __default() {
  }
  public static Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput, software.amazon.cryptography.keystore.internaldafny.types.Error> WriteNewKeyToStore(dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> versionBranchKeyItem, dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> activeBranchKeyItem, dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> beaconKeyItem, dafny.DafnySequence<? extends Character> tableName, software.amazon.cryptography.services.dynamodb.internaldafny.types.IDynamoDBClient ddbClient)
  {
    Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput, software.amazon.cryptography.keystore.internaldafny.types.Error> output = Wrappers_Compile.Result.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput, software.amazon.cryptography.keystore.internaldafny.types.Error>Default(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput.Default());
    if(true) {
      dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem> _0_items;
      _0_items = dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem._typeDescriptor(), __default.CreateTransactWritePutItem(versionBranchKeyItem, tableName, ConditionExpression.create_BRANCH__KEY__NOT__EXIST()), __default.CreateTransactWritePutItem(activeBranchKeyItem, tableName, ConditionExpression.create_BRANCH__KEY__NOT__EXIST()), __default.CreateTransactWritePutItem(beaconKeyItem, tableName, ConditionExpression.create_BRANCH__KEY__NOT__EXIST()));
      software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput _1_transactRequest;
      _1_transactRequest = software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput.create(_0_items, Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics._typeDescriptor()), Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ClientRequestToken._typeDescriptor()));
      Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput, software.amazon.cryptography.services.dynamodb.internaldafny.types.Error> _2_maybeTransactWriteResponse;
      Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput, software.amazon.cryptography.services.dynamodb.internaldafny.types.Error> _out0;
      _out0 = (ddbClient).TransactWriteItems(_1_transactRequest);
      _2_maybeTransactWriteResponse = _out0;
      Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput, software.amazon.cryptography.keystore.internaldafny.types.Error> _3_valueOrError0 = Wrappers_Compile.Result.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput, software.amazon.cryptography.keystore.internaldafny.types.Error>Default(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput.Default());
      _3_valueOrError0 = (_2_maybeTransactWriteResponse).<software.amazon.cryptography.keystore.internaldafny.types.Error>MapFailure(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.services.dynamodb.internaldafny.types.Error, software.amazon.cryptography.keystore.internaldafny.types.Error>)(_4_e_boxed0) -> {
        software.amazon.cryptography.services.dynamodb.internaldafny.types.Error _4_e = ((software.amazon.cryptography.services.dynamodb.internaldafny.types.Error)(java.lang.Object)(_4_e_boxed0));
        return software.amazon.cryptography.keystore.internaldafny.types.Error.create_ComAmazonawsDynamodb(_4_e);
      }));
      if ((_3_valueOrError0).IsFailure(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor())) {
        output = (_3_valueOrError0).<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput>PropagateFailure(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput._typeDescriptor());
        return output;
      }
      software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput _5_transactWriteItemsResponse;
      _5_transactWriteItemsResponse = (_3_valueOrError0).Extract(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor());
      output = Wrappers_Compile.Result.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput, software.amazon.cryptography.keystore.internaldafny.types.Error>create_Success(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), _5_transactWriteItemsResponse);
    }
    return output;
  }
  public static Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput, software.amazon.cryptography.keystore.internaldafny.types.Error> WriteNewBranchKeyVersionToKeystore(dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> versionBranchKeyItem, dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> activeBranchKeyItem, dafny.DafnySequence<? extends Character> tableName, software.amazon.cryptography.services.dynamodb.internaldafny.types.IDynamoDBClient ddbClient)
  {
    Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput, software.amazon.cryptography.keystore.internaldafny.types.Error> output = Wrappers_Compile.Result.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput, software.amazon.cryptography.keystore.internaldafny.types.Error>Default(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput.Default());
    if(true) {
      dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem> _0_items;
      _0_items = dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem._typeDescriptor(), __default.CreateTransactWritePutItem(versionBranchKeyItem, tableName, ConditionExpression.create_BRANCH__KEY__NOT__EXIST()), __default.CreateTransactWritePutItem(activeBranchKeyItem, tableName, ConditionExpression.create_BRANCH__KEY__EXISTS()));
      software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput _1_transactRequest;
      _1_transactRequest = software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput.create(_0_items, Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics._typeDescriptor()), Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ClientRequestToken._typeDescriptor()));
      Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput, software.amazon.cryptography.services.dynamodb.internaldafny.types.Error> _2_maybeTransactWriteResponse;
      Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput, software.amazon.cryptography.services.dynamodb.internaldafny.types.Error> _out0;
      _out0 = (ddbClient).TransactWriteItems(_1_transactRequest);
      _2_maybeTransactWriteResponse = _out0;
      Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput, software.amazon.cryptography.keystore.internaldafny.types.Error> _3_valueOrError0 = Wrappers_Compile.Result.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput, software.amazon.cryptography.keystore.internaldafny.types.Error>Default(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput.Default());
      _3_valueOrError0 = (_2_maybeTransactWriteResponse).<software.amazon.cryptography.keystore.internaldafny.types.Error>MapFailure(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.services.dynamodb.internaldafny.types.Error, software.amazon.cryptography.keystore.internaldafny.types.Error>)(_4_e_boxed0) -> {
        software.amazon.cryptography.services.dynamodb.internaldafny.types.Error _4_e = ((software.amazon.cryptography.services.dynamodb.internaldafny.types.Error)(java.lang.Object)(_4_e_boxed0));
        return software.amazon.cryptography.keystore.internaldafny.types.Error.create_ComAmazonawsDynamodb(_4_e);
      }));
      if ((_3_valueOrError0).IsFailure(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor())) {
        output = (_3_valueOrError0).<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput>PropagateFailure(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput._typeDescriptor());
        return output;
      }
      software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput _5_transactWriteItemsResponse;
      _5_transactWriteItemsResponse = (_3_valueOrError0).Extract(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor());
      output = Wrappers_Compile.Result.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput, software.amazon.cryptography.keystore.internaldafny.types.Error>create_Success(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), _5_transactWriteItemsResponse);
    }
    return output;
  }
  public static Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.keystore.internaldafny.types.Error> GetActiveBranchKeyItem(dafny.DafnySequence<? extends Character> branchKeyIdentifier, dafny.DafnySequence<? extends Character> tableName, software.amazon.cryptography.services.dynamodb.internaldafny.types.IDynamoDBClient ddbClient)
  {
    Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.keystore.internaldafny.types.Error> output = (Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.keystore.internaldafny.types.Error>)null;
    if(true) {
      dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> _0_dynamoDbKey;
      _0_dynamoDbKey = dafny.DafnyMap.fromElements(new dafny.Tuple2(Structure_Compile.__default.BRANCH__KEY__IDENTIFIER__FIELD(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(branchKeyIdentifier)), new dafny.Tuple2(Structure_Compile.__default.TYPE__FIELD(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(Structure_Compile.__default.BRANCH__KEY__ACTIVE__TYPE())));
      software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemInput _1_ItemRequest;
      _1_ItemRequest = software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemInput.create(tableName, _0_dynamoDbKey, Wrappers_Compile.Option.<dafny.DafnySequence<? extends dafny.DafnySequence<? extends Character>>>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeNameList._typeDescriptor()), Wrappers_Compile.Option.<Boolean>create_None(dafny.TypeDescriptor.BOOLEAN), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity._typeDescriptor()), Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>create_None(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>>create_None(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor())));
      Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput, software.amazon.cryptography.services.dynamodb.internaldafny.types.Error> _2_maybeGetItem;
      Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput, software.amazon.cryptography.services.dynamodb.internaldafny.types.Error> _out0;
      _out0 = (ddbClient).GetItem(_1_ItemRequest);
      _2_maybeGetItem = _out0;
      Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput, software.amazon.cryptography.keystore.internaldafny.types.Error> _3_valueOrError0 = Wrappers_Compile.Result.<software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput, software.amazon.cryptography.keystore.internaldafny.types.Error>Default(software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput.Default());
      _3_valueOrError0 = (_2_maybeGetItem).<software.amazon.cryptography.keystore.internaldafny.types.Error>MapFailure(software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.services.dynamodb.internaldafny.types.Error, software.amazon.cryptography.keystore.internaldafny.types.Error>)(_4_e_boxed0) -> {
        software.amazon.cryptography.services.dynamodb.internaldafny.types.Error _4_e = ((software.amazon.cryptography.services.dynamodb.internaldafny.types.Error)(java.lang.Object)(_4_e_boxed0));
        return software.amazon.cryptography.keystore.internaldafny.types.Error.create_ComAmazonawsDynamodb(_4_e);
      }));
      if ((_3_valueOrError0).IsFailure(software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor())) {
        output = (_3_valueOrError0).<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>>PropagateFailure(software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), Structure_Compile.ActiveBranchKeyItem._typeDescriptor());
        return output;
      }
      software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput _5_getItemResponse;
      _5_getItemResponse = (_3_valueOrError0).Extract(software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor());
      Wrappers_Compile.Outcome<software.amazon.cryptography.keystore.internaldafny.types.Error> _6_valueOrError1 = Wrappers_Compile.Outcome.<software.amazon.cryptography.keystore.internaldafny.types.Error>Default(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor());
      _6_valueOrError1 = Wrappers_Compile.__default.<software.amazon.cryptography.keystore.internaldafny.types.Error>Need(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), (((_5_getItemResponse).dtor_Item()).is_Some()) && (java.lang.Long.compareUnsigned((long) (((_5_getItemResponse).dtor_Item()).dtor_value()).cardinalityInt(), (long) 1L) >= 0), software.amazon.cryptography.keystore.internaldafny.types.Error.create_KeyStoreException(KeyStoreErrorMessages_Compile.__default.NO__CORRESPONDING__BRANCH__KEY()));
      if ((_6_valueOrError1).IsFailure(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor())) {
        output = (_6_valueOrError1).<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>>PropagateFailure(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), Structure_Compile.ActiveBranchKeyItem._typeDescriptor());
        return output;
      }
      Wrappers_Compile.Outcome<software.amazon.cryptography.keystore.internaldafny.types.Error> _7_valueOrError2 = Wrappers_Compile.Outcome.<software.amazon.cryptography.keystore.internaldafny.types.Error>Default(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor());
      _7_valueOrError2 = Wrappers_Compile.__default.<software.amazon.cryptography.keystore.internaldafny.types.Error>Need(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), (Structure_Compile.__default.ActiveBranchKeyItem_q(((_5_getItemResponse).dtor_Item()).dtor_value())) && (((((software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue)(java.lang.Object)((((_5_getItemResponse).dtor_Item()).dtor_value()).get(Structure_Compile.__default.BRANCH__KEY__IDENTIFIER__FIELD())))).dtor_S()).equals(branchKeyIdentifier)), software.amazon.cryptography.keystore.internaldafny.types.Error.create_KeyStoreException(dafny.DafnySequence.asString("Item found is not a valid active branch key.")));
      if ((_7_valueOrError2).IsFailure(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor())) {
        output = (_7_valueOrError2).<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>>PropagateFailure(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), Structure_Compile.ActiveBranchKeyItem._typeDescriptor());
        return output;
      }
      output = Wrappers_Compile.Result.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.keystore.internaldafny.types.Error>create_Success(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), ((_5_getItemResponse).dtor_Item()).dtor_value());
    }
    return output;
  }
  public static Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.keystore.internaldafny.types.Error> GetVersionBranchKeyItem(dafny.DafnySequence<? extends Character> branchKeyIdentifier, dafny.DafnySequence<? extends Character> branchKeyVersion, dafny.DafnySequence<? extends Character> tableName, software.amazon.cryptography.services.dynamodb.internaldafny.types.IDynamoDBClient ddbClient)
  {
    Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.keystore.internaldafny.types.Error> output = (Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.keystore.internaldafny.types.Error>)null;
    if(true) {
      dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> _0_dynamoDbKey;
      _0_dynamoDbKey = dafny.DafnyMap.fromElements(new dafny.Tuple2(Structure_Compile.__default.BRANCH__KEY__IDENTIFIER__FIELD(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(branchKeyIdentifier)), new dafny.Tuple2(Structure_Compile.__default.TYPE__FIELD(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.<Character>concatenate(Structure_Compile.__default.BRANCH__KEY__TYPE__PREFIX(), branchKeyVersion))));
      software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemInput _1_ItemRequest;
      _1_ItemRequest = software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemInput.create(tableName, _0_dynamoDbKey, Wrappers_Compile.Option.<dafny.DafnySequence<? extends dafny.DafnySequence<? extends Character>>>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeNameList._typeDescriptor()), Wrappers_Compile.Option.<Boolean>create_None(dafny.TypeDescriptor.BOOLEAN), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity._typeDescriptor()), Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>create_None(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>>create_None(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor())));
      Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput, software.amazon.cryptography.services.dynamodb.internaldafny.types.Error> _2_maybeGetItem;
      Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput, software.amazon.cryptography.services.dynamodb.internaldafny.types.Error> _out0;
      _out0 = (ddbClient).GetItem(_1_ItemRequest);
      _2_maybeGetItem = _out0;
      Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput, software.amazon.cryptography.keystore.internaldafny.types.Error> _3_valueOrError0 = Wrappers_Compile.Result.<software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput, software.amazon.cryptography.keystore.internaldafny.types.Error>Default(software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput.Default());
      _3_valueOrError0 = (_2_maybeGetItem).<software.amazon.cryptography.keystore.internaldafny.types.Error>MapFailure(software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.services.dynamodb.internaldafny.types.Error, software.amazon.cryptography.keystore.internaldafny.types.Error>)(_4_e_boxed0) -> {
        software.amazon.cryptography.services.dynamodb.internaldafny.types.Error _4_e = ((software.amazon.cryptography.services.dynamodb.internaldafny.types.Error)(java.lang.Object)(_4_e_boxed0));
        return software.amazon.cryptography.keystore.internaldafny.types.Error.create_ComAmazonawsDynamodb(_4_e);
      }));
      if ((_3_valueOrError0).IsFailure(software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor())) {
        output = (_3_valueOrError0).<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>>PropagateFailure(software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), Structure_Compile.VersionBranchKeyItem._typeDescriptor());
        return output;
      }
      software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput _5_getItemResponse;
      _5_getItemResponse = (_3_valueOrError0).Extract(software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor());
      Wrappers_Compile.Outcome<software.amazon.cryptography.keystore.internaldafny.types.Error> _6_valueOrError1 = Wrappers_Compile.Outcome.<software.amazon.cryptography.keystore.internaldafny.types.Error>Default(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor());
      _6_valueOrError1 = Wrappers_Compile.__default.<software.amazon.cryptography.keystore.internaldafny.types.Error>Need(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), (((_5_getItemResponse).dtor_Item()).is_Some()) && (java.lang.Long.compareUnsigned((long) (((_5_getItemResponse).dtor_Item()).dtor_value()).cardinalityInt(), (long) 1L) >= 0), software.amazon.cryptography.keystore.internaldafny.types.Error.create_KeyStoreException(KeyStoreErrorMessages_Compile.__default.NO__CORRESPONDING__BRANCH__KEY()));
      if ((_6_valueOrError1).IsFailure(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor())) {
        output = (_6_valueOrError1).<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>>PropagateFailure(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), Structure_Compile.VersionBranchKeyItem._typeDescriptor());
        return output;
      }
      Wrappers_Compile.Outcome<software.amazon.cryptography.keystore.internaldafny.types.Error> _7_valueOrError2 = Wrappers_Compile.Outcome.<software.amazon.cryptography.keystore.internaldafny.types.Error>Default(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor());
      _7_valueOrError2 = Wrappers_Compile.__default.<software.amazon.cryptography.keystore.internaldafny.types.Error>Need(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), ((Structure_Compile.__default.VersionBranchKeyItem_q(((_5_getItemResponse).dtor_Item()).dtor_value())) && (((((software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue)(java.lang.Object)((((_5_getItemResponse).dtor_Item()).dtor_value()).get(Structure_Compile.__default.BRANCH__KEY__IDENTIFIER__FIELD())))).dtor_S()).equals(branchKeyIdentifier))) && (((((software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue)(java.lang.Object)((((_5_getItemResponse).dtor_Item()).dtor_value()).get(Structure_Compile.__default.TYPE__FIELD())))).dtor_S()).equals(dafny.DafnySequence.<Character>concatenate(Structure_Compile.__default.BRANCH__KEY__TYPE__PREFIX(), branchKeyVersion))), software.amazon.cryptography.keystore.internaldafny.types.Error.create_KeyStoreException(dafny.DafnySequence.asString("Item found is not a valid branch key version.")));
      if ((_7_valueOrError2).IsFailure(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor())) {
        output = (_7_valueOrError2).<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>>PropagateFailure(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), Structure_Compile.VersionBranchKeyItem._typeDescriptor());
        return output;
      }
      output = Wrappers_Compile.Result.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.keystore.internaldafny.types.Error>create_Success(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), ((_5_getItemResponse).dtor_Item()).dtor_value());
    }
    return output;
  }
  public static Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.keystore.internaldafny.types.Error> GetBeaconKeyItem(dafny.DafnySequence<? extends Character> branchKeyIdentifier, dafny.DafnySequence<? extends Character> tableName, software.amazon.cryptography.services.dynamodb.internaldafny.types.IDynamoDBClient ddbClient)
  {
    Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.keystore.internaldafny.types.Error> output = (Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.keystore.internaldafny.types.Error>)null;
    if(true) {
      dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> _0_dynamoDbKey;
      _0_dynamoDbKey = dafny.DafnyMap.fromElements(new dafny.Tuple2(Structure_Compile.__default.BRANCH__KEY__IDENTIFIER__FIELD(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(branchKeyIdentifier)), new dafny.Tuple2(Structure_Compile.__default.TYPE__FIELD(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(Structure_Compile.__default.BEACON__KEY__TYPE__VALUE())));
      software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemInput _1_ItemRequest;
      _1_ItemRequest = software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemInput.create(tableName, _0_dynamoDbKey, Wrappers_Compile.Option.<dafny.DafnySequence<? extends dafny.DafnySequence<? extends Character>>>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeNameList._typeDescriptor()), Wrappers_Compile.Option.<Boolean>create_None(dafny.TypeDescriptor.BOOLEAN), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity._typeDescriptor()), Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>create_None(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>>create_None(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor())));
      Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput, software.amazon.cryptography.services.dynamodb.internaldafny.types.Error> _2_maybeGetItem;
      Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput, software.amazon.cryptography.services.dynamodb.internaldafny.types.Error> _out0;
      _out0 = (ddbClient).GetItem(_1_ItemRequest);
      _2_maybeGetItem = _out0;
      Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput, software.amazon.cryptography.keystore.internaldafny.types.Error> _3_valueOrError0 = Wrappers_Compile.Result.<software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput, software.amazon.cryptography.keystore.internaldafny.types.Error>Default(software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput.Default());
      _3_valueOrError0 = (_2_maybeGetItem).<software.amazon.cryptography.keystore.internaldafny.types.Error>MapFailure(software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.services.dynamodb.internaldafny.types.Error, software.amazon.cryptography.keystore.internaldafny.types.Error>)(_4_e_boxed0) -> {
        software.amazon.cryptography.services.dynamodb.internaldafny.types.Error _4_e = ((software.amazon.cryptography.services.dynamodb.internaldafny.types.Error)(java.lang.Object)(_4_e_boxed0));
        return software.amazon.cryptography.keystore.internaldafny.types.Error.create_ComAmazonawsDynamodb(_4_e);
      }));
      if ((_3_valueOrError0).IsFailure(software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor())) {
        output = (_3_valueOrError0).<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>>PropagateFailure(software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), Structure_Compile.BeaconKeyItem._typeDescriptor());
        return output;
      }
      software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput _5_getItemResponse;
      _5_getItemResponse = (_3_valueOrError0).Extract(software.amazon.cryptography.services.dynamodb.internaldafny.types.GetItemOutput._typeDescriptor(), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor());
      Wrappers_Compile.Outcome<software.amazon.cryptography.keystore.internaldafny.types.Error> _6_valueOrError1 = Wrappers_Compile.Outcome.<software.amazon.cryptography.keystore.internaldafny.types.Error>Default(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor());
      _6_valueOrError1 = Wrappers_Compile.__default.<software.amazon.cryptography.keystore.internaldafny.types.Error>Need(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), (((_5_getItemResponse).dtor_Item()).is_Some()) && (java.lang.Long.compareUnsigned((long) (((_5_getItemResponse).dtor_Item()).dtor_value()).cardinalityInt(), (long) 1L) >= 0), software.amazon.cryptography.keystore.internaldafny.types.Error.create_KeyStoreException(KeyStoreErrorMessages_Compile.__default.NO__CORRESPONDING__BRANCH__KEY()));
      if ((_6_valueOrError1).IsFailure(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor())) {
        output = (_6_valueOrError1).<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>>PropagateFailure(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), Structure_Compile.BeaconKeyItem._typeDescriptor());
        return output;
      }
      Wrappers_Compile.Outcome<software.amazon.cryptography.keystore.internaldafny.types.Error> _7_valueOrError2 = Wrappers_Compile.Outcome.<software.amazon.cryptography.keystore.internaldafny.types.Error>Default(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor());
      _7_valueOrError2 = Wrappers_Compile.__default.<software.amazon.cryptography.keystore.internaldafny.types.Error>Need(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), (Structure_Compile.__default.BeaconKeyItem_q(((_5_getItemResponse).dtor_Item()).dtor_value())) && (((((software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue)(java.lang.Object)((((_5_getItemResponse).dtor_Item()).dtor_value()).get(Structure_Compile.__default.BRANCH__KEY__IDENTIFIER__FIELD())))).dtor_S()).equals(branchKeyIdentifier)), software.amazon.cryptography.keystore.internaldafny.types.Error.create_KeyStoreException(dafny.DafnySequence.asString("Item found is not a valid beacon key.")));
      if ((_7_valueOrError2).IsFailure(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor())) {
        output = (_7_valueOrError2).<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>>PropagateFailure(software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), Structure_Compile.BeaconKeyItem._typeDescriptor());
        return output;
      }
      output = Wrappers_Compile.Result.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.keystore.internaldafny.types.Error>create_Success(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), software.amazon.cryptography.keystore.internaldafny.types.Error._typeDescriptor(), ((_5_getItemResponse).dtor_Item()).dtor_value());
    }
    return output;
  }
  public static software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem CreateTransactWritePutItem(dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> item, dafny.DafnySequence<? extends Character> tableName, ConditionExpression conditionExpression)
  {
    return software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem.create(Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ConditionCheck>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ConditionCheck._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.Put>create_Some(software.amazon.cryptography.services.dynamodb.internaldafny.types.Put._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.Put.create(item, tableName, Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>create_Some(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), ((java.util.function.Function<ConditionExpression, dafny.DafnySequence<? extends Character>>)(_source0_boxed0) -> {
  ConditionExpression _source0 = ((ConditionExpression)(java.lang.Object)(_source0_boxed0));
  if (_source0.is_BRANCH__KEY__NOT__EXIST()) {
    return __default.BRANCH__KEY__NOT__EXIST__CONDITION();
  } else {
    return __default.BRANCH__KEY__EXISTS__CONDITION();
  }
}).apply(conditionExpression)), Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>>create_Some(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), __default.BRANCH__KEY__EXISTS__EXPRESSION__ATTRIBUTE__NAMES()), Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>>create_None(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor())), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnValuesOnConditionCheckFailure>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnValuesOnConditionCheckFailure._typeDescriptor()))), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.Delete>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.Delete._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.Update>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.Update._typeDescriptor()));
  }
  public static dafny.DafnySequence<? extends Character> BRANCH__KEY__EXISTS__EXPRESSION__ATTRIBUTE__NAME()
  {
    return dafny.DafnySequence.asString("#BranchKeyIdentifierField");
  }
  public static dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>> BRANCH__KEY__EXISTS__EXPRESSION__ATTRIBUTE__NAMES()
  {
    return dafny.DafnyMap.fromElements(new dafny.Tuple2(__default.BRANCH__KEY__EXISTS__EXPRESSION__ATTRIBUTE__NAME(), Structure_Compile.__default.BRANCH__KEY__IDENTIFIER__FIELD()));
  }
  public static dafny.DafnySequence<? extends Character> BRANCH__KEY__NOT__EXIST__CONDITION()
  {
    return dafny.DafnySequence.<Character>concatenate(dafny.DafnySequence.<Character>concatenate(dafny.DafnySequence.asString("attribute_not_exists("), __default.BRANCH__KEY__EXISTS__EXPRESSION__ATTRIBUTE__NAME()), dafny.DafnySequence.asString(")"));
  }
  public static dafny.DafnySequence<? extends Character> BRANCH__KEY__EXISTS__CONDITION()
  {
    return dafny.DafnySequence.<Character>concatenate(dafny.DafnySequence.<Character>concatenate(dafny.DafnySequence.asString("attribute_exists("), __default.BRANCH__KEY__EXISTS__EXPRESSION__ATTRIBUTE__NAME()), dafny.DafnySequence.asString(")"));
  }
  @Override
  public java.lang.String toString() {
    return "DDBKeystoreOperations._default";
  }
}
