// Class __default
// Dafny class __default compiled into Java
package WriteJsonManifests_Compile;

@SuppressWarnings({"unchecked", "deprecation"})
public class __default {
  public __default() {
  }
  public static Wrappers_Compile.Result<dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>, dafny.DafnySequence<? extends Character>> EncryptionContextKeysToJson(Wrappers_Compile.Option<dafny.DafnySequence<? extends dafny.DafnySequence<? extends java.lang.Byte>>> keys) {
    if ((keys).is_Some()) {
      Wrappers_Compile.Result<dafny.DafnySequence<? extends JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>> _0_valueOrError0 = Seq_Compile.__default.<dafny.DafnySequence<? extends java.lang.Byte>, JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>>MapWithResult(UTF8.ValidUTF8Bytes._typeDescriptor(), JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), ((java.util.function.Function<dafny.DafnySequence<? extends java.lang.Byte>, Wrappers_Compile.Result<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>>>)(_1_bytes_boxed0) -> {
        dafny.DafnySequence<? extends java.lang.Byte> _1_bytes = ((dafny.DafnySequence<? extends java.lang.Byte>)(java.lang.Object)(_1_bytes_boxed0));
        return ((Wrappers_Compile.Result<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>>)(java.lang.Object)(dafny.Helpers.<Wrappers_Compile.Result<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>, Wrappers_Compile.Result<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>>>Let(UTF8.__default.Decode(_1_bytes), boxed32 -> {
          Wrappers_Compile.Result<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>> _pat_let16_0 = ((Wrappers_Compile.Result<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>)(java.lang.Object)(boxed32));
          return ((Wrappers_Compile.Result<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>>)(java.lang.Object)(dafny.Helpers.<Wrappers_Compile.Result<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>, Wrappers_Compile.Result<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>>>Let(_pat_let16_0, boxed33 -> {
            Wrappers_Compile.Result<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>> _2_valueOrError1 = ((Wrappers_Compile.Result<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>)(java.lang.Object)(boxed33));
            return (((_2_valueOrError1).IsFailure(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR))) ? ((_2_valueOrError1).<JSON_mValues_Compile.JSON>PropagateFailure(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())) : (((Wrappers_Compile.Result<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>>)(java.lang.Object)(dafny.Helpers.<dafny.DafnySequence<? extends Character>, Wrappers_Compile.Result<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>>>Let((_2_valueOrError1).Extract(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), boxed34 -> {
              dafny.DafnySequence<? extends Character> _pat_let17_0 = ((dafny.DafnySequence<? extends Character>)(java.lang.Object)(boxed34));
              return ((Wrappers_Compile.Result<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>>)(java.lang.Object)(dafny.Helpers.<dafny.DafnySequence<? extends Character>, Wrappers_Compile.Result<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>>>Let(_pat_let17_0, boxed35 -> {
                dafny.DafnySequence<? extends Character> _3_key = ((dafny.DafnySequence<? extends Character>)(java.lang.Object)(boxed35));
                return Wrappers_Compile.Result.<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>>create_Success(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON.create_String(_3_key));
              }
              )));
            }
            )))));
          }
          )));
        }
        )));
      }), (keys).dtor_value());
      if ((_0_valueOrError0).IsFailure(dafny.DafnySequence.<JSON_mValues_Compile.JSON>_typeDescriptor(JSON_mValues_Compile.JSON._typeDescriptor()), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR))) {
        return (_0_valueOrError0).<dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>>PropagateFailure(dafny.DafnySequence.<JSON_mValues_Compile.JSON>_typeDescriptor(JSON_mValues_Compile.JSON._typeDescriptor()), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())));
      } else {
        dafny.DafnySequence<? extends JSON_mValues_Compile.JSON> _4_tmp = (_0_valueOrError0).Extract(dafny.DafnySequence.<JSON_mValues_Compile.JSON>_typeDescriptor(JSON_mValues_Compile.JSON._typeDescriptor()), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR));
        return Wrappers_Compile.Result.<dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>, dafny.DafnySequence<? extends Character>>create_Success(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> of(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor()), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("requiredEncryptionContextKeys"), JSON_mValues_Compile.JSON.create_Array(_4_tmp))));
      }
    } else {
      return Wrappers_Compile.Result.<dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>, dafny.DafnySequence<? extends Character>>create_Success(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> empty(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())));
    }
  }
  public static Wrappers_Compile.Result<dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>, dafny.DafnySequence<? extends Character>> EncryptionContextToJson(dafny.DafnySequence<? extends Character> key, dafny.DafnyMap<? extends dafny.DafnySequence<? extends java.lang.Byte>, ? extends dafny.DafnySequence<? extends java.lang.Byte>> m)
  {
    dafny.DafnySequence<? extends dafny.DafnySequence<? extends java.lang.Byte>> _0_keys = SortedSets.__default.<java.lang.Byte>SetToOrderedSequence2(BoundedInts_Compile.uint8._typeDescriptor(), (m).keySet(), ((dafny.Function2<java.lang.Byte, java.lang.Byte, Boolean>)(_1_a_boxed0, _2_b_boxed0) -> {
      byte _1_a = ((byte)(java.lang.Object)(_1_a_boxed0));
      byte _2_b = ((byte)(java.lang.Object)(_2_b_boxed0));
      return java.lang.Integer.compareUnsigned(_1_a, _2_b) < 0;
    }));
    Wrappers_Compile.Result<dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>, dafny.DafnySequence<? extends Character>> _3_valueOrError0 = Seq_Compile.__default.<dafny.DafnySequence<? extends java.lang.Byte>, dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>>MapWithResult(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor()), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), ((java.util.function.Function<dafny.DafnyMap<? extends dafny.DafnySequence<? extends java.lang.Byte>, ? extends dafny.DafnySequence<? extends java.lang.Byte>>, java.util.function.Function<dafny.DafnySequence<? extends java.lang.Byte>, Wrappers_Compile.Result<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>>>>)(_4_m) -> ((java.util.function.Function<dafny.DafnySequence<? extends java.lang.Byte>, Wrappers_Compile.Result<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>>>)(_5_k_boxed0) -> {
      dafny.DafnySequence<? extends java.lang.Byte> _5_k = ((dafny.DafnySequence<? extends java.lang.Byte>)(java.lang.Object)(_5_k_boxed0));
      return ((Wrappers_Compile.Result<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>>)(java.lang.Object)(dafny.Helpers.<Wrappers_Compile.Result<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>, Wrappers_Compile.Result<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>>>Let(UTF8.__default.Decode(_5_k), boxed36 -> {
        Wrappers_Compile.Result<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>> _pat_let18_0 = ((Wrappers_Compile.Result<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>)(java.lang.Object)(boxed36));
        return ((Wrappers_Compile.Result<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>>)(java.lang.Object)(dafny.Helpers.<Wrappers_Compile.Result<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>, Wrappers_Compile.Result<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>>>Let(_pat_let18_0, boxed37 -> {
          Wrappers_Compile.Result<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>> _6_valueOrError1 = ((Wrappers_Compile.Result<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>)(java.lang.Object)(boxed37));
          return (((_6_valueOrError1).IsFailure(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR))) ? ((_6_valueOrError1).<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>PropagateFailure(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor()))) : (((Wrappers_Compile.Result<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>>)(java.lang.Object)(dafny.Helpers.<dafny.DafnySequence<? extends Character>, Wrappers_Compile.Result<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>>>Let((_6_valueOrError1).Extract(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), boxed38 -> {
            dafny.DafnySequence<? extends Character> _pat_let19_0 = ((dafny.DafnySequence<? extends Character>)(java.lang.Object)(boxed38));
            return ((Wrappers_Compile.Result<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>>)(java.lang.Object)(dafny.Helpers.<dafny.DafnySequence<? extends Character>, Wrappers_Compile.Result<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>>>Let(_pat_let19_0, boxed39 -> {
              dafny.DafnySequence<? extends Character> _7_key = ((dafny.DafnySequence<? extends Character>)(java.lang.Object)(boxed39));
              return ((Wrappers_Compile.Result<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>>)(java.lang.Object)(dafny.Helpers.<Wrappers_Compile.Result<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>, Wrappers_Compile.Result<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>>>Let(UTF8.__default.Decode(((dafny.DafnySequence<? extends java.lang.Byte>)(java.lang.Object)((_4_m).get(_5_k)))), boxed40 -> {
                Wrappers_Compile.Result<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>> _pat_let20_0 = ((Wrappers_Compile.Result<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>)(java.lang.Object)(boxed40));
                return ((Wrappers_Compile.Result<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>>)(java.lang.Object)(dafny.Helpers.<Wrappers_Compile.Result<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>, Wrappers_Compile.Result<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>>>Let(_pat_let20_0, boxed41 -> {
                  Wrappers_Compile.Result<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>> _8_valueOrError2 = ((Wrappers_Compile.Result<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>)(java.lang.Object)(boxed41));
                  return (((_8_valueOrError2).IsFailure(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR))) ? ((_8_valueOrError2).<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>PropagateFailure(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor()))) : (((Wrappers_Compile.Result<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>>)(java.lang.Object)(dafny.Helpers.<dafny.DafnySequence<? extends Character>, Wrappers_Compile.Result<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>>>Let((_8_valueOrError2).Extract(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), boxed42 -> {
                    dafny.DafnySequence<? extends Character> _pat_let21_0 = ((dafny.DafnySequence<? extends Character>)(java.lang.Object)(boxed42));
                    return ((Wrappers_Compile.Result<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>>)(java.lang.Object)(dafny.Helpers.<dafny.DafnySequence<? extends Character>, Wrappers_Compile.Result<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>>>Let(_pat_let21_0, boxed43 -> {
                      dafny.DafnySequence<? extends Character> _9_value = ((dafny.DafnySequence<? extends Character>)(java.lang.Object)(boxed43));
                      return Wrappers_Compile.Result.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>>create_Success(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor()), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(_7_key, JSON_mValues_Compile.JSON.create_String(_9_value)));
                    }
                    )));
                  }
                  )))));
                }
                )));
              }
              )));
            }
            )));
          }
          )))));
        }
        )));
      }
      )));
    })).apply(m), _0_keys);
    if ((_3_valueOrError0).IsFailure(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR))) {
      return (_3_valueOrError0).<dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>>PropagateFailure(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())));
    } else {
      dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> _10_pairsBytes = (_3_valueOrError0).Extract(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR));
      return Wrappers_Compile.Result.<dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>, dafny.DafnySequence<? extends Character>>create_Success(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> of(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor()), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(key, JSON_mValues_Compile.JSON.create_Object(_10_pairsBytes))));
    }
  }
  public static dafny.Tuple0 printJson(JSON_mValues_Compile.JSON j)
  {
    dafny.Tuple0 _hresult = dafny.Tuple0.Default();
    System.out.print(java.lang.String.valueOf(j));
    System.out.print((dafny.DafnySequence.asString("\n")).verbatimString());
    System.out.print((dafny.DafnySequence.asString("\n")).verbatimString());
    _hresult = dafny.Tuple0.create();
    return _hresult;
  }
  public static Wrappers_Compile.Result<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>> EncryptTestVectorToJson(TestVectors_Compile.EncryptTestVector test) {
    dafny.DafnySequence<? extends Character> _0_id = AllAlgorithmSuites_Compile.__default.ToHex((test).dtor_algorithmSuite());
    dafny.DafnySequence<? extends Character> _1_description = dafny.DafnySequence.<Character>concatenate(dafny.DafnySequence.<Character>concatenate((test).dtor_name(), dafny.DafnySequence.asString(" ")), _0_id);
    Wrappers_Compile.Result<dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>, dafny.DafnySequence<? extends Character>> _2_valueOrError0 = __default.EncryptionContextToJson(dafny.DafnySequence.asString("encryptionContext"), (test).dtor_encryptionContext());
    if ((_2_valueOrError0).IsFailure(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR))) {
      return (_2_valueOrError0).<JSON_mValues_Compile.JSON>PropagateFailure(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor());
    } else {
      dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> _3_encryptionContext = (_2_valueOrError0).Extract(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR));
      dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> _4_maxPlaintextL = ((((test).dtor_maxPlaintextLength()).is_Some()) ? (dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> of(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor()), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("maxPlaintextLength"), JSON_mValues_Compile.JSON.create_Number(JSON_mValues_Compile.__default.Int(java.math.BigInteger.valueOf(((test).dtor_maxPlaintextLength()).dtor_value())))))) : (dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> empty(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor()))));
      Wrappers_Compile.Result<dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>, dafny.DafnySequence<? extends Character>> _5_valueOrError1 = __default.EncryptionContextKeysToJson((test).dtor_requiredEncryptionContextKeys());
      if ((_5_valueOrError1).IsFailure(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR))) {
        return (_5_valueOrError1).<JSON_mValues_Compile.JSON>PropagateFailure(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor());
      } else {
        dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> _6_requiredEncryptionContextKeys = (_5_valueOrError1).Extract(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR));
        Wrappers_Compile.Result<dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>, dafny.DafnySequence<? extends Character>> _7_valueOrError2 = (((!((test).is_NegativeEncryptKeyringVector())) && (((test).dtor_reproducedEncryptionContext()).is_Some())) ? (__default.EncryptionContextToJson(dafny.DafnySequence.asString("reproducedEncryptionContext"), ((test).dtor_reproducedEncryptionContext()).dtor_value())) : (Wrappers_Compile.Result.<dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>, dafny.DafnySequence<? extends Character>>create_Success(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> empty(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())))));
        if ((_7_valueOrError2).IsFailure(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR))) {
          return (_7_valueOrError2).<JSON_mValues_Compile.JSON>PropagateFailure(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor());
        } else {
          dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> _8_reproducedEc = (_7_valueOrError2).Extract(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR));
          dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> _9_optionalValues = dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>concatenate(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>concatenate(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>concatenate(_8_reproducedEc, _4_maxPlaintextL), _6_requiredEncryptionContextKeys), _3_encryptionContext);
          TestVectors_Compile.EncryptTestVector _source0 = test;
          if (_source0.is_PositiveEncryptKeyringVector()) {
            dafny.DafnySequence<? extends Character> _10___mcc_h0 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptKeyringVector)_source0)._name;
            Wrappers_Compile.Option<dafny.DafnySequence<? extends Character>> _11___mcc_h1 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptKeyringVector)_source0)._description;
            dafny.DafnyMap<? extends dafny.DafnySequence<? extends java.lang.Byte>, ? extends dafny.DafnySequence<? extends java.lang.Byte>> _12___mcc_h2 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptKeyringVector)_source0)._encryptionContext;
            software.amazon.cryptography.materialproviders.internaldafny.types.CommitmentPolicy _13___mcc_h3 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptKeyringVector)_source0)._commitmentPolicy;
            software.amazon.cryptography.materialproviders.internaldafny.types.AlgorithmSuiteInfo _14___mcc_h4 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptKeyringVector)_source0)._algorithmSuite;
            Wrappers_Compile.Option<java.lang.Long> _15___mcc_h5 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptKeyringVector)_source0)._maxPlaintextLength;
            Wrappers_Compile.Option<dafny.DafnySequence<? extends dafny.DafnySequence<? extends java.lang.Byte>>> _16___mcc_h6 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptKeyringVector)_source0)._requiredEncryptionContextKeys;
            software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription _17___mcc_h7 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptKeyringVector)_source0)._encryptDescription;
            software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription _18___mcc_h8 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptKeyringVector)_source0)._decryptDescription;
            Wrappers_Compile.Option<dafny.DafnyMap<? extends dafny.DafnySequence<? extends java.lang.Byte>, ? extends dafny.DafnySequence<? extends java.lang.Byte>>> _19___mcc_h9 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptKeyringVector)_source0)._reproducedEncryptionContext;
            Wrappers_Compile.Result<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>> _20_valueOrError3 = KeyDescription_Compile.__default.ToJson((test).dtor_encryptDescription(), java.math.BigInteger.valueOf(3L));
            if ((_20_valueOrError3).IsFailure(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR))) {
              return (_20_valueOrError3).<JSON_mValues_Compile.JSON>PropagateFailure(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor());
            } else {
              JSON_mValues_Compile.JSON _21_encrypt = (_20_valueOrError3).Extract(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR));
              Wrappers_Compile.Result<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>> _22_valueOrError4 = KeyDescription_Compile.__default.ToJson((test).dtor_decryptDescription(), java.math.BigInteger.valueOf(3L));
              if ((_22_valueOrError4).IsFailure(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR))) {
                return (_22_valueOrError4).<JSON_mValues_Compile.JSON>PropagateFailure(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor());
              } else {
                JSON_mValues_Compile.JSON _23_decrypt = (_22_valueOrError4).Extract(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR));
                return Wrappers_Compile.Result.<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>>create_Success(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON.create_Object(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>concatenate(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> of(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor()), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("type"), JSON_mValues_Compile.JSON.create_String(dafny.DafnySequence.asString("positive-keyring"))), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("description"), JSON_mValues_Compile.JSON.create_String(_1_description)), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("algorithmSuiteId"), JSON_mValues_Compile.JSON.create_String(_0_id)), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("encryptKeyDescription"), _21_encrypt), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("decryptKeyDescription"), _23_decrypt)), _9_optionalValues)));
              }
            }
          } else if (_source0.is_PositiveEncryptNegativeDecryptKeyringVector()) {
            dafny.DafnySequence<? extends Character> _24___mcc_h10 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptNegativeDecryptKeyringVector)_source0)._name;
            Wrappers_Compile.Option<dafny.DafnySequence<? extends Character>> _25___mcc_h11 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptNegativeDecryptKeyringVector)_source0)._description;
            dafny.DafnyMap<? extends dafny.DafnySequence<? extends java.lang.Byte>, ? extends dafny.DafnySequence<? extends java.lang.Byte>> _26___mcc_h12 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptNegativeDecryptKeyringVector)_source0)._encryptionContext;
            software.amazon.cryptography.materialproviders.internaldafny.types.CommitmentPolicy _27___mcc_h13 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptNegativeDecryptKeyringVector)_source0)._commitmentPolicy;
            software.amazon.cryptography.materialproviders.internaldafny.types.AlgorithmSuiteInfo _28___mcc_h14 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptNegativeDecryptKeyringVector)_source0)._algorithmSuite;
            Wrappers_Compile.Option<java.lang.Long> _29___mcc_h15 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptNegativeDecryptKeyringVector)_source0)._maxPlaintextLength;
            Wrappers_Compile.Option<dafny.DafnySequence<? extends dafny.DafnySequence<? extends java.lang.Byte>>> _30___mcc_h16 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptNegativeDecryptKeyringVector)_source0)._requiredEncryptionContextKeys;
            dafny.DafnySequence<? extends Character> _31___mcc_h17 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptNegativeDecryptKeyringVector)_source0)._decryptErrorDescription;
            software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription _32___mcc_h18 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptNegativeDecryptKeyringVector)_source0)._encryptDescription;
            software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription _33___mcc_h19 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptNegativeDecryptKeyringVector)_source0)._decryptDescription;
            Wrappers_Compile.Option<dafny.DafnyMap<? extends dafny.DafnySequence<? extends java.lang.Byte>, ? extends dafny.DafnySequence<? extends java.lang.Byte>>> _34___mcc_h20 = ((TestVectors_Compile.EncryptTestVector_PositiveEncryptNegativeDecryptKeyringVector)_source0)._reproducedEncryptionContext;
            Wrappers_Compile.Result<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>> _35_valueOrError5 = KeyDescription_Compile.__default.ToJson((test).dtor_encryptDescription(), java.math.BigInteger.valueOf(3L));
            if ((_35_valueOrError5).IsFailure(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR))) {
              return (_35_valueOrError5).<JSON_mValues_Compile.JSON>PropagateFailure(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor());
            } else {
              JSON_mValues_Compile.JSON _36_encrypt = (_35_valueOrError5).Extract(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR));
              Wrappers_Compile.Result<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>> _37_valueOrError6 = KeyDescription_Compile.__default.ToJson((test).dtor_decryptDescription(), java.math.BigInteger.valueOf(3L));
              if ((_37_valueOrError6).IsFailure(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR))) {
                return (_37_valueOrError6).<JSON_mValues_Compile.JSON>PropagateFailure(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor());
              } else {
                JSON_mValues_Compile.JSON _38_decrypt = (_37_valueOrError6).Extract(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR));
                return Wrappers_Compile.Result.<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>>create_Success(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON.create_Object(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>concatenate(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> of(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor()), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("type"), JSON_mValues_Compile.JSON.create_String(dafny.DafnySequence.asString("negative-decrypt-keyring"))), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("description"), JSON_mValues_Compile.JSON.create_String(_1_description)), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("decryptErrorDescription"), JSON_mValues_Compile.JSON.create_String((test).dtor_decryptErrorDescription())), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("algorithmSuiteId"), JSON_mValues_Compile.JSON.create_String(_0_id)), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("encryptKeyDescription"), _36_encrypt), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("decryptKeyDescription"), _38_decrypt)), _9_optionalValues)));
              }
            }
          } else {
            dafny.DafnySequence<? extends Character> _39___mcc_h21 = ((TestVectors_Compile.EncryptTestVector_NegativeEncryptKeyringVector)_source0)._name;
            Wrappers_Compile.Option<dafny.DafnySequence<? extends Character>> _40___mcc_h22 = ((TestVectors_Compile.EncryptTestVector_NegativeEncryptKeyringVector)_source0)._description;
            dafny.DafnyMap<? extends dafny.DafnySequence<? extends java.lang.Byte>, ? extends dafny.DafnySequence<? extends java.lang.Byte>> _41___mcc_h23 = ((TestVectors_Compile.EncryptTestVector_NegativeEncryptKeyringVector)_source0)._encryptionContext;
            software.amazon.cryptography.materialproviders.internaldafny.types.CommitmentPolicy _42___mcc_h24 = ((TestVectors_Compile.EncryptTestVector_NegativeEncryptKeyringVector)_source0)._commitmentPolicy;
            software.amazon.cryptography.materialproviders.internaldafny.types.AlgorithmSuiteInfo _43___mcc_h25 = ((TestVectors_Compile.EncryptTestVector_NegativeEncryptKeyringVector)_source0)._algorithmSuite;
            Wrappers_Compile.Option<java.lang.Long> _44___mcc_h26 = ((TestVectors_Compile.EncryptTestVector_NegativeEncryptKeyringVector)_source0)._maxPlaintextLength;
            Wrappers_Compile.Option<dafny.DafnySequence<? extends dafny.DafnySequence<? extends java.lang.Byte>>> _45___mcc_h27 = ((TestVectors_Compile.EncryptTestVector_NegativeEncryptKeyringVector)_source0)._requiredEncryptionContextKeys;
            dafny.DafnySequence<? extends Character> _46___mcc_h28 = ((TestVectors_Compile.EncryptTestVector_NegativeEncryptKeyringVector)_source0)._errorDescription;
            software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription _47___mcc_h29 = ((TestVectors_Compile.EncryptTestVector_NegativeEncryptKeyringVector)_source0)._keyDescription;
            Wrappers_Compile.Result<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>> _48_valueOrError7 = KeyDescription_Compile.__default.ToJson((test).dtor_keyDescription(), java.math.BigInteger.valueOf(3L));
            if ((_48_valueOrError7).IsFailure(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR))) {
              return (_48_valueOrError7).<JSON_mValues_Compile.JSON>PropagateFailure(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor());
            } else {
              JSON_mValues_Compile.JSON _49_keyDescription = (_48_valueOrError7).Extract(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR));
              return Wrappers_Compile.Result.<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>>create_Success(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON.create_Object(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>concatenate(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> of(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor()), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("type"), JSON_mValues_Compile.JSON.create_String(dafny.DafnySequence.asString("negative-encrypt-keyring"))), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("description"), JSON_mValues_Compile.JSON.create_String(_1_description)), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("errorDescription"), JSON_mValues_Compile.JSON.create_String((test).dtor_errorDescription())), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("algorithmSuiteId"), JSON_mValues_Compile.JSON.create_String(_0_id)), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("keyDescription"), _49_keyDescription)), _9_optionalValues)));
            }
          }
        }
      }
    }
  }
  public static dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> OptionalBytes(dafny.DafnySequence<? extends Character> key, Wrappers_Compile.Option<dafny.DafnySequence<? extends java.lang.Byte>> secret)
  {
    if ((secret).is_Some()) {
      dafny.DafnySequence<? extends Character> _0_base64 = Base64_Compile.__default.Encode((secret).dtor_value());
      return dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> of(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor()), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(key, JSON_mValues_Compile.JSON.create_String(_0_base64)));
    } else {
      return dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> empty(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor()));
    }
  }
  public static Wrappers_Compile.Result<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>> EncryptedDataKey(software.amazon.cryptography.materialproviders.internaldafny.types.EncryptedDataKey encryptedDataKey) {
    Wrappers_Compile.Result<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>> _0_valueOrError0 = UTF8.__default.Decode((encryptedDataKey).dtor_keyProviderId());
    if ((_0_valueOrError0).IsFailure(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR))) {
      return (_0_valueOrError0).<JSON_mValues_Compile.JSON>PropagateFailure(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor());
    } else {
      dafny.DafnySequence<? extends Character> _1_keyProviderId = (_0_valueOrError0).Extract(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR));
      return Wrappers_Compile.Result.<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>>create_Success(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON.create_Object(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> of(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor()), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("keyProviderId"), JSON_mValues_Compile.JSON.create_String(_1_keyProviderId)), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("keyProviderInfo"), JSON_mValues_Compile.JSON.create_String(Base64_Compile.__default.Encode((encryptedDataKey).dtor_keyProviderInfo()))), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("ciphertext"), JSON_mValues_Compile.JSON.create_String(Base64_Compile.__default.Encode((encryptedDataKey).dtor_ciphertext()))))));
    }
  }
  public static Wrappers_Compile.Result<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>> DecryptTestVectorToJson(TestVectors_Compile.DecryptTestVector test) {
    dafny.DafnySequence<? extends Character> _0_id = AllAlgorithmSuites_Compile.__default.ToHex((test).dtor_algorithmSuite());
    dafny.DafnySequence<? extends Character> _1_description = dafny.DafnySequence.<Character>concatenate(dafny.DafnySequence.<Character>concatenate((test).dtor_name(), dafny.DafnySequence.asString(" ")), _0_id);
    Wrappers_Compile.Result<dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>, dafny.DafnySequence<? extends Character>> _2_valueOrError0 = __default.EncryptionContextToJson(dafny.DafnySequence.asString("encryptionContext"), (test).dtor_encryptionContext());
    if ((_2_valueOrError0).IsFailure(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR))) {
      return (_2_valueOrError0).<JSON_mValues_Compile.JSON>PropagateFailure(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor());
    } else {
      dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> _3_encryptionContext = (_2_valueOrError0).Extract(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR));
      Wrappers_Compile.Result<dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>, dafny.DafnySequence<? extends Character>> _4_valueOrError1 = ((((test).dtor_reproducedEncryptionContext()).is_Some()) ? (__default.EncryptionContextToJson(dafny.DafnySequence.asString("reproducedEncryptionContext"), ((test).dtor_reproducedEncryptionContext()).dtor_value())) : (Wrappers_Compile.Result.<dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>, dafny.DafnySequence<? extends Character>>create_Success(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> empty(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())))));
      if ((_4_valueOrError1).IsFailure(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR))) {
        return (_4_valueOrError1).<JSON_mValues_Compile.JSON>PropagateFailure(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor());
      } else {
        dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> _5_reproducedEc = (_4_valueOrError1).Extract(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR));
        Wrappers_Compile.Result<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>> _6_valueOrError2 = KeyDescription_Compile.__default.ToJson((test).dtor_keyDescription(), java.math.BigInteger.valueOf(3L));
        if ((_6_valueOrError2).IsFailure(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR))) {
          return (_6_valueOrError2).<JSON_mValues_Compile.JSON>PropagateFailure(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor());
        } else {
          JSON_mValues_Compile.JSON _7_keyDescription = (_6_valueOrError2).Extract(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR));
          Wrappers_Compile.Result<dafny.DafnySequence<? extends JSON_mValues_Compile.JSON>, dafny.DafnySequence<? extends Character>> _8_valueOrError3 = Seq_Compile.__default.<software.amazon.cryptography.materialproviders.internaldafny.types.EncryptedDataKey, JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>>MapWithResult(software.amazon.cryptography.materialproviders.internaldafny.types.EncryptedDataKey._typeDescriptor(), JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), ((java.util.function.Function<software.amazon.cryptography.materialproviders.internaldafny.types.EncryptedDataKey, Wrappers_Compile.Result<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>>>)(_9_edk_boxed0) -> {
            software.amazon.cryptography.materialproviders.internaldafny.types.EncryptedDataKey _9_edk = ((software.amazon.cryptography.materialproviders.internaldafny.types.EncryptedDataKey)(java.lang.Object)(_9_edk_boxed0));
            return __default.EncryptedDataKey(_9_edk);
          }), (test).dtor_encryptedDataKeys());
          if ((_8_valueOrError3).IsFailure(dafny.DafnySequence.<JSON_mValues_Compile.JSON>_typeDescriptor(JSON_mValues_Compile.JSON._typeDescriptor()), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR))) {
            return (_8_valueOrError3).<JSON_mValues_Compile.JSON>PropagateFailure(dafny.DafnySequence.<JSON_mValues_Compile.JSON>_typeDescriptor(JSON_mValues_Compile.JSON._typeDescriptor()), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor());
          } else {
            dafny.DafnySequence<? extends JSON_mValues_Compile.JSON> _10_encryptedDataKeys = (_8_valueOrError3).Extract(dafny.DafnySequence.<JSON_mValues_Compile.JSON>_typeDescriptor(JSON_mValues_Compile.JSON._typeDescriptor()), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR));
            TestVectors_Compile.DecryptTestVector _source0 = test;
            if (_source0.is_PositiveDecryptKeyringTest()) {
              dafny.DafnySequence<? extends Character> _11___mcc_h0 = ((TestVectors_Compile.DecryptTestVector_PositiveDecryptKeyringTest)_source0)._name;
              software.amazon.cryptography.materialproviders.internaldafny.types.AlgorithmSuiteInfo _12___mcc_h1 = ((TestVectors_Compile.DecryptTestVector_PositiveDecryptKeyringTest)_source0)._algorithmSuite;
              software.amazon.cryptography.materialproviders.internaldafny.types.CommitmentPolicy _13___mcc_h2 = ((TestVectors_Compile.DecryptTestVector_PositiveDecryptKeyringTest)_source0)._commitmentPolicy;
              dafny.DafnySequence<? extends software.amazon.cryptography.materialproviders.internaldafny.types.EncryptedDataKey> _14___mcc_h3 = ((TestVectors_Compile.DecryptTestVector_PositiveDecryptKeyringTest)_source0)._encryptedDataKeys;
              dafny.DafnyMap<? extends dafny.DafnySequence<? extends java.lang.Byte>, ? extends dafny.DafnySequence<? extends java.lang.Byte>> _15___mcc_h4 = ((TestVectors_Compile.DecryptTestVector_PositiveDecryptKeyringTest)_source0)._encryptionContext;
              software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription _16___mcc_h5 = ((TestVectors_Compile.DecryptTestVector_PositiveDecryptKeyringTest)_source0)._keyDescription;
              TestVectors_Compile.DecryptResult _17___mcc_h6 = ((TestVectors_Compile.DecryptTestVector_PositiveDecryptKeyringTest)_source0)._expectedResult;
              Wrappers_Compile.Option<dafny.DafnySequence<? extends Character>> _18___mcc_h7 = ((TestVectors_Compile.DecryptTestVector_PositiveDecryptKeyringTest)_source0)._description;
              Wrappers_Compile.Option<dafny.DafnyMap<? extends dafny.DafnySequence<? extends java.lang.Byte>, ? extends dafny.DafnySequence<? extends java.lang.Byte>>> _19___mcc_h8 = ((TestVectors_Compile.DecryptTestVector_PositiveDecryptKeyringTest)_source0)._reproducedEncryptionContext;
              dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> _20_plaintextDataKey = __default.OptionalBytes(dafny.DafnySequence.asString("plaintextDataKey"), ((test).dtor_expectedResult()).dtor_plaintextDataKey());
              dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> _21_symmetricSigningKey = __default.OptionalBytes(dafny.DafnySequence.asString("symmetricSigningKey"), ((test).dtor_expectedResult()).dtor_symmetricSigningKey());
              Wrappers_Compile.Result<dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>, dafny.DafnySequence<? extends Character>> _22_valueOrError4 = __default.EncryptionContextKeysToJson(Wrappers_Compile.Option.<dafny.DafnySequence<? extends dafny.DafnySequence<? extends java.lang.Byte>>>create_Some(dafny.DafnySequence.<dafny.DafnySequence<? extends java.lang.Byte>>_typeDescriptor(UTF8.ValidUTF8Bytes._typeDescriptor()), ((test).dtor_expectedResult()).dtor_requiredEncryptionContextKeys()));
              if ((_22_valueOrError4).IsFailure(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR))) {
                return (_22_valueOrError4).<JSON_mValues_Compile.JSON>PropagateFailure(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor());
              } else {
                dafny.DafnySequence<? extends dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> _23_requiredEncryptionContextKeys = (_22_valueOrError4).Extract(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>_typeDescriptor(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor())), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR));
                return Wrappers_Compile.Result.<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>>create_Success(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON.create_Object(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>concatenate(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>concatenate(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> of(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor()), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("type"), JSON_mValues_Compile.JSON.create_String(dafny.DafnySequence.asString("positive-keyring"))), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("description"), JSON_mValues_Compile.JSON.create_String(_1_description)), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("algorithmSuiteId"), JSON_mValues_Compile.JSON.create_String(_0_id)), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("keyDescription"), _7_keyDescription), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("encryptedDataKeys"), JSON_mValues_Compile.JSON.create_Array(_10_encryptedDataKeys)), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("result"), JSON_mValues_Compile.JSON.create_Object(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>concatenate(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>concatenate(_20_plaintextDataKey, _21_symmetricSigningKey), _23_requiredEncryptionContextKeys)))), _5_reproducedEc), _3_encryptionContext)));
              }
            } else {
              dafny.DafnySequence<? extends Character> _24___mcc_h9 = ((TestVectors_Compile.DecryptTestVector_NegativeDecryptKeyringTest)_source0)._name;
              software.amazon.cryptography.materialproviders.internaldafny.types.AlgorithmSuiteInfo _25___mcc_h10 = ((TestVectors_Compile.DecryptTestVector_NegativeDecryptKeyringTest)_source0)._algorithmSuite;
              software.amazon.cryptography.materialproviders.internaldafny.types.CommitmentPolicy _26___mcc_h11 = ((TestVectors_Compile.DecryptTestVector_NegativeDecryptKeyringTest)_source0)._commitmentPolicy;
              dafny.DafnySequence<? extends software.amazon.cryptography.materialproviders.internaldafny.types.EncryptedDataKey> _27___mcc_h12 = ((TestVectors_Compile.DecryptTestVector_NegativeDecryptKeyringTest)_source0)._encryptedDataKeys;
              dafny.DafnyMap<? extends dafny.DafnySequence<? extends java.lang.Byte>, ? extends dafny.DafnySequence<? extends java.lang.Byte>> _28___mcc_h13 = ((TestVectors_Compile.DecryptTestVector_NegativeDecryptKeyringTest)_source0)._encryptionContext;
              dafny.DafnySequence<? extends Character> _29___mcc_h14 = ((TestVectors_Compile.DecryptTestVector_NegativeDecryptKeyringTest)_source0)._errorDescription;
              software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription _30___mcc_h15 = ((TestVectors_Compile.DecryptTestVector_NegativeDecryptKeyringTest)_source0)._keyDescription;
              Wrappers_Compile.Option<dafny.DafnyMap<? extends dafny.DafnySequence<? extends java.lang.Byte>, ? extends dafny.DafnySequence<? extends java.lang.Byte>>> _31___mcc_h16 = ((TestVectors_Compile.DecryptTestVector_NegativeDecryptKeyringTest)_source0)._reproducedEncryptionContext;
              Wrappers_Compile.Option<dafny.DafnySequence<? extends Character>> _32___mcc_h17 = ((TestVectors_Compile.DecryptTestVector_NegativeDecryptKeyringTest)_source0)._description;
              return Wrappers_Compile.Result.<JSON_mValues_Compile.JSON, dafny.DafnySequence<? extends Character>>create_Success(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON.create_Object(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>concatenate(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>>concatenate(dafny.DafnySequence.<dafny.Tuple2<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>> of(dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), JSON_mValues_Compile.JSON._typeDescriptor()), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("type"), JSON_mValues_Compile.JSON.create_String(dafny.DafnySequence.asString("negative-keyring"))), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("description"), JSON_mValues_Compile.JSON.create_String(_1_description)), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("errorDescription"), JSON_mValues_Compile.JSON.create_String((test).dtor_errorDescription())), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("algorithmSuiteId"), JSON_mValues_Compile.JSON.create_String(_0_id)), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("keyDescription"), _7_keyDescription), dafny.Tuple2.<dafny.DafnySequence<? extends Character>, JSON_mValues_Compile.JSON>create(dafny.DafnySequence.asString("encryptedDataKeys"), JSON_mValues_Compile.JSON.create_Array(_10_encryptedDataKeys))), _5_reproducedEc), _3_encryptionContext)));
            }
          }
        }
      }
    }
  }
  @Override
  public java.lang.String toString() {
    return "WriteJsonManifests._default";
  }
}
