version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: "gradle"
    directories:
      - "StandardLibrary/runtimes/java"
      - "ComAmazonawsKms/runtimes/java"
      - "ComAmazonawsDynamodb/runtimes/java"
      - "AwsCryptographyPrimitives/runtimes/java"
      - "AwsCryptographicMaterialProviders/runtimes/java"
      - "TestVectorsAwsCryptographicMaterialProviders/runtimes/java"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: "nuget"
    directories:
      - "StandardLibrary/runtimes/net"
      - "ComAmazonawsKms/runtimes/net"
      - "ComAmazonawsDynamodb/runtimes/net"
      - "AwsCryptographyPrimitives/runtimes/net"
      - "AwsCryptographicMaterialProviders/runtimes/net"
      - "TestVectorsAwsCryptographicMaterialProviders/runtimes/net"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: "gomod"
    directories:
      - "StandardLibrary/runtimes/go"
      - "ComAmazonawsKms/runtimes/go"
      - "ComAmazonawsDynamodb/runtimes/go"
      - "AwsCryptographyPrimitives/runtimes/go"
      - "AwsCryptographicMaterialProviders/runtimes/go"
      - "TestVectorsAwsCryptographicMaterialProviders/runtimes/go"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: "pip"
    directories:
      - "StandardLibrary/runtimes/python"
      - "ComAmazonawsKms/runtimes/python"
      - "ComAmazonawsDynamodb/runtimes/python"
      - "AwsCryptographyPrimitives/runtimes/python"
      - "AwsCryptographicMaterialProviders/runtimes/python"
      - "TestVectorsAwsCryptographicMaterialProviders/runtimes/python"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: "cargo"
    directories:
      - "StandardLibrary/runtimes/rust"
      - "ComAmazonawsKms/runtimes/rust"
      - "ComAmazonawsDynamodb/runtimes/rust"
      - "AwsCryptographyPrimitives/runtimes/rust"
      - "AwsCryptographicMaterialProviders/runtimes/rust"
      - "TestVectorsAwsCryptographicMaterialProviders/runtimes/rust"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: ["*"]
