version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "AwsCryptographicMaterialProviders/runtimes/java"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "daily"
  # STD NET
  - package-ecosystem: "nuget"
    directory: "StandardLibrary/runtimes/net"
    schedule:
      interval: "daily"
  # KMS NET
  - package-ecosystem: "nuget"
    directory: "ComAmazonawsKms/runtimes/net"
    schedule:
      interval: "daily"
  # DDB NET
  - package-ecosystem: "nuget"
    directory: "ComAmazonawsDynamodb/runtimes/net"
    schedule:
      interval: "daily"
  # Crypto NET
  - package-ecosystem: "nuget"
    directory: "AwsCryptographyPrimitives/runtimes/net"
    schedule:
      interval: "daily"
  # MPL NET
  - package-ecosystem: "nuget"
    directory: "AwsCryptographicMaterialProviders/runtimes/net"
    schedule:
      interval: "daily"
  # Test Vectors NET
  - package-ecosystem: "nuget"
    directory: "TestVectorsAwsCryptographicMaterialProviders/runtimes/net"
    schedule:
      interval: "daily"
