version: 0.2

env:
  variables:
    BRANCH: "main"
  secrets-manager:
    TWINE_USERNAME: PyPiAPIToken:username
    TWINE_PASSWORD: PyPiAPIToken:password

phases:
  install:
    commands:
      - pip install "tox < 4.0"
      - pip install --upgrade pip
    runtime-versions:
      python: latest
  pre_build:
    commands:
      - git checkout $COMMIT_ID
      - FOUND_VERSION=$(sed -n 's/version = "\(.*\)"/\1/p' StandardLibrary/runtimes/python/pyproject.toml)
      - |
        if expr ${FOUND_VERSION} != ${VERSION}; then
          echo "pyproject.toml version (${FOUND_VERSION}) does not match expected version (${VERSION}), stopping"
          exit 1;
        fi
  build:
    commands:
      - echo "Skipping prod release until we are ready to release the MPL"

batch:
  fast-fail: true
  build-graph:
    - identifier: release_to_prod
    - identifier: validate_prod_release
      depend-on:
        - release_to_prod
      buildspec: codebuild/release-python/validate.yml
      env:
        variables:
          PIP_INDEX_URL: https://pypi.python.org/simple/
