// The AWS Cryptographic Material Providers Library (MPL) TestServer wire contract.
//
// This file is the SINGLE SOURCE OF TRUTH for the TestServer (Requirement 1.1).
// Both the one generated Java Test_Client (../client-java) and the Java
// Language_Server's scaffolding (../servers/java) are generated from it, so the
// two ends of the wire cannot drift.
//
// PLAIN SMITHY 2.0 ONLY (Requirement 1.2). The MPL's own model uses
// `aws.polymorph` traits, which are consumed by the MPL's bespoke smithy-dafny
// generator. This harness is generated by STANDARD tooling (smithy-java), so it
// uses only standard constructs. In particular it does NOT use
// `aws.polymorph#reference`, `#positional`, `#extendable`, or `#javadoc`.
//
// WHY HANDLES: every MPL constructor returns an `aws.polymorph#reference` to a
// resource -- a Keyring, a CryptographicMaterialsManager, a
// CryptographicMaterialsCache. A reference cannot cross a wire. So each Create*
// operation here returns an opaque UUID `ResourceId` into a server-side
// registry, and every operation on a created resource takes that id back
// (Requirement 3). This is not a convenience indirection; it is the only way to
// model the MPL's API at all.

$version: "2.0"

namespace aws.cryptography.materialProviders.testServer

use smithy.protocols#rpcv2Cbor

/// The MPL TestServer.
///
/// The protocol is declared exactly once, here at the service level
/// (Requirement 1.3). rpcv2Cbor needs no per-operation HTTP binding traits, so
/// this single trait describes the entire transport.
@rpcv2Cbor
service MPLTestServer {
    version: "2026-07-27"
    operations: [
        CreateMPL
        CreateRawAesKeyring
        CreateRawRsaKeyring
        CreateMultiKeyring
        InitializeEncryptionMaterials
        InitializeDecryptionMaterials
        OnEncrypt
        OnDecrypt
    ]
    errors: [
        GenericServerError
        MaterialProvidersClientError
    ]
}

// ---------------------------------------------------------------------------
// Errors (Requirement 4)
// ---------------------------------------------------------------------------

/// A failure originating in the TestServer framework itself: an absent, empty,
/// unknown, or wrong-kind ResourceId; a malformed request; an unrecognized
/// operation; or a Resource_Registry failure (Requirement 4.3).
///
/// Never used for a failure raised by the MPL -- that is
/// MaterialProvidersClientError. The distinction is what lets a test tell a
/// harness defect from MPL behavior.
@error("client")
structure GenericServerError {
    @required
    message: String
}

/// A failure raised by the Artifact_Under_Test (the MPL), forwarded with the
/// MPL's own message unmodified so tests can assert on it (Requirement 4.4).
@error("client")
structure MaterialProvidersClientError {
    @required
    message: String
}

// ---------------------------------------------------------------------------
// Resource handles (Requirement 3)
// ---------------------------------------------------------------------------

/// An opaque handle to a server-side MPL resource, in UUID form.
///
/// One shape is used for every kind of handle. The server-side registry is
/// typed, so supplying a keyring handle where a MaterialProviders handle is
/// expected is a GenericServerError naming both kinds rather than an opaque
/// server fault (Requirement 3.9, 3.10).
@length(min: 1)
string ResourceId

/// A list of resource handles. Used where the MPL's own API takes a list of
/// resource references (Requirement 3.11).
list ResourceIdList {
    member: ResourceId
}

// ---------------------------------------------------------------------------
// CreateMPL
// ---------------------------------------------------------------------------

/// Construct a MaterialProviders instance -- the root of the
/// Artifact_Under_Test -- and return a handle to it (Requirement 3.2).
///
/// Every other Create* operation takes the returned handle, so a test can hold
/// several independently configured MaterialProviders instances at once.
operation CreateMPL {
    input := {
        /// The MaterialProviders configuration.
        ///
        /// Modeled as a structure even though the MPL's own
        /// `MaterialProvidersConfig` is currently empty, so that when the MPL
        /// gives it members this operation's signature does not change.
        @required
        config: MaterialProvidersConfig
    }

    output := {
        /// A handle to the constructed MaterialProviders instance.
        @required
        mplId: ResourceId
    }

    errors: [
        GenericServerError
        MaterialProvidersClientError
    ]
}

/// Mirrors the MPL's `MaterialProvidersConfig`, which is an empty structure
/// today (see the MPL's own `material-provider.smithy`).
structure MaterialProvidersConfig {}

// ---------------------------------------------------------------------------
// Algorithm suites (Requirement 2.2, 8.1)
// ---------------------------------------------------------------------------

/// Mirrors the MPL's `ESDKAlgorithmSuiteId`, with the MPL's exact constant names and
/// values, so a value round-trips through `Enum.valueOf` on the server without a
/// translation table.
enum ESDKAlgorithmSuiteId {
    ALG_AES_128_GCM_IV12_TAG16_NO_KDF = "0x0014"
    ALG_AES_192_GCM_IV12_TAG16_NO_KDF = "0x0046"
    ALG_AES_256_GCM_IV12_TAG16_NO_KDF = "0x0078"
    ALG_AES_128_GCM_IV12_TAG16_HKDF_SHA256 = "0x0114"
    ALG_AES_192_GCM_IV12_TAG16_HKDF_SHA256 = "0x0146"
    ALG_AES_256_GCM_IV12_TAG16_HKDF_SHA256 = "0x0178"
    ALG_AES_128_GCM_IV12_TAG16_HKDF_SHA256_ECDSA_P256 = "0x0214"
    ALG_AES_192_GCM_IV12_TAG16_HKDF_SHA384_ECDSA_P384 = "0x0346"
    ALG_AES_256_GCM_IV12_TAG16_HKDF_SHA384_ECDSA_P384 = "0x0378"
    ALG_AES_256_GCM_HKDF_SHA512_COMMIT_KEY = "0x0478"
    ALG_AES_256_GCM_HKDF_SHA512_COMMIT_KEY_ECDSA_P384 = "0x0578"
}

/// Mirrors the MPL's `DBEAlgorithmSuiteId`.
enum DBEAlgorithmSuiteId {
    ALG_AES_256_GCM_HKDF_SHA512_COMMIT_KEY_SYMSIG_HMAC_SHA384 = "0x6700"
    ALG_AES_256_GCM_HKDF_SHA512_COMMIT_KEY_ECDSA_P384_SYMSIG_HMAC_SHA384 = "0x6701"
}

/// Mirrors the MPL's `AlgorithmSuiteId` union: an algorithm suite is named within
/// exactly one format's enumeration, and the two formats may reuse a value.
union AlgorithmSuiteId {
    ESDK: ESDKAlgorithmSuiteId
    DBE: DBEAlgorithmSuiteId
}

// ---------------------------------------------------------------------------
// Materials (Requirement 5)
// ---------------------------------------------------------------------------

/// The encryption context: a key-value mapping of non-secret, UTF-8 strings used as
/// additional authenticated data.
///
/// The MPL types both key and value as `Utf8Bytes`, which its Java codegen maps to
/// `String`, so a plain string map is the faithful wire shape.
map EncryptionContext {
    key: String
    value: String
}

/// Encryption context keys, for the subset required to be supplied on decrypt.
list EncryptionContextKeys {
    member: String
}

/// A list of secrets. Kept as an ordered list because the MPL's
/// `symmetricSigningKeys` is positional with respect to the encrypted data keys.
list SecretList {
    member: Blob
}

/// Mirrors the MPL's `EncryptedDataKey`.
///
/// `keyProviderId` is a `String` rather than a `Blob` because the MPL declares it as
/// `Utf8Bytes`, which its Java codegen maps to `String`; using a Blob here would
/// misrepresent the MPL's own type.
structure EncryptedDataKey {
    @required
    keyProviderId: String

    @required
    keyProviderInfo: Blob

    @required
    ciphertext: Blob
}

list EncryptedDataKeyList {
    member: EncryptedDataKey
}

/// Mirrors the MPL's `EncryptionMaterials`, with one deliberate difference.
///
/// THE DEVIATION (Requirement 8): the MPL's structure carries the full
/// `algorithmSuite: AlgorithmSuiteInfo`, a structure of five nested unions plus four
/// shapes imported from `aws.cryptography.primitives` -- roughly fifteen extra shapes
/// to mirror. This carries `algorithmSuiteId` instead and the server rehydrates the
/// full structure with the MPL's own `GetAlgorithmSuiteInfo`.
///
/// That is lossless, not a hidden abstraction: `AlgorithmSuiteInfo` is a total
/// function of the id -- the MPL provides the lookup, and the table behind it is a
/// fixed compile-time constant. The server therefore operates on exactly the structure
/// the MPL associates with the id. The cost is that a test cannot assert on suite
/// properties directly today; the fix for that is to expose `GetAlgorithmSuiteInfo` as
/// an operation, not to inline the structure here.
///
/// `plaintextDataKey` is an UNWRAPPED data key travelling over unencrypted HTTP. That
/// is accepted for this harness -- the keys are test-only and the server binds
/// loopback -- and is what lets a test carry materials from one server's OnEncrypt to
/// another server's OnDecrypt. See the TestServer README.
structure EncryptionMaterials {
    @required
    algorithmSuiteId: AlgorithmSuiteId

    @required
    encryptionContext: EncryptionContext

    @required
    encryptedDataKeys: EncryptedDataKeyList

    @required
    requiredEncryptionContextKeys: EncryptionContextKeys

    plaintextDataKey: Blob

    signingKey: Blob

    symmetricSigningKeys: SecretList
}

/// Mirrors the MPL's `DecryptionMaterials`, with the same algorithm-suite deviation
/// described on `EncryptionMaterials`.
structure DecryptionMaterials {
    @required
    algorithmSuiteId: AlgorithmSuiteId

    @required
    encryptionContext: EncryptionContext

    @required
    requiredEncryptionContextKeys: EncryptionContextKeys

    plaintextDataKey: Blob

    verificationKey: Blob

    symmetricSigningKey: Blob
}

// ---------------------------------------------------------------------------
// Materials initialization (Requirement 5.2)
// ---------------------------------------------------------------------------

/// Produce well-formed, empty encryption materials for an algorithm suite.
///
/// Exposed so a test never has to hand-build materials. Hand-built materials would
/// encode the harness's idea of what is well-formed rather than the MPL's, and a test
/// that then failed would be ambiguous.
operation InitializeEncryptionMaterials {
    input := {
        @required
        mplId: ResourceId

        @required
        algorithmSuiteId: AlgorithmSuiteId

        @required
        encryptionContext: EncryptionContext

        @required
        requiredEncryptionContextKeys: EncryptionContextKeys

        signingKey: Blob

        verificationKey: Blob
    }

    output := {
        @required
        materials: EncryptionMaterials
    }

    errors: [
        GenericServerError
        MaterialProvidersClientError
    ]
}

/// Produce well-formed, empty decryption materials for an algorithm suite.
operation InitializeDecryptionMaterials {
    input := {
        @required
        mplId: ResourceId

        @required
        algorithmSuiteId: AlgorithmSuiteId

        @required
        encryptionContext: EncryptionContext

        @required
        requiredEncryptionContextKeys: EncryptionContextKeys
    }

    output := {
        @required
        materials: DecryptionMaterials
    }

    errors: [
        GenericServerError
        MaterialProvidersClientError
    ]
}

// ---------------------------------------------------------------------------
// Keyrings (Requirement 6.1)
// ---------------------------------------------------------------------------

/// Mirrors the MPL's `AesWrappingAlg`.
enum AesWrappingAlg {
    ALG_AES128_GCM_IV12_TAG16 = "ALG_AES128_GCM_IV12_TAG16"
    ALG_AES192_GCM_IV12_TAG16 = "ALG_AES192_GCM_IV12_TAG16"
    ALG_AES256_GCM_IV12_TAG16 = "ALG_AES256_GCM_IV12_TAG16"
}

/// Create a Raw AES keyring, which wraps and unwraps data keys locally with AES-GCM.
///
/// Local-only: no AWS call is made, on construction or on use, which is what lets the
/// phase-1 conformance suite be green without credentials.
operation CreateRawAesKeyring {
    input := {
        /// The MaterialProviders instance to construct through.
        @required
        mplId: ResourceId

        @required
        keyNamespace: String

        @required
        keyName: String

        @required
        wrappingKey: Blob

        @required
        wrappingAlg: AesWrappingAlg
    }

    output := {
        /// A handle to the created keyring, standing in for the MPL's
        /// `KeyringReference`, which cannot cross a wire.
        @required
        keyringId: ResourceId
    }

    errors: [
        GenericServerError
        MaterialProvidersClientError
    ]
}

/// Mirrors the MPL's `PaddingScheme` for RSA key wrapping.
enum PaddingScheme {
    PKCS1 = "PKCS1"
    OAEP_SHA1_MGF1 = "OAEP_SHA1_MGF1"
    OAEP_SHA256_MGF1 = "OAEP_SHA256_MGF1"
    OAEP_SHA384_MGF1 = "OAEP_SHA384_MGF1"
    OAEP_SHA512_MGF1 = "OAEP_SHA512_MGF1"
}

/// Create a Raw RSA keyring, which wraps and unwraps data keys locally with RSA.
///
/// Both keys are optional, and which are supplied determines what the keyring can do: the
/// public key is required to encrypt, the private key to decrypt. Supplying neither is
/// rejected by the MPL. The Model keeps both optional rather than splitting into
/// encrypt-only and decrypt-only operations, because that is exactly how the MPL models it
/// -- and because the resulting negative cases are worth testing.
operation CreateRawRsaKeyring {
    input := {
        /// The MaterialProviders instance to construct through.
        @required
        mplId: ResourceId

        @required
        keyNamespace: String

        @required
        keyName: String

        @required
        paddingScheme: PaddingScheme

        /// PEM-encoded X.509 SubjectPublicKeyInfo. Without it the keyring cannot encrypt.
        publicKey: Blob

        /// PEM-encoded PKCS#8 PrivateKeyInfo. Without it the keyring cannot decrypt.
        privateKey: Blob
    }

    output := {
        @required
        keyringId: ResourceId
    }

    errors: [
        GenericServerError
        MaterialProvidersClientError
    ]
}

/// Create a Multi-keyring composed of other keyrings.
///
/// This is where resource handles earn their keep. The MPL's own
/// `CreateMultiKeyringInput` takes an `IKeyring` generator and a list of `IKeyring`
/// children, so the wire takes handles to keyrings the server already holds. Composition
/// on the wire therefore mirrors composition in the MPL exactly, and recursion is free: a
/// child may itself be a multi-keyring, with no recursive Smithy shape and no
/// tagged-union-of-variants workaround.
operation CreateMultiKeyring {
    input := {
        /// The MaterialProviders instance to construct through.
        @required
        mplId: ResourceId

        /// The keyring that may generate the data key, and wraps it first. Optional: with
        /// no generator the multi-keyring cannot generate a data key and can only wrap one
        /// that already exists.
        generatorKeyringId: ResourceId

        /// The other keyrings that wrap the data key. Required but may be empty, exactly as
        /// in the MPL, which represents "no children" as an empty list.
        @required
        childKeyringIds: ResourceIdList
    }

    output := {
        @required
        keyringId: ResourceId
    }

    errors: [
        GenericServerError
        MaterialProvidersClientError
    ]
}

// ---------------------------------------------------------------------------
// Keyring operations (Requirement 2.3)
// ---------------------------------------------------------------------------

/// Invoke a keyring's `OnEncrypt`: given encryption materials, produce materials with a
/// plaintext data key and the encrypted data keys that wrap it.
///
/// This is the MPL's real keyring interface. The MPL has no "encrypt this plaintext"
/// operation to model instead -- keyrings take materials in and hand materials back.
operation OnEncrypt {
    input := {
        /// The keyring to invoke.
        @required
        keyringId: ResourceId

        @required
        materials: EncryptionMaterials
    }

    output := {
        @required
        materials: EncryptionMaterials
    }

    errors: [
        GenericServerError
        MaterialProvidersClientError
    ]
}

/// Invoke a keyring's `OnDecrypt`: given decryption materials and encrypted data keys,
/// produce materials carrying the unwrapped plaintext data key.
///
/// The encrypted data keys are a separate input rather than being read from the
/// materials, exactly as in the MPL. That is also what lets a test take the keys produced
/// by one server's `OnEncrypt` and present them to a different server's `OnDecrypt`.
operation OnDecrypt {
    input := {
        /// The keyring to invoke.
        @required
        keyringId: ResourceId

        @required
        materials: DecryptionMaterials

        @required
        encryptedDataKeys: EncryptedDataKeyList
    }

    output := {
        @required
        materials: DecryptionMaterials
    }

    errors: [
        GenericServerError
        MaterialProvidersClientError
    ]
}
