# Code generated by smithy-python-codegen DO NOT EDIT.

import aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_keystore.dafny_to_smithy
import aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy
import aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models
import aws_cryptography_primitives.smithygenerated.aws_cryptography_primitives.dafny_to_smithy
import com_amazonaws_kms.smithygenerated.com_amazonaws_kms.dafny_to_aws_sdk
import module_
from software_amazon_cryptography_materialproviders_internaldafny_types import (
    AesWrappingAlg_ALG__AES128__GCM__IV12__TAG16,
    AesWrappingAlg_ALG__AES192__GCM__IV12__TAG16,
    AesWrappingAlg_ALG__AES256__GCM__IV12__TAG16,
    AlgorithmSuiteId_DBE,
    AlgorithmSuiteId_ESDK,
    CacheType_Default,
    CacheType_MultiThreaded,
    CacheType_No,
    CacheType_SingleThreaded,
    CacheType_StormTracking,
    CommitmentPolicy_DBE,
    CommitmentPolicy_ESDK,
    DBEAlgorithmSuiteId_ALG__AES__256__GCM__HKDF__SHA512__COMMIT__KEY__ECDSA__P384__SYMSIG__HMAC__SHA384,
    DBEAlgorithmSuiteId_ALG__AES__256__GCM__HKDF__SHA512__COMMIT__KEY__SYMSIG__HMAC__SHA384,
    DBECommitmentPolicy_REQUIRE__ENCRYPT__REQUIRE__DECRYPT,
    DerivationAlgorithm_HKDF,
    DerivationAlgorithm_IDENTITY,
    DerivationAlgorithm_None,
    ESDKAlgorithmSuiteId_ALG__AES__128__GCM__IV12__TAG16__HKDF__SHA256,
    ESDKAlgorithmSuiteId_ALG__AES__128__GCM__IV12__TAG16__HKDF__SHA256__ECDSA__P256,
    ESDKAlgorithmSuiteId_ALG__AES__128__GCM__IV12__TAG16__NO__KDF,
    ESDKAlgorithmSuiteId_ALG__AES__192__GCM__IV12__TAG16__HKDF__SHA256,
    ESDKAlgorithmSuiteId_ALG__AES__192__GCM__IV12__TAG16__HKDF__SHA384__ECDSA__P384,
    ESDKAlgorithmSuiteId_ALG__AES__192__GCM__IV12__TAG16__NO__KDF,
    ESDKAlgorithmSuiteId_ALG__AES__256__GCM__HKDF__SHA512__COMMIT__KEY,
    ESDKAlgorithmSuiteId_ALG__AES__256__GCM__HKDF__SHA512__COMMIT__KEY__ECDSA__P384,
    ESDKAlgorithmSuiteId_ALG__AES__256__GCM__IV12__TAG16__HKDF__SHA256,
    ESDKAlgorithmSuiteId_ALG__AES__256__GCM__IV12__TAG16__HKDF__SHA384__ECDSA__P384,
    ESDKAlgorithmSuiteId_ALG__AES__256__GCM__IV12__TAG16__NO__KDF,
    ESDKCommitmentPolicy_FORBID__ENCRYPT__ALLOW__DECRYPT,
    ESDKCommitmentPolicy_REQUIRE__ENCRYPT__ALLOW__DECRYPT,
    ESDKCommitmentPolicy_REQUIRE__ENCRYPT__REQUIRE__DECRYPT,
    EdkWrappingAlgorithm_DIRECT__KEY__WRAPPING,
    EdkWrappingAlgorithm_IntermediateKeyWrapping,
    Encrypt_AES__GCM,
    Materials_BeaconKey,
    Materials_BranchKey,
    Materials_Decryption,
    Materials_Encryption,
    PaddingScheme_OAEP__SHA1__MGF1,
    PaddingScheme_OAEP__SHA256__MGF1,
    PaddingScheme_OAEP__SHA384__MGF1,
    PaddingScheme_OAEP__SHA512__MGF1,
    PaddingScheme_PKCS1,
    SignatureAlgorithm_ECDSA,
    SignatureAlgorithm_None,
    SymmetricSignatureAlgorithm_HMAC,
    SymmetricSignatureAlgorithm_None,
)


def aws_cryptography_materialproviders_GetBranchKeyIdInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.GetBranchKeyIdInput(
        encryption_context={
            bytes(key): bytes(value) for (key, value) in input.encryptionContext.items
        },
    )


def aws_cryptography_materialproviders_GetBranchKeyIdOutput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.GetBranchKeyIdOutput(
        branch_key_id=input.branchKeyId.VerbatimString(False),
    )


def aws_cryptography_materialproviders_GetClientInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.GetClientInput(
        region=input.region.VerbatimString(False),
    )


def aws_cryptography_materialproviders_KmsClientReference(input):
    return input._impl


def aws_cryptography_materialproviders_GetClientOutput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_KmsClientReference(
        input
    )


def aws_cryptography_materialproviders_Materials(input):
    # Convert Materials
    if isinstance(input, Materials_Encryption):
        Materials_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.MaterialsEncryption(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_EncryptionMaterials(
                input.Encryption
            )
        )
    elif isinstance(input, Materials_Decryption):
        Materials_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.MaterialsDecryption(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_DecryptionMaterials(
                input.Decryption
            )
        )
    elif isinstance(input, Materials_BranchKey):
        Materials_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.MaterialsBranchKey(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_keystore.dafny_to_smithy.aws_cryptography_keystore_BranchKeyMaterials(
                input.BranchKey
            )
        )
    elif isinstance(input, Materials_BeaconKey):
        Materials_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.MaterialsBeaconKey(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_keystore.dafny_to_smithy.aws_cryptography_keystore_BeaconKeyMaterials(
                input.BeaconKey
            )
        )
    else:
        raise ValueError("No recognized union value in union type: " + str(input))

    return Materials_union_value


def aws_cryptography_materialproviders_EncryptionMaterials(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.EncryptionMaterials(
        algorithm_suite=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_AlgorithmSuiteInfo(
            input.algorithmSuite
        ),
        encryption_context={
            bytes(key): bytes(value) for (key, value) in input.encryptionContext.items
        },
        encrypted_data_keys=[
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_EncryptedDataKey(
                list_element
            )
            for list_element in input.encryptedDataKeys
        ],
        required_encryption_context_keys=[
            bytes(list_element) for list_element in input.requiredEncryptionContextKeys
        ],
        plaintext_data_key=(
            (bytes(input.plaintextDataKey.value))
            if (input.plaintextDataKey.is_Some)
            else None
        ),
        signing_key=(
            (bytes(input.signingKey.value)) if (input.signingKey.is_Some) else None
        ),
        symmetric_signing_keys=(
            ([bytes(list_element) for list_element in input.symmetricSigningKeys.value])
            if (input.symmetricSigningKeys.is_Some)
            else None
        ),
    )


def aws_cryptography_materialproviders_DecryptionMaterials(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.DecryptionMaterials(
        algorithm_suite=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_AlgorithmSuiteInfo(
            input.algorithmSuite
        ),
        encryption_context={
            bytes(key): bytes(value) for (key, value) in input.encryptionContext.items
        },
        required_encryption_context_keys=[
            bytes(list_element) for list_element in input.requiredEncryptionContextKeys
        ],
        plaintext_data_key=(
            (bytes(input.plaintextDataKey.value))
            if (input.plaintextDataKey.is_Some)
            else None
        ),
        verification_key=(
            (bytes(input.verificationKey.value))
            if (input.verificationKey.is_Some)
            else None
        ),
        symmetric_signing_key=(
            (bytes(input.symmetricSigningKey.value))
            if (input.symmetricSigningKey.is_Some)
            else None
        ),
    )


def aws_cryptography_materialproviders_AlgorithmSuiteInfo(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.AlgorithmSuiteInfo(
        id=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_AlgorithmSuiteId(
            input.id
        ),
        binary_id=bytes(input.binaryId),
        message_version=input.messageVersion,
        encrypt=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_Encrypt(
            input.encrypt
        ),
        kdf=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_DerivationAlgorithm(
            input.kdf
        ),
        commitment=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_DerivationAlgorithm(
            input.commitment
        ),
        signature=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_SignatureAlgorithm(
            input.signature
        ),
        symmetric_signature=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_SymmetricSignatureAlgorithm(
            input.symmetricSignature
        ),
        edk_wrapping=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_EdkWrappingAlgorithm(
            input.edkWrapping
        ),
    )


def aws_cryptography_materialproviders_EncryptedDataKey(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.EncryptedDataKey(
        key_provider_id=bytes(input.keyProviderId),
        key_provider_info=bytes(input.keyProviderInfo),
        ciphertext=bytes(input.ciphertext),
    )


def aws_cryptography_materialproviders_AlgorithmSuiteId(input):
    # Convert AlgorithmSuiteId
    if isinstance(input, AlgorithmSuiteId_ESDK):
        AlgorithmSuiteId_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.AlgorithmSuiteIdESDK(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_ESDKAlgorithmSuiteId(
                input.ESDK
            )
        )
    elif isinstance(input, AlgorithmSuiteId_DBE):
        AlgorithmSuiteId_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.AlgorithmSuiteIdDBE(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_DBEAlgorithmSuiteId(
                input.DBE
            )
        )
    else:
        raise ValueError("No recognized union value in union type: " + str(input))

    return AlgorithmSuiteId_union_value


def aws_cryptography_materialproviders_Encrypt(input):
    # Convert Encrypt
    if isinstance(input, Encrypt_AES__GCM):
        Encrypt_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.EncryptAES_GCM(
            aws_cryptography_primitives.smithygenerated.aws_cryptography_primitives.dafny_to_smithy.aws_cryptography_primitives_AES_GCM(
                input.AES__GCM
            )
        )
    else:
        raise ValueError("No recognized union value in union type: " + str(input))

    return Encrypt_union_value


def aws_cryptography_materialproviders_DerivationAlgorithm(input):
    # Convert DerivationAlgorithm
    if isinstance(input, DerivationAlgorithm_HKDF):
        DerivationAlgorithm_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.DerivationAlgorithmHKDF(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_HKDF(
                input.HKDF
            )
        )
    elif isinstance(input, DerivationAlgorithm_IDENTITY):
        DerivationAlgorithm_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.DerivationAlgorithmIDENTITY(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_IDENTITY(
                input.IDENTITY
            )
        )
    elif isinstance(input, DerivationAlgorithm_None):
        DerivationAlgorithm_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.DerivationAlgorithmNone(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_None(
                input.None_
            )
        )
    else:
        raise ValueError("No recognized union value in union type: " + str(input))

    return DerivationAlgorithm_union_value


def aws_cryptography_materialproviders_SignatureAlgorithm(input):
    # Convert SignatureAlgorithm
    if isinstance(input, SignatureAlgorithm_ECDSA):
        SignatureAlgorithm_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.SignatureAlgorithmECDSA(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_ECDSA(
                input.ECDSA
            )
        )
    elif isinstance(input, SignatureAlgorithm_None):
        SignatureAlgorithm_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.SignatureAlgorithmNone(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_None(
                input.None_
            )
        )
    else:
        raise ValueError("No recognized union value in union type: " + str(input))

    return SignatureAlgorithm_union_value


def aws_cryptography_materialproviders_SymmetricSignatureAlgorithm(input):
    # Convert SymmetricSignatureAlgorithm
    if isinstance(input, SymmetricSignatureAlgorithm_HMAC):
        SymmetricSignatureAlgorithm_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.SymmetricSignatureAlgorithmHMAC(
            aws_cryptography_primitives.smithygenerated.aws_cryptography_primitives.dafny_to_smithy.aws_cryptography_primitives_DigestAlgorithm(
                input.HMAC
            )
        )
    elif isinstance(input, SymmetricSignatureAlgorithm_None):
        SymmetricSignatureAlgorithm_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.SymmetricSignatureAlgorithmNone(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_None(
                input.None_
            )
        )
    else:
        raise ValueError("No recognized union value in union type: " + str(input))

    return SymmetricSignatureAlgorithm_union_value


def aws_cryptography_materialproviders_EdkWrappingAlgorithm(input):
    # Convert EdkWrappingAlgorithm
    if isinstance(input, EdkWrappingAlgorithm_DIRECT__KEY__WRAPPING):
        EdkWrappingAlgorithm_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.EdkWrappingAlgorithmDIRECT_KEY_WRAPPING(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_DIRECT_KEY_WRAPPING(
                input.DIRECT__KEY__WRAPPING
            )
        )
    elif isinstance(input, EdkWrappingAlgorithm_IntermediateKeyWrapping):
        EdkWrappingAlgorithm_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.EdkWrappingAlgorithmIntermediateKeyWrapping(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_IntermediateKeyWrapping(
                input.IntermediateKeyWrapping
            )
        )
    else:
        raise ValueError("No recognized union value in union type: " + str(input))

    return EdkWrappingAlgorithm_union_value


def aws_cryptography_materialproviders_ESDKAlgorithmSuiteId(input):
    if isinstance(input, ESDKAlgorithmSuiteId_ALG__AES__128__GCM__IV12__TAG16__NO__KDF):
        return "0x0014"

    elif isinstance(
        input, ESDKAlgorithmSuiteId_ALG__AES__192__GCM__IV12__TAG16__NO__KDF
    ):
        return "0x0046"

    elif isinstance(
        input, ESDKAlgorithmSuiteId_ALG__AES__256__GCM__IV12__TAG16__NO__KDF
    ):
        return "0x0078"

    elif isinstance(
        input, ESDKAlgorithmSuiteId_ALG__AES__128__GCM__IV12__TAG16__HKDF__SHA256
    ):
        return "0x0114"

    elif isinstance(
        input, ESDKAlgorithmSuiteId_ALG__AES__192__GCM__IV12__TAG16__HKDF__SHA256
    ):
        return "0x0146"

    elif isinstance(
        input, ESDKAlgorithmSuiteId_ALG__AES__256__GCM__IV12__TAG16__HKDF__SHA256
    ):
        return "0x0178"

    elif isinstance(
        input,
        ESDKAlgorithmSuiteId_ALG__AES__128__GCM__IV12__TAG16__HKDF__SHA256__ECDSA__P256,
    ):
        return "0x0214"

    elif isinstance(
        input,
        ESDKAlgorithmSuiteId_ALG__AES__192__GCM__IV12__TAG16__HKDF__SHA384__ECDSA__P384,
    ):
        return "0x0346"

    elif isinstance(
        input,
        ESDKAlgorithmSuiteId_ALG__AES__256__GCM__IV12__TAG16__HKDF__SHA384__ECDSA__P384,
    ):
        return "0x0378"

    elif isinstance(
        input, ESDKAlgorithmSuiteId_ALG__AES__256__GCM__HKDF__SHA512__COMMIT__KEY
    ):
        return "0x0478"

    elif isinstance(
        input,
        ESDKAlgorithmSuiteId_ALG__AES__256__GCM__HKDF__SHA512__COMMIT__KEY__ECDSA__P384,
    ):
        return "0x0578"

    else:
        raise ValueError(f"No recognized enum value in enum type: {input=}")


def aws_cryptography_materialproviders_DBEAlgorithmSuiteId(input):
    if isinstance(
        input,
        DBEAlgorithmSuiteId_ALG__AES__256__GCM__HKDF__SHA512__COMMIT__KEY__SYMSIG__HMAC__SHA384,
    ):
        return "0x6700"

    elif isinstance(
        input,
        DBEAlgorithmSuiteId_ALG__AES__256__GCM__HKDF__SHA512__COMMIT__KEY__ECDSA__P384__SYMSIG__HMAC__SHA384,
    ):
        return "0x6701"

    else:
        raise ValueError(f"No recognized enum value in enum type: {input=}")


def aws_cryptography_materialproviders_HKDF(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.HKDF(
        hmac=aws_cryptography_primitives.smithygenerated.aws_cryptography_primitives.dafny_to_smithy.aws_cryptography_primitives_DigestAlgorithm(
            input.hmac
        ),
        salt_length=input.saltLength,
        input_key_length=input.inputKeyLength,
        output_key_length=input.outputKeyLength,
    )


def aws_cryptography_materialproviders_IDENTITY(input):
    return (
        aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.IDENTITY()
    )


def aws_cryptography_materialproviders_None(input):
    return (
        aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.None_()
    )


def aws_cryptography_materialproviders_ECDSA(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.ECDSA(
        curve=aws_cryptography_primitives.smithygenerated.aws_cryptography_primitives.dafny_to_smithy.aws_cryptography_primitives_ECDSASignatureAlgorithm(
            input.curve
        ),
    )


def aws_cryptography_materialproviders_DIRECT_KEY_WRAPPING(input):
    return (
        aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.DIRECT_KEY_WRAPPING()
    )


def aws_cryptography_materialproviders_IntermediateKeyWrapping(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.IntermediateKeyWrapping(
        key_encryption_key_kdf=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_DerivationAlgorithm(
            input.keyEncryptionKeyKdf
        ),
        mac_key_kdf=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_DerivationAlgorithm(
            input.macKeyKdf
        ),
        pdk_encrypt_algorithm=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_Encrypt(
            input.pdkEncryptAlgorithm
        ),
    )


def aws_cryptography_materialproviders_PutCacheEntryInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.PutCacheEntryInput(
        identifier=bytes(input.identifier),
        materials=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_Materials(
            input.materials
        ),
        creation_time=input.creationTime,
        expiry_time=input.expiryTime,
        messages_used=(
            (input.messagesUsed.value) if (input.messagesUsed.is_Some) else None
        ),
        bytes_used=(input.bytesUsed.value) if (input.bytesUsed.is_Some) else None,
    )


def smithy_api_Unit():
    return (
        aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.Unit()
    )


def aws_cryptography_materialproviders_GetCacheEntryInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.GetCacheEntryInput(
        identifier=bytes(input.identifier),
        bytes_used=(input.bytesUsed.value) if (input.bytesUsed.is_Some) else None,
    )


def aws_cryptography_materialproviders_GetCacheEntryOutput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.GetCacheEntryOutput(
        materials=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_Materials(
            input.materials
        ),
        creation_time=input.creationTime,
        expiry_time=input.expiryTime,
        messages_used=input.messagesUsed,
        bytes_used=input.bytesUsed,
    )


def aws_cryptography_materialproviders_UpdateUsageMetadataInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.UpdateUsageMetadataInput(
        identifier=bytes(input.identifier),
        bytes_used=input.bytesUsed,
    )


def aws_cryptography_materialproviders_DeleteCacheEntryInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.DeleteCacheEntryInput(
        identifier=bytes(input.identifier),
    )


def aws_cryptography_materialproviders_CommitmentPolicy(input):
    # Convert CommitmentPolicy
    if isinstance(input, CommitmentPolicy_ESDK):
        CommitmentPolicy_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CommitmentPolicyESDK(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_ESDKCommitmentPolicy(
                input.ESDK
            )
        )
    elif isinstance(input, CommitmentPolicy_DBE):
        CommitmentPolicy_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CommitmentPolicyDBE(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_DBECommitmentPolicy(
                input.DBE
            )
        )
    else:
        raise ValueError("No recognized union value in union type: " + str(input))

    return CommitmentPolicy_union_value


def aws_cryptography_materialproviders_ESDKCommitmentPolicy(input):
    if isinstance(input, ESDKCommitmentPolicy_FORBID__ENCRYPT__ALLOW__DECRYPT):
        return "FORBID_ENCRYPT_ALLOW_DECRYPT"

    elif isinstance(input, ESDKCommitmentPolicy_REQUIRE__ENCRYPT__ALLOW__DECRYPT):
        return "REQUIRE_ENCRYPT_ALLOW_DECRYPT"

    elif isinstance(input, ESDKCommitmentPolicy_REQUIRE__ENCRYPT__REQUIRE__DECRYPT):
        return "REQUIRE_ENCRYPT_REQUIRE_DECRYPT"

    else:
        raise ValueError(f"No recognized enum value in enum type: {input=}")


def aws_cryptography_materialproviders_DBECommitmentPolicy(input):
    if isinstance(input, DBECommitmentPolicy_REQUIRE__ENCRYPT__REQUIRE__DECRYPT):
        return "REQUIRE_ENCRYPT_REQUIRE_DECRYPT"

    else:
        raise ValueError(f"No recognized enum value in enum type: {input=}")


def aws_cryptography_materialproviders_GetEncryptionMaterialsInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.GetEncryptionMaterialsInput(
        encryption_context={
            bytes(key): bytes(value) for (key, value) in input.encryptionContext.items
        },
        commitment_policy=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_CommitmentPolicy(
            input.commitmentPolicy
        ),
        algorithm_suite_id=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_AlgorithmSuiteId(
                    input.algorithmSuiteId.value
                )
            )
            if (input.algorithmSuiteId.is_Some)
            else None
        ),
        max_plaintext_length=(
            (input.maxPlaintextLength.value)
            if (input.maxPlaintextLength.is_Some)
            else None
        ),
        required_encryption_context_keys=(
            (
                [
                    bytes(list_element)
                    for list_element in input.requiredEncryptionContextKeys.value
                ]
            )
            if (input.requiredEncryptionContextKeys.is_Some)
            else None
        ),
    )


def aws_cryptography_materialproviders_GetEncryptionMaterialsOutput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.GetEncryptionMaterialsOutput(
        encryption_materials=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_EncryptionMaterials(
            input.encryptionMaterials
        ),
    )


def aws_cryptography_materialproviders_DecryptMaterialsInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.DecryptMaterialsInput(
        algorithm_suite_id=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_AlgorithmSuiteId(
            input.algorithmSuiteId
        ),
        commitment_policy=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_CommitmentPolicy(
            input.commitmentPolicy
        ),
        encrypted_data_keys=[
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_EncryptedDataKey(
                list_element
            )
            for list_element in input.encryptedDataKeys
        ],
        encryption_context={
            bytes(key): bytes(value) for (key, value) in input.encryptionContext.items
        },
        reproduced_encryption_context=(
            (
                {
                    bytes(key): bytes(value)
                    for (key, value) in input.reproducedEncryptionContext.value.items
                }
            )
            if (input.reproducedEncryptionContext.is_Some)
            else None
        ),
    )


def aws_cryptography_materialproviders_DecryptMaterialsOutput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.DecryptMaterialsOutput(
        decryption_materials=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_DecryptionMaterials(
            input.decryptionMaterials
        ),
    )


def aws_cryptography_materialproviders_OnEncryptInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.OnEncryptInput(
        materials=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_EncryptionMaterials(
            input.materials
        ),
    )


def aws_cryptography_materialproviders_OnEncryptOutput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.OnEncryptOutput(
        materials=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_EncryptionMaterials(
            input.materials
        ),
    )


def aws_cryptography_materialproviders_OnDecryptInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.OnDecryptInput(
        materials=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_DecryptionMaterials(
            input.materials
        ),
        encrypted_data_keys=[
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_EncryptedDataKey(
                list_element
            )
            for list_element in input.encryptedDataKeys
        ],
    )


def aws_cryptography_materialproviders_OnDecryptOutput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.OnDecryptOutput(
        materials=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_DecryptionMaterials(
            input.materials
        ),
    )


def aws_cryptography_materialproviders_CreateAwsKmsKeyringInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CreateAwsKmsKeyringInput(
        kms_key_id=input.kmsKeyId.VerbatimString(False),
        kms_client=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_KmsClientReference(
                    input.kmsClient
                )
            )
            if (input.kmsClient is not None)
            else None
        ),
        grant_tokens=(
            (
                [
                    list_element.VerbatimString(False)
                    for list_element in input.grantTokens.value
                ]
            )
            if (input.grantTokens.is_Some)
            else None
        ),
    )


def aws_cryptography_materialproviders_DiscoveryFilter(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.DiscoveryFilter(
        account_ids=[
            list_element.VerbatimString(False) for list_element in input.accountIds
        ],
        partition=input.partition.VerbatimString(False),
    )


def aws_cryptography_materialproviders_CreateAwsKmsDiscoveryKeyringInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CreateAwsKmsDiscoveryKeyringInput(
        kms_client=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_KmsClientReference(
                    input.kmsClient
                )
            )
            if (input.kmsClient is not None)
            else None
        ),
        discovery_filter=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_DiscoveryFilter(
                    input.discoveryFilter.value
                )
            )
            if (input.discoveryFilter.is_Some)
            else None
        ),
        grant_tokens=(
            (
                [
                    list_element.VerbatimString(False)
                    for list_element in input.grantTokens.value
                ]
            )
            if (input.grantTokens.is_Some)
            else None
        ),
    )


def aws_cryptography_materialproviders_ClientSupplierReference(input):
    if hasattr(input, "_native_impl"):
        return input._native_impl

    else:
        from aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.references import (
            ClientSupplier,
        )

        return ClientSupplier(_impl=input)


def aws_cryptography_materialproviders_CreateAwsKmsMultiKeyringInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CreateAwsKmsMultiKeyringInput(
        generator=(
            (input.generator.value.VerbatimString(False))
            if (input.generator.is_Some)
            else None
        ),
        kms_key_ids=(
            (
                [
                    list_element.VerbatimString(False)
                    for list_element in input.kmsKeyIds.value
                ]
            )
            if (input.kmsKeyIds.is_Some)
            else None
        ),
        client_supplier=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_ClientSupplierReference(
                    input.clientSupplier.UnwrapOr(None)
                )
            )
            if (input.clientSupplier.UnwrapOr(None) is not None)
            else None
        ),
        grant_tokens=(
            (
                [
                    list_element.VerbatimString(False)
                    for list_element in input.grantTokens.value
                ]
            )
            if (input.grantTokens.is_Some)
            else None
        ),
    )


def aws_cryptography_materialproviders_CreateAwsKmsDiscoveryMultiKeyringInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CreateAwsKmsDiscoveryMultiKeyringInput(
        regions=[list_element.VerbatimString(False) for list_element in input.regions],
        discovery_filter=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_DiscoveryFilter(
                    input.discoveryFilter.value
                )
            )
            if (input.discoveryFilter.is_Some)
            else None
        ),
        client_supplier=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_ClientSupplierReference(
                    input.clientSupplier.UnwrapOr(None)
                )
            )
            if (input.clientSupplier.UnwrapOr(None) is not None)
            else None
        ),
        grant_tokens=(
            (
                [
                    list_element.VerbatimString(False)
                    for list_element in input.grantTokens.value
                ]
            )
            if (input.grantTokens.is_Some)
            else None
        ),
    )


def aws_cryptography_materialproviders_CreateAwsKmsMrkKeyringInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CreateAwsKmsMrkKeyringInput(
        kms_key_id=input.kmsKeyId.VerbatimString(False),
        kms_client=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_KmsClientReference(
                    input.kmsClient
                )
            )
            if (input.kmsClient is not None)
            else None
        ),
        grant_tokens=(
            (
                [
                    list_element.VerbatimString(False)
                    for list_element in input.grantTokens.value
                ]
            )
            if (input.grantTokens.is_Some)
            else None
        ),
    )


def aws_cryptography_materialproviders_CreateAwsKmsMrkMultiKeyringInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CreateAwsKmsMrkMultiKeyringInput(
        generator=(
            (input.generator.value.VerbatimString(False))
            if (input.generator.is_Some)
            else None
        ),
        kms_key_ids=(
            (
                [
                    list_element.VerbatimString(False)
                    for list_element in input.kmsKeyIds.value
                ]
            )
            if (input.kmsKeyIds.is_Some)
            else None
        ),
        client_supplier=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_ClientSupplierReference(
                    input.clientSupplier.UnwrapOr(None)
                )
            )
            if (input.clientSupplier.UnwrapOr(None) is not None)
            else None
        ),
        grant_tokens=(
            (
                [
                    list_element.VerbatimString(False)
                    for list_element in input.grantTokens.value
                ]
            )
            if (input.grantTokens.is_Some)
            else None
        ),
    )


def aws_cryptography_materialproviders_CreateAwsKmsMrkDiscoveryKeyringInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CreateAwsKmsMrkDiscoveryKeyringInput(
        kms_client=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_KmsClientReference(
                    input.kmsClient
                )
            )
            if (input.kmsClient is not None)
            else None
        ),
        discovery_filter=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_DiscoveryFilter(
                    input.discoveryFilter.value
                )
            )
            if (input.discoveryFilter.is_Some)
            else None
        ),
        grant_tokens=(
            (
                [
                    list_element.VerbatimString(False)
                    for list_element in input.grantTokens.value
                ]
            )
            if (input.grantTokens.is_Some)
            else None
        ),
        region=input.region.VerbatimString(False),
    )


def aws_cryptography_materialproviders_CreateAwsKmsMrkDiscoveryMultiKeyringInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CreateAwsKmsMrkDiscoveryMultiKeyringInput(
        regions=[list_element.VerbatimString(False) for list_element in input.regions],
        discovery_filter=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_DiscoveryFilter(
                    input.discoveryFilter.value
                )
            )
            if (input.discoveryFilter.is_Some)
            else None
        ),
        client_supplier=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_ClientSupplierReference(
                    input.clientSupplier.UnwrapOr(None)
                )
            )
            if (input.clientSupplier.UnwrapOr(None) is not None)
            else None
        ),
        grant_tokens=(
            (
                [
                    list_element.VerbatimString(False)
                    for list_element in input.grantTokens.value
                ]
            )
            if (input.grantTokens.is_Some)
            else None
        ),
    )


def aws_cryptography_materialproviders_BranchKeyIdSupplierReference(input):
    if hasattr(input, "_native_impl"):
        return input._native_impl

    else:
        from aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.references import (
            BranchKeyIdSupplier,
        )

        return BranchKeyIdSupplier(_impl=input)


def aws_cryptography_materialproviders_KeyStoreReference(input):
    from aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_keystore.client import (
        KeyStore,
    )

    return KeyStore(config=None, dafny_client=input)


def aws_cryptography_materialproviders_CacheType(input):
    # Convert CacheType
    if isinstance(input, CacheType_Default):
        CacheType_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CacheTypeDefault(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_DefaultCache(
                input.Default
            )
        )
    elif isinstance(input, CacheType_No):
        CacheType_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CacheTypeNo(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_NoCache(
                input.No
            )
        )
    elif isinstance(input, CacheType_SingleThreaded):
        CacheType_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CacheTypeSingleThreaded(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_SingleThreadedCache(
                input.SingleThreaded
            )
        )
    elif isinstance(input, CacheType_MultiThreaded):
        CacheType_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CacheTypeMultiThreaded(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_MultiThreadedCache(
                input.MultiThreaded
            )
        )
    elif isinstance(input, CacheType_StormTracking):
        CacheType_union_value = aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CacheTypeStormTracking(
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_StormTrackingCache(
                input.StormTracking
            )
        )
    else:
        raise ValueError("No recognized union value in union type: " + str(input))

    return CacheType_union_value


def aws_cryptography_materialproviders_DefaultCache(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.DefaultCache(
        entry_capacity=input.entryCapacity,
    )


def aws_cryptography_materialproviders_NoCache(input):
    return (
        aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.NoCache()
    )


def aws_cryptography_materialproviders_SingleThreadedCache(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.SingleThreadedCache(
        entry_capacity=input.entryCapacity,
        entry_pruning_tail_size=(
            (input.entryPruningTailSize.value)
            if (input.entryPruningTailSize.is_Some)
            else None
        ),
    )


def aws_cryptography_materialproviders_MultiThreadedCache(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.MultiThreadedCache(
        entry_capacity=input.entryCapacity,
        entry_pruning_tail_size=(
            (input.entryPruningTailSize.value)
            if (input.entryPruningTailSize.is_Some)
            else None
        ),
    )


def aws_cryptography_materialproviders_StormTrackingCache(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.StormTrackingCache(
        entry_capacity=input.entryCapacity,
        entry_pruning_tail_size=(
            (input.entryPruningTailSize.value)
            if (input.entryPruningTailSize.is_Some)
            else None
        ),
        grace_period=input.gracePeriod,
        grace_interval=input.graceInterval,
        fan_out=input.fanOut,
        in_flight_ttl=input.inFlightTTL,
        sleep_milli=input.sleepMilli,
    )


def aws_cryptography_materialproviders_CreateAwsKmsHierarchicalKeyringInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CreateAwsKmsHierarchicalKeyringInput(
        branch_key_id=(
            (input.branchKeyId.value.VerbatimString(False))
            if (input.branchKeyId.is_Some)
            else None
        ),
        branch_key_id_supplier=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_BranchKeyIdSupplierReference(
                    input.branchKeyIdSupplier.UnwrapOr(None)
                )
            )
            if (input.branchKeyIdSupplier.UnwrapOr(None) is not None)
            else None
        ),
        key_store=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_KeyStoreReference(
                    input.keyStore
                )
            )
            if (input.keyStore is not None)
            else None
        ),
        ttl_seconds=input.ttlSeconds,
        cache=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_CacheType(
                    input.cache.value
                )
            )
            if (input.cache.is_Some)
            else None
        ),
    )


def aws_cryptography_materialproviders_KeyringReference(input):
    if hasattr(input, "_native_impl"):
        return input._native_impl

    else:
        from aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.references import (
            Keyring,
        )

        return Keyring(_impl=input)


def aws_cryptography_materialproviders_CreateMultiKeyringInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CreateMultiKeyringInput(
        generator=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_KeyringReference(
                    input.generator.UnwrapOr(None)
                )
            )
            if (input.generator.UnwrapOr(None) is not None)
            else None
        ),
        child_keyrings=[
            aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_KeyringReference(
                list_element
            )
            for list_element in input.childKeyrings
        ],
    )


def aws_cryptography_materialproviders_AesWrappingAlg(input):
    if isinstance(input, AesWrappingAlg_ALG__AES128__GCM__IV12__TAG16):
        return "ALG_AES128_GCM_IV12_TAG16"

    elif isinstance(input, AesWrappingAlg_ALG__AES192__GCM__IV12__TAG16):
        return "ALG_AES192_GCM_IV12_TAG16"

    elif isinstance(input, AesWrappingAlg_ALG__AES256__GCM__IV12__TAG16):
        return "ALG_AES256_GCM_IV12_TAG16"

    else:
        raise ValueError(f"No recognized enum value in enum type: {input=}")


def aws_cryptography_materialproviders_CreateRawAesKeyringInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CreateRawAesKeyringInput(
        key_namespace=input.keyNamespace.VerbatimString(False),
        key_name=input.keyName.VerbatimString(False),
        wrapping_key=bytes(input.wrappingKey),
        wrapping_alg=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_AesWrappingAlg(
            input.wrappingAlg
        ),
    )


def aws_cryptography_materialproviders_PaddingScheme(input):
    if isinstance(input, PaddingScheme_PKCS1):
        return "PKCS1"

    elif isinstance(input, PaddingScheme_OAEP__SHA1__MGF1):
        return "OAEP_SHA1_MGF1"

    elif isinstance(input, PaddingScheme_OAEP__SHA256__MGF1):
        return "OAEP_SHA256_MGF1"

    elif isinstance(input, PaddingScheme_OAEP__SHA384__MGF1):
        return "OAEP_SHA384_MGF1"

    elif isinstance(input, PaddingScheme_OAEP__SHA512__MGF1):
        return "OAEP_SHA512_MGF1"

    else:
        raise ValueError(f"No recognized enum value in enum type: {input=}")


def aws_cryptography_materialproviders_CreateRawRsaKeyringInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CreateRawRsaKeyringInput(
        key_namespace=input.keyNamespace.VerbatimString(False),
        key_name=input.keyName.VerbatimString(False),
        padding_scheme=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_PaddingScheme(
            input.paddingScheme
        ),
        public_key=(
            (bytes(input.publicKey.value)) if (input.publicKey.is_Some) else None
        ),
        private_key=(
            (bytes(input.privateKey.value)) if (input.privateKey.is_Some) else None
        ),
    )


def aws_cryptography_materialproviders_CreateAwsKmsRsaKeyringInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CreateAwsKmsRsaKeyringInput(
        public_key=(
            (bytes(input.publicKey.value)) if (input.publicKey.is_Some) else None
        ),
        kms_key_id=input.kmsKeyId.VerbatimString(False),
        encryption_algorithm=com_amazonaws_kms.smithygenerated.com_amazonaws_kms.dafny_to_aws_sdk.com_amazonaws_kms_EncryptionAlgorithmSpec(
            input.encryptionAlgorithm
        ),
        kms_client=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_KmsClientReference(
                    input.kmsClient.UnwrapOr(None)
                )
            )
            if (input.kmsClient.UnwrapOr(None) is not None)
            else None
        ),
        grant_tokens=(
            (
                [
                    list_element.VerbatimString(False)
                    for list_element in input.grantTokens.value
                ]
            )
            if (input.grantTokens.is_Some)
            else None
        ),
    )


def aws_cryptography_materialproviders_CreateDefaultCryptographicMaterialsManagerInput(
    input,
):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CreateDefaultCryptographicMaterialsManagerInput(
        keyring=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_KeyringReference(
                    input.keyring
                )
            )
            if (input.keyring is not None)
            else None
        ),
    )


def aws_cryptography_materialproviders_CryptographicMaterialsManagerReference(input):
    if hasattr(input, "_native_impl"):
        return input._native_impl

    else:
        from aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.references import (
            CryptographicMaterialsManager,
        )

        return CryptographicMaterialsManager(_impl=input)


def aws_cryptography_materialproviders_CreateRequiredEncryptionContextCMMInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CreateRequiredEncryptionContextCMMInput(
        underlying_cmm=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_CryptographicMaterialsManagerReference(
                    input.underlyingCMM.UnwrapOr(None)
                )
            )
            if (input.underlyingCMM.UnwrapOr(None) is not None)
            else None
        ),
        keyring=(
            (
                aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_KeyringReference(
                    input.keyring.UnwrapOr(None)
                )
            )
            if (input.keyring.UnwrapOr(None) is not None)
            else None
        ),
        required_encryption_context_keys=[
            bytes(list_element) for list_element in input.requiredEncryptionContextKeys
        ],
    )


def aws_cryptography_materialproviders_CreateCryptographicMaterialsCacheInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CreateCryptographicMaterialsCacheInput(
        cache=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_CacheType(
            input.cache
        ),
    )


def aws_cryptography_materialproviders_CreateDefaultClientSupplierInput(input):
    return (
        aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.CreateDefaultClientSupplierInput()
    )


def aws_cryptography_materialproviders_InitializeEncryptionMaterialsInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.InitializeEncryptionMaterialsInput(
        algorithm_suite_id=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_AlgorithmSuiteId(
            input.algorithmSuiteId
        ),
        encryption_context={
            bytes(key): bytes(value) for (key, value) in input.encryptionContext.items
        },
        required_encryption_context_keys=[
            bytes(list_element) for list_element in input.requiredEncryptionContextKeys
        ],
        signing_key=(
            (bytes(input.signingKey.value)) if (input.signingKey.is_Some) else None
        ),
        verification_key=(
            (bytes(input.verificationKey.value))
            if (input.verificationKey.is_Some)
            else None
        ),
    )


def aws_cryptography_materialproviders_InitializeDecryptionMaterialsInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.InitializeDecryptionMaterialsInput(
        algorithm_suite_id=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_AlgorithmSuiteId(
            input.algorithmSuiteId
        ),
        encryption_context={
            bytes(key): bytes(value) for (key, value) in input.encryptionContext.items
        },
        required_encryption_context_keys=[
            bytes(list_element) for list_element in input.requiredEncryptionContextKeys
        ],
    )


def aws_cryptography_materialproviders_ValidEncryptionMaterialsTransitionInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.ValidEncryptionMaterialsTransitionInput(
        start=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_EncryptionMaterials(
            input.start
        ),
        stop=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_EncryptionMaterials(
            input.stop
        ),
    )


def aws_cryptography_materialproviders_ValidDecryptionMaterialsTransitionInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.ValidDecryptionMaterialsTransitionInput(
        start=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_DecryptionMaterials(
            input.start
        ),
        stop=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_DecryptionMaterials(
            input.stop
        ),
    )


def aws_cryptography_materialproviders_GetAlgorithmSuiteInfoInput(input):
    return bytes(input)


def aws_cryptography_materialproviders_ValidateCommitmentPolicyOnEncryptInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.ValidateCommitmentPolicyOnEncryptInput(
        algorithm=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_AlgorithmSuiteId(
            input.algorithm
        ),
        commitment_policy=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_CommitmentPolicy(
            input.commitmentPolicy
        ),
    )


def aws_cryptography_materialproviders_ValidateCommitmentPolicyOnDecryptInput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.models.ValidateCommitmentPolicyOnDecryptInput(
        algorithm=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_AlgorithmSuiteId(
            input.algorithm
        ),
        commitment_policy=aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_CommitmentPolicy(
            input.commitmentPolicy
        ),
    )


def aws_cryptography_materialproviders_CreateKeyringOutput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_KeyringReference(
        input
    )


def aws_cryptography_materialproviders_CreateCryptographicMaterialsManagerOutput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_CryptographicMaterialsManagerReference(
        input
    )


def aws_cryptography_materialproviders_CreateRequiredEncryptionContextCMMOutput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_CryptographicMaterialsManagerReference(
        input
    )


def aws_cryptography_materialproviders_CryptographicMaterialsCacheReference(input):
    if hasattr(input, "_native_impl"):
        return input._native_impl

    else:
        from aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.references import (
            CryptographicMaterialsCache,
        )

        return CryptographicMaterialsCache(_impl=input)


def aws_cryptography_materialproviders_CreateCryptographicMaterialsCacheOutput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_CryptographicMaterialsCacheReference(
        input
    )


def aws_cryptography_materialproviders_CreateDefaultClientSupplierOutput(input):
    return aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.dafny_to_smithy.aws_cryptography_materialproviders_ClientSupplierReference(
        input
    )


def aws_cryptography_materialproviders_MaterialProvidersConfig(input):
    # Deferred import of .config to avoid circular dependency
    import aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.config

    return (
        aws_cryptographic_materialproviders.smithygenerated.aws_cryptography_materialproviders.config.MaterialProvidersConfig()
    )
