version: 0.2

env:
  variables:
    BRANCH: "main"
  secrets-manager:
    TWINE_USERNAME: PyPiAPIToken:username
    TWINE_PASSWORD: PyPiAPIToken:password

phases:
  install:
    commands:
      - pip install "tox < 4.0"
      - pip install --upgrade pip
    runtime-versions:
      python: latest
  pre_build:
    commands:
      # Get Dafny
      - cd ..
      - curl https://github.com/dafny-lang/dafny/releases/download/v$dafnyVersion/dafny-$dafnyVersion-x64-ubuntu-20.04.zip  -L -o dafny.zip
      - unzip -qq dafny.zip && rm dafny.zip
      - export PATH="$PWD/dafny:$PATH"
      # Switch back to the main directory
      - cd aws-cryptographic-material-providers-library
      - git checkout $COMMIT_ID
      - FOUND_VERSION=$(sed -n 's/version = "\(.*\)"/\1/p' AwsCryptographyPrimitives/runtimes/python/pyproject.toml)
      - |
        if expr ${FOUND_VERSION} != ${VERSION}; then
          echo "pyproject.toml version (${FOUND_VERSION}) does not match expected version (${VERSION}), stopping"
          exit 1;
        fi
      - cd AwsCryptographyPrimitives
      # Build Dafny source
      - make transpile_python
  build:
    commands:
      - echo "Skipping prod release until we are ready to release the MPL"

batch:
  fast-fail: true
  build-graph:
    - identifier: release_to_prod
    - identifier: validate_prod_release
      depend-on:
        - release_to_prod
      buildspec: codebuild/release-python/validate.yml
      env:
        variables:
          PIP_INDEX_URL: https://pypi.python.org/simple/
