#
# This local action sets up code dependencies
# to run Smithy-Dafny CI in GitHub Actions workflows.
#

name: "Install Smithy-Dafny codegen dependencies"
description: "Install Java package dependencies required to run Smithy-Dafny codegen"
inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.11"
runs:
  using: "composite"
  steps:
    - name: Setup Java 17 for codegen
      uses: actions/setup-java@v5
      with:
        distribution: "corretto"
        java-version: "17"

    - name: Install smithy-dafny-codegen dependencies locally
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 60
        retry_wait_seconds: 30
        max_attempts: 3
        shell: bash
        command: make -C smithy-dafny mvn_local_deploy_polymorph_dependencies

    - name: Setup Python, black, and docformatter for code formatting
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version || matrix.python-version }}
        architecture: x64
    - shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install black==25.1
        python -m pip install --upgrade docformatter
        python -m pip install --upgrade tox

    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: "1.23"

    - name: Install Go imports
      shell: bash
      run: |
        go install golang.org/x/tools/cmd/goimports@v0.36.0

    # Without this the if-dafny-at-least command includes "Downloading ..." output
    - name: Arbitrary makefile target to force downloading Gradle
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 60
        retry_wait_seconds: 30
        max_attempts: 3
        shell: bash
        command: make -C StandardLibrary setup_net
