#
# This local action sets up code dependencies
# to run Smithy-Dafny CI in GitHub Actions workflows.
#

name: "Install Smithy-Dafny codegen dependencies"
description: "Install Java package dependencies required to run Smithy-Dafny codegen"
runs:
  using: "composite"
  steps:
    - name: Install smithy-dafny-codegen Rust dependencies locally
      uses: gradle/gradle-build-action@v2
      with:
        arguments: :codegen-client:pTML :codegen-core:pTML :rust-runtime:pTML
        build-root-directory: smithy-dafny/smithy-dafny-codegen-modules/smithy-rs

    - name: Install smithy-dafny-codegen Python dependencies locally
      uses: gradle/gradle-build-action@v2
      with:
        arguments: :smithy-python-codegen:pTML
        build-root-directory: smithy-dafny/codegen/smithy-dafny-codegen-modules/smithy-python/codegen

    - name: Setup Python, black, and docformatter for code formatting
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade black
        python -m pip install --upgrade docformatter

    - name: Setup Java 17 for codegen
      uses: actions/setup-java@v3
      with:
        distribution: "corretto"
        java-version: "17"
    
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install Go imports
      shell: bash
      run: |
        go install golang.org/x/tools/cmd/goimports@latest

      

    
