#
# This local action sets up code dependencies
# to run Smithy-Dafny CI in GitHub Actions workflows.
#

name: "Install Smithy-Dafny codegen dependencies"
description: "Install Java package dependencies required to run Smithy-Dafny codegen"
runs:
  steps:
    - name: Install Smithy-Dafny codegen dependencies
      uses: Wandalen/wretry.action@1
        with:
          attempt_limit: 3
          attempt_delay: 30
          action: ./.github/actions/codegen_dependencies
