// Code generated by smithy-go-codegen DO NOT EDIT.

package awscryptographykeystoresmithygenerated

import (
	"github.com/aws/aws-cryptographic-material-providers-library/releases/go/mpl/AwsCryptographyKeyStoreTypes"
	"github.com/aws/aws-cryptographic-material-providers-library/releases/go/mpl/awscryptographykeystoresmithygeneratedtypes"
	"github.com/aws/aws-cryptographic-material-providers-library/releases/go/smithy-dafny-standard-library/Wrappers"
)

type KeyStorageInterfaceNativeWrapper struct {
	AwsCryptographyKeyStoreTypes.IKeyStorageInterface
	Impl awscryptographykeystoresmithygeneratedtypes.IKeyStorageInterface
}

func (this *KeyStorageInterfaceNativeWrapper) WriteNewEncryptedBranchKey(input AwsCryptographyKeyStoreTypes.WriteNewEncryptedBranchKeyInput) Wrappers.Result {
	var native_request = WriteNewEncryptedBranchKeyInput_FromDafny(input)
	var native_response, native_error = this.Impl.WriteNewEncryptedBranchKey(native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(WriteNewEncryptedBranchKeyOutput_ToDafny(*native_response))
}

func (this *KeyStorageInterfaceNativeWrapper) WriteNewEncryptedBranchKeyVersion(input AwsCryptographyKeyStoreTypes.WriteNewEncryptedBranchKeyVersionInput) Wrappers.Result {
	var native_request = WriteNewEncryptedBranchKeyVersionInput_FromDafny(input)
	var native_response, native_error = this.Impl.WriteNewEncryptedBranchKeyVersion(native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(WriteNewEncryptedBranchKeyVersionOutput_ToDafny(*native_response))
}

func (this *KeyStorageInterfaceNativeWrapper) GetEncryptedActiveBranchKey(input AwsCryptographyKeyStoreTypes.GetEncryptedActiveBranchKeyInput) Wrappers.Result {
	var native_request = GetEncryptedActiveBranchKeyInput_FromDafny(input)
	var native_response, native_error = this.Impl.GetEncryptedActiveBranchKey(native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(GetEncryptedActiveBranchKeyOutput_ToDafny(*native_response))
}

func (this *KeyStorageInterfaceNativeWrapper) GetEncryptedBranchKeyVersion(input AwsCryptographyKeyStoreTypes.GetEncryptedBranchKeyVersionInput) Wrappers.Result {
	var native_request = GetEncryptedBranchKeyVersionInput_FromDafny(input)
	var native_response, native_error = this.Impl.GetEncryptedBranchKeyVersion(native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(GetEncryptedBranchKeyVersionOutput_ToDafny(*native_response))
}

func (this *KeyStorageInterfaceNativeWrapper) GetEncryptedBeaconKey(input AwsCryptographyKeyStoreTypes.GetEncryptedBeaconKeyInput) Wrappers.Result {
	var native_request = GetEncryptedBeaconKeyInput_FromDafny(input)
	var native_response, native_error = this.Impl.GetEncryptedBeaconKey(native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(GetEncryptedBeaconKeyOutput_ToDafny(*native_response))
}

func (this *KeyStorageInterfaceNativeWrapper) GetKeyStorageInfo(input AwsCryptographyKeyStoreTypes.GetKeyStorageInfoInput) Wrappers.Result {
	var native_request = GetKeyStorageInfoInput_FromDafny(input)
	var native_response, native_error = this.Impl.GetKeyStorageInfo(native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(GetKeyStorageInfoOutput_ToDafny(*native_response))
}

func (this *KeyStorageInterfaceNativeWrapper) GetItemsForInitializeMutation(input AwsCryptographyKeyStoreTypes.GetItemsForInitializeMutationInput) Wrappers.Result {
	var native_request = GetItemsForInitializeMutationInput_FromDafny(input)
	var native_response, native_error = this.Impl.GetItemsForInitializeMutation(native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(GetItemsForInitializeMutationOutput_ToDafny(*native_response))
}

func (this *KeyStorageInterfaceNativeWrapper) WriteInitializeMutation(input AwsCryptographyKeyStoreTypes.WriteInitializeMutationInput) Wrappers.Result {
	var native_request = WriteInitializeMutationInput_FromDafny(input)
	var native_response, native_error = this.Impl.WriteInitializeMutation(native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(WriteInitializeMutationOutput_ToDafny(*native_response))
}

func (this *KeyStorageInterfaceNativeWrapper) WriteAtomicMutation(input AwsCryptographyKeyStoreTypes.WriteAtomicMutationInput) Wrappers.Result {
	var native_request = WriteAtomicMutationInput_FromDafny(input)
	var native_response, native_error = this.Impl.WriteAtomicMutation(native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(WriteAtomicMutationOutput_ToDafny(*native_response))
}

func (this *KeyStorageInterfaceNativeWrapper) QueryForVersions(input AwsCryptographyKeyStoreTypes.QueryForVersionsInput) Wrappers.Result {
	var native_request = QueryForVersionsInput_FromDafny(input)
	var native_response, native_error = this.Impl.QueryForVersions(native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(QueryForVersionsOutput_ToDafny(*native_response))
}

func (this *KeyStorageInterfaceNativeWrapper) WriteMutatedVersions(input AwsCryptographyKeyStoreTypes.WriteMutatedVersionsInput) Wrappers.Result {
	var native_request = WriteMutatedVersionsInput_FromDafny(input)
	var native_response, native_error = this.Impl.WriteMutatedVersions(native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(WriteMutatedVersionsOutput_ToDafny(*native_response))
}

func (this *KeyStorageInterfaceNativeWrapper) GetMutation(input AwsCryptographyKeyStoreTypes.GetMutationInput) Wrappers.Result {
	var native_request = GetMutationInput_FromDafny(input)
	var native_response, native_error = this.Impl.GetMutation(native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(GetMutationOutput_ToDafny(*native_response))
}

func (this *KeyStorageInterfaceNativeWrapper) DeleteMutation(input AwsCryptographyKeyStoreTypes.DeleteMutationInput) Wrappers.Result {
	var native_request = DeleteMutationInput_FromDafny(input)
	var native_response, native_error = this.Impl.DeleteMutation(native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(DeleteMutationOutput_ToDafny(*native_response))
}

func (this *KeyStorageInterfaceNativeWrapper) WriteMutationIndex(input AwsCryptographyKeyStoreTypes.WriteMutationIndexInput) Wrappers.Result {
	var native_request = WriteMutationIndexInput_FromDafny(input)
	var native_response, native_error = this.Impl.WriteMutationIndex(native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(WriteMutationIndexOutput_ToDafny(*native_response))
}
