// Class __default
// Dafny class __default compiled into Java
package CmmFromKeyDescription_Compile;

@SuppressWarnings({"unchecked", "deprecation"})
public class __default {
  public __default() {
  }
  public static Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> ToCmm(software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient mpl, dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends KeyMaterial_Compile.KeyMaterial> keys, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription description, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.CmmOperation forOperation)
  {
    Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> output = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)null;
    if(true) {
      Wrappers_Compile.Option<KeyMaterial_Compile.KeyMaterial> _0_material;
      _0_material = KeyringFromKeyDescription_Compile.__default.GetKeyMaterial(keys, description);
      software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription _source0 = description;
      if (_source0.is_Kms()) {
        software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KMSInfo _1___mcc_h0 = ((software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription_Kms)_source0)._Kms;
        {
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _2_valueOrError1 = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)null;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _out0;
          _out0 = KeyringFromKeyDescription_Compile.__default.ToKeyring(mpl, keys, description);
          _2_valueOrError1 = _out0;
          if ((_2_valueOrError1).IsFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
            output = (_2_valueOrError1).<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>PropagateFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)));
            return output;
          }
          software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring _3_keyring;
          _3_keyring = (_2_valueOrError1).Extract(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _4_output_k;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _out1;
          _out1 = (mpl).CreateDefaultCryptographicMaterialsManager(software.amazon.cryptography.materialproviders.internaldafny.types.CreateDefaultCryptographicMaterialsManagerInput.create(_3_keyring));
          _4_output_k = _out1;
          output = (_4_output_k).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>MapFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)), software.amazon.cryptography.materialproviders.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.materialproviders.internaldafny.types.Error, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)(_5_e_boxed0) -> {
            software.amazon.cryptography.materialproviders.internaldafny.types.Error _5_e = ((software.amazon.cryptography.materialproviders.internaldafny.types.Error)(java.lang.Object)(_5_e_boxed0));
            return software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(_5_e);
          }));
        }
      } else if (_source0.is_KmsMrk()) {
        software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KmsMrkAware _6___mcc_h2 = ((software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription_KmsMrk)_source0)._KmsMrk;
        {
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _7_valueOrError1 = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)null;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _out2;
          _out2 = KeyringFromKeyDescription_Compile.__default.ToKeyring(mpl, keys, description);
          _7_valueOrError1 = _out2;
          if ((_7_valueOrError1).IsFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
            output = (_7_valueOrError1).<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>PropagateFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)));
            return output;
          }
          software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring _8_keyring;
          _8_keyring = (_7_valueOrError1).Extract(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _9_output_k;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _out3;
          _out3 = (mpl).CreateDefaultCryptographicMaterialsManager(software.amazon.cryptography.materialproviders.internaldafny.types.CreateDefaultCryptographicMaterialsManagerInput.create(_8_keyring));
          _9_output_k = _out3;
          output = (_9_output_k).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>MapFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)), software.amazon.cryptography.materialproviders.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.materialproviders.internaldafny.types.Error, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)(_10_e_boxed0) -> {
            software.amazon.cryptography.materialproviders.internaldafny.types.Error _10_e = ((software.amazon.cryptography.materialproviders.internaldafny.types.Error)(java.lang.Object)(_10_e_boxed0));
            return software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(_10_e);
          }));
        }
      } else if (_source0.is_KmsMrkDiscovery()) {
        software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KmsMrkAwareDiscovery _11___mcc_h4 = ((software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription_KmsMrkDiscovery)_source0)._KmsMrkDiscovery;
        {
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _12_valueOrError1 = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)null;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _out4;
          _out4 = KeyringFromKeyDescription_Compile.__default.ToKeyring(mpl, keys, description);
          _12_valueOrError1 = _out4;
          if ((_12_valueOrError1).IsFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
            output = (_12_valueOrError1).<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>PropagateFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)));
            return output;
          }
          software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring _13_keyring;
          _13_keyring = (_12_valueOrError1).Extract(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _14_output_k;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _out5;
          _out5 = (mpl).CreateDefaultCryptographicMaterialsManager(software.amazon.cryptography.materialproviders.internaldafny.types.CreateDefaultCryptographicMaterialsManagerInput.create(_13_keyring));
          _14_output_k = _out5;
          output = (_14_output_k).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>MapFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)), software.amazon.cryptography.materialproviders.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.materialproviders.internaldafny.types.Error, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)(_15_e_boxed0) -> {
            software.amazon.cryptography.materialproviders.internaldafny.types.Error _15_e = ((software.amazon.cryptography.materialproviders.internaldafny.types.Error)(java.lang.Object)(_15_e_boxed0));
            return software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(_15_e);
          }));
        }
      } else if (_source0.is_RSA()) {
        software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.RawRSA _16___mcc_h6 = ((software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription_RSA)_source0)._RSA;
        {
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _17_valueOrError1 = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)null;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _out6;
          _out6 = KeyringFromKeyDescription_Compile.__default.ToKeyring(mpl, keys, description);
          _17_valueOrError1 = _out6;
          if ((_17_valueOrError1).IsFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
            output = (_17_valueOrError1).<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>PropagateFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)));
            return output;
          }
          software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring _18_keyring;
          _18_keyring = (_17_valueOrError1).Extract(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _19_output_k;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _out7;
          _out7 = (mpl).CreateDefaultCryptographicMaterialsManager(software.amazon.cryptography.materialproviders.internaldafny.types.CreateDefaultCryptographicMaterialsManagerInput.create(_18_keyring));
          _19_output_k = _out7;
          output = (_19_output_k).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>MapFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)), software.amazon.cryptography.materialproviders.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.materialproviders.internaldafny.types.Error, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)(_20_e_boxed0) -> {
            software.amazon.cryptography.materialproviders.internaldafny.types.Error _20_e = ((software.amazon.cryptography.materialproviders.internaldafny.types.Error)(java.lang.Object)(_20_e_boxed0));
            return software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(_20_e);
          }));
        }
      } else if (_source0.is_AES()) {
        software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.RawAES _21___mcc_h8 = ((software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription_AES)_source0)._AES;
        {
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _22_valueOrError1 = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)null;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _out8;
          _out8 = KeyringFromKeyDescription_Compile.__default.ToKeyring(mpl, keys, description);
          _22_valueOrError1 = _out8;
          if ((_22_valueOrError1).IsFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
            output = (_22_valueOrError1).<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>PropagateFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)));
            return output;
          }
          software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring _23_keyring;
          _23_keyring = (_22_valueOrError1).Extract(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _24_output_k;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _out9;
          _out9 = (mpl).CreateDefaultCryptographicMaterialsManager(software.amazon.cryptography.materialproviders.internaldafny.types.CreateDefaultCryptographicMaterialsManagerInput.create(_23_keyring));
          _24_output_k = _out9;
          output = (_24_output_k).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>MapFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)), software.amazon.cryptography.materialproviders.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.materialproviders.internaldafny.types.Error, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)(_25_e_boxed0) -> {
            software.amazon.cryptography.materialproviders.internaldafny.types.Error _25_e = ((software.amazon.cryptography.materialproviders.internaldafny.types.Error)(java.lang.Object)(_25_e_boxed0));
            return software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(_25_e);
          }));
        }
      } else if (_source0.is_ECDH()) {
        software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.RawEcdh _26___mcc_h10 = ((software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription_ECDH)_source0)._ECDH;
        {
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _27_valueOrError1 = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)null;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _out10;
          _out10 = KeyringFromKeyDescription_Compile.__default.ToKeyring(mpl, keys, description);
          _27_valueOrError1 = _out10;
          if ((_27_valueOrError1).IsFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
            output = (_27_valueOrError1).<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>PropagateFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)));
            return output;
          }
          software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring _28_keyring;
          _28_keyring = (_27_valueOrError1).Extract(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _29_output_k;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _out11;
          _out11 = (mpl).CreateDefaultCryptographicMaterialsManager(software.amazon.cryptography.materialproviders.internaldafny.types.CreateDefaultCryptographicMaterialsManagerInput.create(_28_keyring));
          _29_output_k = _out11;
          output = (_29_output_k).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>MapFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)), software.amazon.cryptography.materialproviders.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.materialproviders.internaldafny.types.Error, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)(_30_e_boxed0) -> {
            software.amazon.cryptography.materialproviders.internaldafny.types.Error _30_e = ((software.amazon.cryptography.materialproviders.internaldafny.types.Error)(java.lang.Object)(_30_e_boxed0));
            return software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(_30_e);
          }));
        }
      } else if (_source0.is_Static()) {
        software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.StaticKeyring _31___mcc_h12 = ((software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription_Static)_source0)._Static;
        {
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _32_valueOrError1 = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)null;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _out12;
          _out12 = KeyringFromKeyDescription_Compile.__default.ToKeyring(mpl, keys, description);
          _32_valueOrError1 = _out12;
          if ((_32_valueOrError1).IsFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
            output = (_32_valueOrError1).<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>PropagateFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)));
            return output;
          }
          software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring _33_keyring;
          _33_keyring = (_32_valueOrError1).Extract(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _34_output_k;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _out13;
          _out13 = (mpl).CreateDefaultCryptographicMaterialsManager(software.amazon.cryptography.materialproviders.internaldafny.types.CreateDefaultCryptographicMaterialsManagerInput.create(_33_keyring));
          _34_output_k = _out13;
          output = (_34_output_k).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>MapFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)), software.amazon.cryptography.materialproviders.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.materialproviders.internaldafny.types.Error, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)(_35_e_boxed0) -> {
            software.amazon.cryptography.materialproviders.internaldafny.types.Error _35_e = ((software.amazon.cryptography.materialproviders.internaldafny.types.Error)(java.lang.Object)(_35_e_boxed0));
            return software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(_35_e);
          }));
        }
      } else if (_source0.is_KmsRsa()) {
        software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KmsRsaKeyring _36___mcc_h14 = ((software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription_KmsRsa)_source0)._KmsRsa;
        {
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _37_valueOrError1 = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)null;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _out14;
          _out14 = KeyringFromKeyDescription_Compile.__default.ToKeyring(mpl, keys, description);
          _37_valueOrError1 = _out14;
          if ((_37_valueOrError1).IsFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
            output = (_37_valueOrError1).<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>PropagateFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)));
            return output;
          }
          software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring _38_keyring;
          _38_keyring = (_37_valueOrError1).Extract(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _39_output_k;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _out15;
          _out15 = (mpl).CreateDefaultCryptographicMaterialsManager(software.amazon.cryptography.materialproviders.internaldafny.types.CreateDefaultCryptographicMaterialsManagerInput.create(_38_keyring));
          _39_output_k = _out15;
          output = (_39_output_k).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>MapFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)), software.amazon.cryptography.materialproviders.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.materialproviders.internaldafny.types.Error, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)(_40_e_boxed0) -> {
            software.amazon.cryptography.materialproviders.internaldafny.types.Error _40_e = ((software.amazon.cryptography.materialproviders.internaldafny.types.Error)(java.lang.Object)(_40_e_boxed0));
            return software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(_40_e);
          }));
        }
      } else if (_source0.is_KmsECDH()) {
        software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KmsEcdhKeyring _41___mcc_h16 = ((software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription_KmsECDH)_source0)._KmsECDH;
        {
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _42_valueOrError1 = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)null;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _out16;
          _out16 = KeyringFromKeyDescription_Compile.__default.ToKeyring(mpl, keys, description);
          _42_valueOrError1 = _out16;
          if ((_42_valueOrError1).IsFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
            output = (_42_valueOrError1).<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>PropagateFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)));
            return output;
          }
          software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring _43_keyring;
          _43_keyring = (_42_valueOrError1).Extract(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _44_output_k;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _out17;
          _out17 = (mpl).CreateDefaultCryptographicMaterialsManager(software.amazon.cryptography.materialproviders.internaldafny.types.CreateDefaultCryptographicMaterialsManagerInput.create(_43_keyring));
          _44_output_k = _out17;
          output = (_44_output_k).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>MapFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)), software.amazon.cryptography.materialproviders.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.materialproviders.internaldafny.types.Error, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)(_45_e_boxed0) -> {
            software.amazon.cryptography.materialproviders.internaldafny.types.Error _45_e = ((software.amazon.cryptography.materialproviders.internaldafny.types.Error)(java.lang.Object)(_45_e_boxed0));
            return software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(_45_e);
          }));
        }
      } else if (_source0.is_Hierarchy()) {
        software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.HierarchyKeyring _46___mcc_h18 = ((software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription_Hierarchy)_source0)._Hierarchy;
        {
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _47_valueOrError1 = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)null;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _out18;
          _out18 = KeyringFromKeyDescription_Compile.__default.ToKeyring(mpl, keys, description);
          _47_valueOrError1 = _out18;
          if ((_47_valueOrError1).IsFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
            output = (_47_valueOrError1).<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>PropagateFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)));
            return output;
          }
          software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring _48_keyring;
          _48_keyring = (_47_valueOrError1).Extract(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _49_output_k;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _out19;
          _out19 = (mpl).CreateDefaultCryptographicMaterialsManager(software.amazon.cryptography.materialproviders.internaldafny.types.CreateDefaultCryptographicMaterialsManagerInput.create(_48_keyring));
          _49_output_k = _out19;
          output = (_49_output_k).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>MapFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)), software.amazon.cryptography.materialproviders.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.materialproviders.internaldafny.types.Error, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)(_50_e_boxed0) -> {
            software.amazon.cryptography.materialproviders.internaldafny.types.Error _50_e = ((software.amazon.cryptography.materialproviders.internaldafny.types.Error)(java.lang.Object)(_50_e_boxed0));
            return software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(_50_e);
          }));
        }
      } else if (_source0.is_Multi()) {
        software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.MultiKeyring _51___mcc_h20 = ((software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription_Multi)_source0)._Multi;
        {
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _52_valueOrError1 = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)null;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _out20;
          _out20 = KeyringFromKeyDescription_Compile.__default.ToKeyring(mpl, keys, description);
          _52_valueOrError1 = _out20;
          if ((_52_valueOrError1).IsFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
            output = (_52_valueOrError1).<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>PropagateFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)));
            return output;
          }
          software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring _53_keyring;
          _53_keyring = (_52_valueOrError1).Extract(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _54_output_k;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _out21;
          _out21 = (mpl).CreateDefaultCryptographicMaterialsManager(software.amazon.cryptography.materialproviders.internaldafny.types.CreateDefaultCryptographicMaterialsManagerInput.create(_53_keyring));
          _54_output_k = _out21;
          output = (_54_output_k).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>MapFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)), software.amazon.cryptography.materialproviders.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.materialproviders.internaldafny.types.Error, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)(_55_e_boxed0) -> {
            software.amazon.cryptography.materialproviders.internaldafny.types.Error _55_e = ((software.amazon.cryptography.materialproviders.internaldafny.types.Error)(java.lang.Object)(_55_e_boxed0));
            return software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(_55_e);
          }));
        }
      } else {
        software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.RequiredEncryptionContextCMM _56___mcc_h22 = ((software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription_RequiredEncryptionContext)_source0)._RequiredEncryptionContext;
        software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.RequiredEncryptionContextCMM _57_cmm = _56___mcc_h22;
        {
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _58_valueOrError0 = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)null;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _out22;
          _out22 = __default.ToCmm(mpl, keys, (_57_cmm).dtor_underlying(), forOperation);
          _58_valueOrError0 = _out22;
          if ((_58_valueOrError0).IsFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
            output = (_58_valueOrError0).<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>PropagateFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)));
            return output;
          }
          software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager _59_underlying;
          _59_underlying = (_58_valueOrError0).Extract(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _60_output_k;
          Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _out23;
          _out23 = (mpl).CreateRequiredEncryptionContextCMM(software.amazon.cryptography.materialproviders.internaldafny.types.CreateRequiredEncryptionContextCMMInput.create(Wrappers_Compile.Option.<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>create_Some(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)), _59_underlying), Wrappers_Compile.Option.<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>create_None(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class))), (_57_cmm).dtor_requiredEncryptionContextKeys()));
          _60_output_k = _out23;
          output = (_60_output_k).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>MapFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)), software.amazon.cryptography.materialproviders.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.materialproviders.internaldafny.types.Error, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)(_61_e_boxed0) -> {
            software.amazon.cryptography.materialproviders.internaldafny.types.Error _61_e = ((software.amazon.cryptography.materialproviders.internaldafny.types.Error)(java.lang.Object)(_61_e_boxed0));
            return software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(_61_e);
          }));
        }
      }
    }
    return output;
  }
  @Override
  public java.lang.String toString() {
    return "CmmFromKeyDescription._default";
  }
}
