// Class __default
// Dafny class __default compiled into Java
package JSON_mZeroCopy_mDeserializer_mObjects_Compile;

import Wrappers_Compile.*;
import Seq_mMergeSort_Compile.*;
import Math_Compile.*;
import Seq_Compile.*;
import BoundedInts_Compile.*;
import Unicode_Compile.*;
import Utf8EncodingForm_Compile.*;
import Utf16EncodingForm_Compile.*;
import UnicodeStrings_Compile.*;
import FileIO_Compile.*;
import MulInternals_Compile.*;
import ModInternals_Compile.*;
import DivInternals_Compile.*;
import Power_Compile.*;
import Logarithm_Compile.*;
import StandardLibraryInterop_Compile.*;
import StandardLibrary_mUInt_Compile.*;
import StandardLibrary_mSequence_Compile.*;
import StandardLibrary_mString_Compile.*;
import StandardLibrary_Compile.*;
import UUID.*;
import UTF8.*;
import OsLang.*;
import Time.*;
import Streams_Compile.*;
import Sorting_Compile.*;
import HexStrings_Compile.*;
import GetOpt_Compile.*;
import FloatCompare_Compile.*;
import ConcurrentCall.*;
import Base64_Compile.*;
import Actions_Compile.*;
import DafnyLibraries.*;
import JSON_mUtils_mViews_mCore_Compile.*;
import JSON_mUtils_mViews_mWriters_Compile.*;
import JSON_mUtils_mLexers_mCore_Compile.*;
import JSON_mUtils_mLexers_mStrings_Compile.*;
import JSON_mUtils_mCursors_Compile.*;
import JSON_mUtils_mParsers_Compile.*;
import JSON_mUtils_mStr_mCharStrConversion_Compile.*;
import JSON_mUtils_mStr_mCharStrEscaping_Compile.*;
import JSON_mUtils_mStr_Compile.*;
import JSON_mUtils_mVectors_Compile.*;
import JSON_mErrors_Compile.*;
import JSON_mValues_Compile.*;
import JSON_mSpec_Compile.*;
import JSON_mGrammar_Compile.*;
import JSON_mSerializer_mByteStrConversion_Compile.*;
import JSON_mSerializer_Compile.*;
import JSON_mDeserializer_mUint16StrConversion_Compile.*;
import JSON_mDeserializer_mByteStrConversion_Compile.*;
import JSON_mDeserializer_Compile.*;
import JSON_mConcreteSyntax_mSpec_Compile.*;
import JSON_mZeroCopy_mSerializer_Compile.*;
import JSON_mZeroCopy_mDeserializer_mCore_Compile.*;
import JSON_mZeroCopy_mDeserializer_mStrings_Compile.*;
import JSON_mZeroCopy_mDeserializer_mNumbers_Compile.*;
import JSON_mZeroCopy_mDeserializer_mObjectParams_Compile.*;

@SuppressWarnings({"unchecked", "deprecation"})
public class __default {
  public __default() {
  }
  public static Wrappers_Compile.Result<JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>, JSON_mUtils_mCursors_Compile.CursorError<JSON_mErrors_Compile.DeserializationError>> Object(JSON_mUtils_mCursors_Compile.Cursor__ cs, JSON_mUtils_mParsers_Compile.SubParser__<JSON_mGrammar_Compile.Value, JSON_mErrors_Compile.DeserializationError> json)
  {
    Wrappers_Compile.Result<JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>, JSON_mUtils_mCursors_Compile.CursorError<JSON_mErrors_Compile.DeserializationError>> _0_valueOrError0 = __default.Bracketed(cs, json);
    if ((_0_valueOrError0).IsFailure(JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Bracketed.<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(jopen._typeDescriptor(), JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor(), jclose._typeDescriptor())), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()))) {
      return (_0_valueOrError0).<JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>>PropagateFailure(JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Bracketed.<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(jopen._typeDescriptor(), JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor(), jclose._typeDescriptor())), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()), JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Bracketed.<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(jopen._typeDescriptor(), JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor(), jclose._typeDescriptor())));
    } else {
      JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>> _1_sp = (_0_valueOrError0).Extract(JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Bracketed.<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(jopen._typeDescriptor(), JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor(), jclose._typeDescriptor())), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()));
      return Wrappers_Compile.Result.<JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>, JSON_mUtils_mCursors_Compile.CursorError<JSON_mErrors_Compile.DeserializationError>>create_Success(JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Bracketed.<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(jopen._typeDescriptor(), JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor(), jclose._typeDescriptor())), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()), _1_sp);
    }
  }
  public static Wrappers_Compile.Result<JSON_mUtils_mCursors_Compile.Split<JSON_mUtils_mViews_mCore_Compile.View__>, JSON_mUtils_mCursors_Compile.CursorError<JSON_mErrors_Compile.DeserializationError>> Open(JSON_mUtils_mCursors_Compile.Cursor__ cs) {
    Wrappers_Compile.Result<JSON_mUtils_mCursors_Compile.Cursor__, JSON_mUtils_mCursors_Compile.CursorError<JSON_mErrors_Compile.DeserializationError>> _0_valueOrError0 = (cs).<JSON_mErrors_Compile.DeserializationError>AssertByte(JSON_mErrors_Compile.DeserializationError._typeDescriptor(), JSON_mZeroCopy_mDeserializer_mObjectParams_Compile.__default.OPEN());
    if ((_0_valueOrError0).IsFailure(JSON_mUtils_mCursors_Compile.Cursor._typeDescriptor(), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()))) {
      return (_0_valueOrError0).<JSON_mUtils_mCursors_Compile.Split<JSON_mUtils_mViews_mCore_Compile.View__>>PropagateFailure(JSON_mUtils_mCursors_Compile.Cursor._typeDescriptor(), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()), JSON_mUtils_mCursors_Compile.Split.<JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(JSON_mUtils_mViews_mCore_Compile.View._typeDescriptor()));
    } else {
      JSON_mUtils_mCursors_Compile.Cursor__ _1_cs = (_0_valueOrError0).Extract(JSON_mUtils_mCursors_Compile.Cursor._typeDescriptor(), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()));
      return Wrappers_Compile.Result.<JSON_mUtils_mCursors_Compile.Split<JSON_mUtils_mViews_mCore_Compile.View__>, JSON_mUtils_mCursors_Compile.CursorError<JSON_mErrors_Compile.DeserializationError>>create_Success(JSON_mUtils_mCursors_Compile.Split.<JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(JSON_mUtils_mViews_mCore_Compile.View._typeDescriptor()), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()), (_1_cs).Split());
    }
  }
  public static Wrappers_Compile.Result<JSON_mUtils_mCursors_Compile.Split<JSON_mUtils_mViews_mCore_Compile.View__>, JSON_mUtils_mCursors_Compile.CursorError<JSON_mErrors_Compile.DeserializationError>> Close(JSON_mUtils_mCursors_Compile.Cursor__ cs) {
    Wrappers_Compile.Result<JSON_mUtils_mCursors_Compile.Cursor__, JSON_mUtils_mCursors_Compile.CursorError<JSON_mErrors_Compile.DeserializationError>> _0_valueOrError0 = (cs).<JSON_mErrors_Compile.DeserializationError>AssertByte(JSON_mErrors_Compile.DeserializationError._typeDescriptor(), JSON_mZeroCopy_mDeserializer_mObjectParams_Compile.__default.CLOSE());
    if ((_0_valueOrError0).IsFailure(JSON_mUtils_mCursors_Compile.Cursor._typeDescriptor(), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()))) {
      return (_0_valueOrError0).<JSON_mUtils_mCursors_Compile.Split<JSON_mUtils_mViews_mCore_Compile.View__>>PropagateFailure(JSON_mUtils_mCursors_Compile.Cursor._typeDescriptor(), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()), JSON_mUtils_mCursors_Compile.Split.<JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(JSON_mUtils_mViews_mCore_Compile.View._typeDescriptor()));
    } else {
      JSON_mUtils_mCursors_Compile.Cursor__ _1_cs = (_0_valueOrError0).Extract(JSON_mUtils_mCursors_Compile.Cursor._typeDescriptor(), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()));
      return Wrappers_Compile.Result.<JSON_mUtils_mCursors_Compile.Split<JSON_mUtils_mViews_mCore_Compile.View__>, JSON_mUtils_mCursors_Compile.CursorError<JSON_mErrors_Compile.DeserializationError>>create_Success(JSON_mUtils_mCursors_Compile.Split.<JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(JSON_mUtils_mViews_mCore_Compile.View._typeDescriptor()), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()), (_1_cs).Split());
    }
  }
  public static JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>> BracketedFromParts(JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>> open, JSON_mUtils_mCursors_Compile.Split<dafny.DafnySequence<? extends JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>>> elems, JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>> close)
  {
    JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>> _0_sp = JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>create(JSON_mGrammar_Compile.Bracketed.<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(jopen._typeDescriptor(), JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor(), jclose._typeDescriptor()), JSON_mGrammar_Compile.Bracketed.<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>create(jopen._typeDescriptor(), JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor(), jclose._typeDescriptor(), (open).dtor_t(), (elems).dtor_t(), (close).dtor_t()), (close).dtor_cs());
    return _0_sp;
  }
  public static JSON_mUtils_mCursors_Compile.Split<dafny.DafnySequence<? extends JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>>> AppendWithSuffix(JSON_mUtils_mCursors_Compile.Split<dafny.DafnySequence<? extends JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>>> elems, JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.jKeyValue> elem, JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>> sep)
  {
    JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__> _0_suffixed = JSON_mGrammar_Compile.Suffixed.<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>create(JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor(), (elem).dtor_t(), JSON_mGrammar_Compile.Maybe.<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>>create_NonEmpty(JSON_mGrammar_Compile.Structural.<JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(JSON_mGrammar_Compile.jcomma._typeDescriptor()), (sep).dtor_t()));
    JSON_mUtils_mCursors_Compile.Split<dafny.DafnySequence<? extends JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>>> _1_elems_k = JSON_mUtils_mCursors_Compile.Split.<dafny.DafnySequence<? extends JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>>>create(dafny.DafnySequence.<JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Suffixed.<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor())), dafny.DafnySequence.<JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>>concatenate((elems).dtor_t(), dafny.DafnySequence.<JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>> of(JSON_mGrammar_Compile.Suffixed.<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor()), _0_suffixed)), (sep).dtor_cs());
    return _1_elems_k;
  }
  public static JSON_mUtils_mCursors_Compile.Split<dafny.DafnySequence<? extends JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>>> AppendLast(JSON_mUtils_mCursors_Compile.Split<dafny.DafnySequence<? extends JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>>> elems, JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.jKeyValue> elem, JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>> sep)
  {
    JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__> _0_suffixed = JSON_mGrammar_Compile.Suffixed.<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>create(JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor(), (elem).dtor_t(), JSON_mGrammar_Compile.Maybe.<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>>create_Empty(JSON_mGrammar_Compile.Structural.<JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(JSON_mGrammar_Compile.jcomma._typeDescriptor())));
    JSON_mUtils_mCursors_Compile.Split<dafny.DafnySequence<? extends JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>>> _1_elems_k = JSON_mUtils_mCursors_Compile.Split.<dafny.DafnySequence<? extends JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>>>create(dafny.DafnySequence.<JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Suffixed.<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor())), dafny.DafnySequence.<JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>>concatenate((elems).dtor_t(), dafny.DafnySequence.<JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>> of(JSON_mGrammar_Compile.Suffixed.<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor()), _0_suffixed)), (elem).dtor_cs());
    return _1_elems_k;
  }
  public static Wrappers_Compile.Result<JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>, JSON_mUtils_mCursors_Compile.CursorError<JSON_mErrors_Compile.DeserializationError>> Elements(JSON_mUtils_mParsers_Compile.SubParser__<JSON_mGrammar_Compile.Value, JSON_mErrors_Compile.DeserializationError> json, JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>> open, JSON_mUtils_mCursors_Compile.Split<dafny.DafnySequence<? extends JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>>> elems)
  {
    TAIL_CALL_START: while (true) {
      Wrappers_Compile.Result<JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.jKeyValue>, JSON_mUtils_mCursors_Compile.CursorError<JSON_mErrors_Compile.DeserializationError>> _0_valueOrError0 = JSON_mZeroCopy_mDeserializer_mObjectParams_Compile.__default.Element((elems).dtor_cs(), json);
      if ((_0_valueOrError0).IsFailure(JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.jKeyValue>_typeDescriptor(JSON_mGrammar_Compile.jKeyValue._typeDescriptor()), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()))) {
        return (_0_valueOrError0).<JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>>PropagateFailure(JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.jKeyValue>_typeDescriptor(JSON_mGrammar_Compile.jKeyValue._typeDescriptor()), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()), JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Bracketed.<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(jopen._typeDescriptor(), JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor(), jclose._typeDescriptor())));
      } else {
        JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.jKeyValue> _1_elem = (_0_valueOrError0).Extract(JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.jKeyValue>_typeDescriptor(JSON_mGrammar_Compile.jKeyValue._typeDescriptor()), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()));
        if (((_1_elem).dtor_cs()).EOF_q()) {
          return Wrappers_Compile.Result.<JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>, JSON_mUtils_mCursors_Compile.CursorError<JSON_mErrors_Compile.DeserializationError>>create_Failure(JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Bracketed.<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(jopen._typeDescriptor(), JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor(), jclose._typeDescriptor())), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>create_EOF(JSON_mErrors_Compile.DeserializationError._typeDescriptor()));
        } else {
          JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>> _2_sep = JSON_mZeroCopy_mDeserializer_mCore_Compile.__default.TryStructural((_1_elem).dtor_cs());
          short _3_s0 = (((_2_sep).dtor_t()).dtor_t()).Peek();
          if (((_3_s0) == ((short) java.lang.Byte.toUnsignedInt(__default.SEPARATOR()))) && (((((_2_sep).dtor_t()).dtor_t()).Length()) == (1))) {
            JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>> _4_sep = _2_sep;
            JSON_mUtils_mCursors_Compile.Split<dafny.DafnySequence<? extends JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>>> _5_elems = __default.AppendWithSuffix(elems, _1_elem, _4_sep);
            JSON_mUtils_mParsers_Compile.SubParser__<JSON_mGrammar_Compile.Value, JSON_mErrors_Compile.DeserializationError> _in0 = json;
            JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>> _in1 = open;
            JSON_mUtils_mCursors_Compile.Split<dafny.DafnySequence<? extends JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>>> _in2 = _5_elems;
            json = _in0;
            open = _in1;
            elems = _in2;
            continue TAIL_CALL_START;
          } else if (((_3_s0) == ((short) java.lang.Byte.toUnsignedInt(JSON_mZeroCopy_mDeserializer_mObjectParams_Compile.__default.CLOSE()))) && (((((_2_sep).dtor_t()).dtor_t()).Length()) == (1))) {
            JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>> _6_sep = _2_sep;
            JSON_mUtils_mCursors_Compile.Split<dafny.DafnySequence<? extends JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>>> _7_elems_k = __default.AppendLast(elems, _1_elem, _6_sep);
            JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>> _8_bracketed = __default.BracketedFromParts(open, _7_elems_k, _6_sep);
            return Wrappers_Compile.Result.<JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>, JSON_mUtils_mCursors_Compile.CursorError<JSON_mErrors_Compile.DeserializationError>>create_Success(JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Bracketed.<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(jopen._typeDescriptor(), JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor(), jclose._typeDescriptor())), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()), _8_bracketed);
          } else {
            byte _9_separator = __default.SEPARATOR();
            Wrappers_Compile.Result<JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>, JSON_mUtils_mCursors_Compile.CursorError<JSON_mErrors_Compile.DeserializationError>> _10_pr = Wrappers_Compile.Result.<JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>, JSON_mUtils_mCursors_Compile.CursorError<JSON_mErrors_Compile.DeserializationError>>create_Failure(JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Bracketed.<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(jopen._typeDescriptor(), JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor(), jclose._typeDescriptor())), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>create_ExpectingAnyByte(JSON_mErrors_Compile.DeserializationError._typeDescriptor(), dafny.DafnySequence.<java.lang.Byte> of(JSON_mZeroCopy_mDeserializer_mObjectParams_Compile.__default.CLOSE(), _9_separator), _3_s0));
            return _10_pr;
          }
        }
      }
    }
  }
  public static Wrappers_Compile.Result<JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>, JSON_mUtils_mCursors_Compile.CursorError<JSON_mErrors_Compile.DeserializationError>> Bracketed(JSON_mUtils_mCursors_Compile.Cursor__ cs, JSON_mUtils_mParsers_Compile.SubParser__<JSON_mGrammar_Compile.Value, JSON_mErrors_Compile.DeserializationError> json)
  {
    Wrappers_Compile.Result<JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>>, JSON_mUtils_mCursors_Compile.CursorError<JSON_mErrors_Compile.DeserializationError>> _0_valueOrError0 = JSON_mZeroCopy_mDeserializer_mCore_Compile.__default.<JSON_mUtils_mViews_mCore_Compile.View__>Structural(jopen._typeDescriptor(), cs, JSON_mUtils_mParsers_Compile.Parser__.<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mErrors_Compile.DeserializationError>create(jopen._typeDescriptor(), JSON_mErrors_Compile.DeserializationError._typeDescriptor(), __default::Open));
    if ((_0_valueOrError0).IsFailure(JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Structural.<JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(jopen._typeDescriptor())), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()))) {
      return (_0_valueOrError0).<JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>>PropagateFailure(JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Structural.<JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(jopen._typeDescriptor())), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()), JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Bracketed.<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(jopen._typeDescriptor(), JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor(), jclose._typeDescriptor())));
    } else {
      JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>> _1_open = (_0_valueOrError0).Extract(JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Structural.<JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(jopen._typeDescriptor())), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()));
      JSON_mUtils_mCursors_Compile.Split<dafny.DafnySequence<? extends JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>>> _2_elems = JSON_mUtils_mCursors_Compile.Split.<dafny.DafnySequence<? extends JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>>>create(dafny.DafnySequence.<JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Suffixed.<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor())), dafny.DafnySequence.<JSON_mGrammar_Compile.Suffixed<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>> empty(JSON_mGrammar_Compile.Suffixed.<JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor())), (_1_open).dtor_cs());
      if ((((_1_open).dtor_cs()).Peek()) == ((short) java.lang.Byte.toUnsignedInt(JSON_mZeroCopy_mDeserializer_mObjectParams_Compile.__default.CLOSE()))) {
        JSON_mUtils_mParsers_Compile.Parser__<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mErrors_Compile.DeserializationError> _3_p = JSON_mUtils_mParsers_Compile.Parser__.<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mErrors_Compile.DeserializationError>create(jclose._typeDescriptor(), JSON_mErrors_Compile.DeserializationError._typeDescriptor(), __default::Close);
        Wrappers_Compile.Result<JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>>, JSON_mUtils_mCursors_Compile.CursorError<JSON_mErrors_Compile.DeserializationError>> _4_valueOrError1 = JSON_mZeroCopy_mDeserializer_mCore_Compile.__default.<JSON_mUtils_mViews_mCore_Compile.View__>Structural(jclose._typeDescriptor(), (_1_open).dtor_cs(), _3_p);
        if ((_4_valueOrError1).IsFailure(JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Structural.<JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(jclose._typeDescriptor())), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()))) {
          return (_4_valueOrError1).<JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>>PropagateFailure(JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Structural.<JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(jclose._typeDescriptor())), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()), JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Bracketed.<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(jopen._typeDescriptor(), JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor(), jclose._typeDescriptor())));
        } else {
          JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>> _5_close = (_4_valueOrError1).Extract(JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.Structural<JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Structural.<JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(jclose._typeDescriptor())), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()));
          return Wrappers_Compile.Result.<JSON_mUtils_mCursors_Compile.Split<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>, JSON_mUtils_mCursors_Compile.CursorError<JSON_mErrors_Compile.DeserializationError>>create_Success(JSON_mUtils_mCursors_Compile.Split.<JSON_mGrammar_Compile.Bracketed<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>>_typeDescriptor(JSON_mGrammar_Compile.Bracketed.<JSON_mUtils_mViews_mCore_Compile.View__, JSON_mGrammar_Compile.jKeyValue, JSON_mUtils_mViews_mCore_Compile.View__, JSON_mUtils_mViews_mCore_Compile.View__>_typeDescriptor(jopen._typeDescriptor(), JSON_mGrammar_Compile.jKeyValue._typeDescriptor(), JSON_mGrammar_Compile.jcomma._typeDescriptor(), jclose._typeDescriptor())), JSON_mUtils_mCursors_Compile.CursorError.<JSON_mErrors_Compile.DeserializationError>_typeDescriptor(JSON_mErrors_Compile.DeserializationError._typeDescriptor()), __default.BracketedFromParts(_1_open, _2_elems, _5_close));
        }
      } else {
        return __default.Elements(json, _1_open, _2_elems);
      }
    }
  }
  public static java.util.function.Function<JSON_mUtils_mViews_mCore_Compile.View__, dafny.DafnySequence<? extends java.lang.Byte>> SpecViewOpen()
  {
    return JSON_mZeroCopy_mDeserializer_mCore_Compile.__default.SpecView();
  }
  public static java.util.function.Function<JSON_mUtils_mViews_mCore_Compile.View__, dafny.DafnySequence<? extends java.lang.Byte>> SpecViewClose()
  {
    return JSON_mZeroCopy_mDeserializer_mCore_Compile.__default.SpecView();
  }
  public static byte SEPARATOR()
  {
    return ((byte) (','));
  }
  @Override
  public java.lang.String toString() {
    return "JSON.ZeroCopy.Deserializer.Objects._default";
  }
}
