// Code generated by smithy-go-codegen DO NOT EDIT.

package awscryptographymaterialproviderstestvectorkeyssmithygeneratedtypes

import (
	"fmt"
)

type KeyVectorException struct {
	KeyVectorsBaseException
	Message           string
	ErrorCodeOverride *string
}

func (e KeyVectorException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCodeOverride, e.Message)
}
