// Class __default
// Dafny class __default compiled into Java
package KeysVectorOperations_Compile;

@SuppressWarnings({"unchecked", "deprecation"})
public class __default {
  public __default() {
  }
  public static boolean CreateTestVectorKeyringEnsuresPublicly(software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.TestVectorKeyringInput input, Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> output)
  {
    return true;
  }
  public static Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> CreateTestVectorKeyring(Config config, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.TestVectorKeyringInput input)
  {
    Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> output = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)null;
    if(true) {
      Wrappers_Compile.Outcome<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _0_valueOrError0 = Wrappers_Compile.Outcome.<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>Default(software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
      _0_valueOrError0 = Wrappers_Compile.__default.<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>Need(software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), KeyDescription_Compile.__default.Keyring_q((input).dtor_keyDescription()), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_KeyVectorException(dafny.DafnySequence.asString("Only Keyring key descriptions are supported.")));
      if ((_0_valueOrError0).IsFailure(software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
        output = (_0_valueOrError0).<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>PropagateFailure(software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)));
        return output;
      }
      Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _1_maybeMpl;
      Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _out0;
      _out0 = software.amazon.cryptography.materialproviders.internaldafny.__default.MaterialProviders(software.amazon.cryptography.materialproviders.internaldafny.__default.DefaultMaterialProvidersConfig());
      _1_maybeMpl = _out0;
      Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _2_valueOrError1 = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)null;
      _2_valueOrError1 = (_1_maybeMpl).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>MapFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient.class)), software.amazon.cryptography.materialproviders.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.materialproviders.internaldafny.types.Error, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)(_3_e_boxed0) -> {
        software.amazon.cryptography.materialproviders.internaldafny.types.Error _3_e = ((software.amazon.cryptography.materialproviders.internaldafny.types.Error)(java.lang.Object)(_3_e_boxed0));
        return software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(_3_e);
      }));
      if ((_2_valueOrError1).IsFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
        output = (_2_valueOrError1).<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>PropagateFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)));
        return output;
      }
      software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient _4_mpl;
      _4_mpl = (_2_valueOrError1).Extract(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
      Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _out1;
      _out1 = KeyringFromKeyDescription_Compile.__default.ToKeyring(_4_mpl, (config).dtor_keys(), (input).dtor_keyDescription());
      output = _out1;
    }
    return output;
  }
  public static boolean CreateWrappedTestVectorKeyringEnsuresPublicly(software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.TestVectorKeyringInput input, Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> output)
  {
    return true;
  }
  public static Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> CreateWrappedTestVectorKeyring(Config config, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.TestVectorKeyringInput input)
  {
    Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> output = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)null;
    if(true) {
      Wrappers_Compile.Outcome<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _0_valueOrError0 = Wrappers_Compile.Outcome.<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>Default(software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
      _0_valueOrError0 = Wrappers_Compile.__default.<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>Need(software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), KeyDescription_Compile.__default.Keyring_q((input).dtor_keyDescription()), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_KeyVectorException(dafny.DafnySequence.asString("Only Keyring key descriptions are supported.")));
      if ((_0_valueOrError0).IsFailure(software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
        output = (_0_valueOrError0).<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>PropagateFailure(software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)));
        return output;
      }
      Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _1_maybeMpl;
      Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _out0;
      _out0 = software.amazon.cryptography.materialproviders.internaldafny.wrapped.__default.WrappedMaterialProviders(software.amazon.cryptography.materialproviders.internaldafny.wrapped.__default.WrappedDefaultMaterialProvidersConfig());
      _1_maybeMpl = _out0;
      Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _2_valueOrError1 = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)null;
      _2_valueOrError1 = (_1_maybeMpl).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>MapFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient.class)), software.amazon.cryptography.materialproviders.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.materialproviders.internaldafny.types.Error, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)(_3_e_boxed0) -> {
        software.amazon.cryptography.materialproviders.internaldafny.types.Error _3_e = ((software.amazon.cryptography.materialproviders.internaldafny.types.Error)(java.lang.Object)(_3_e_boxed0));
        return software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(_3_e);
      }));
      if ((_2_valueOrError1).IsFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
        output = (_2_valueOrError1).<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>PropagateFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class)));
        return output;
      }
      software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient _4_wrappedMPL;
      _4_wrappedMPL = (_2_valueOrError1).Extract(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
      Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _out1;
      _out1 = KeyringFromKeyDescription_Compile.__default.ToKeyring(_4_wrappedMPL, (config).dtor_keys(), (input).dtor_keyDescription());
      output = _out1;
    }
    return output;
  }
  public static boolean CreateWrappedTestVectorCmmEnsuresPublicly(software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.TestVectorCmmInput input, Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> output)
  {
    return true;
  }
  public static Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> CreateWrappedTestVectorCmm(Config config, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.TestVectorCmmInput input)
  {
    Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> output = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)null;
    if(true) {
      Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _0_maybeMpl;
      Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _out0;
      _out0 = software.amazon.cryptography.materialproviders.internaldafny.wrapped.__default.WrappedMaterialProviders(software.amazon.cryptography.materialproviders.internaldafny.wrapped.__default.WrappedDefaultMaterialProvidersConfig());
      _0_maybeMpl = _out0;
      Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _1_valueOrError0 = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)null;
      _1_valueOrError0 = (_0_maybeMpl).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>MapFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient.class)), software.amazon.cryptography.materialproviders.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.materialproviders.internaldafny.types.Error, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)(_2_e_boxed0) -> {
        software.amazon.cryptography.materialproviders.internaldafny.types.Error _2_e = ((software.amazon.cryptography.materialproviders.internaldafny.types.Error)(java.lang.Object)(_2_e_boxed0));
        return software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(_2_e);
      }));
      if ((_1_valueOrError0).IsFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
        output = (_1_valueOrError0).<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>PropagateFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)));
        return output;
      }
      software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient _3_wrappedMPL;
      _3_wrappedMPL = (_1_valueOrError0).Extract(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IAwsCryptographicMaterialProvidersClient.class)), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
      Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _out1;
      _out1 = CmmFromKeyDescription_Compile.__default.ToCmm(_3_wrappedMPL, (config).dtor_keys(), (input).dtor_keyDescription(), (input).dtor_forOperation());
      output = _out1;
    }
    return output;
  }
  public static Wrappers_Compile.Result<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.GetKeyDescriptionOutput, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> GetKeyDescription(Config config, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.GetKeyDescriptionInput input)
  {
    Wrappers_Compile.Result<JSON_mValues_Compile.JSON, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _0_valueOrError0 = (JSON_mAPI_Compile.__default.Deserialize((input).dtor_json())).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>MapFailure(JSON_mValues_Compile.JSON._typeDescriptor(), JSON_mErrors_Compile.DeserializationError._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<JSON_mErrors_Compile.DeserializationError, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)(_1_e_boxed0) -> {
      JSON_mErrors_Compile.DeserializationError _1_e = ((JSON_mErrors_Compile.DeserializationError)(java.lang.Object)(_1_e_boxed0));
      return software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(software.amazon.cryptography.materialproviders.internaldafny.types.Error.create_AwsCryptographicMaterialProvidersException((_1_e).ToString()));
    }));
    if ((_0_valueOrError0).IsFailure(JSON_mValues_Compile.JSON._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
      return (_0_valueOrError0).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.GetKeyDescriptionOutput>PropagateFailure(JSON_mValues_Compile.JSON._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.GetKeyDescriptionOutput._typeDescriptor());
    } else {
      JSON_mValues_Compile.JSON _2_keyDescriptionJSON = (_0_valueOrError0).Extract(JSON_mValues_Compile.JSON._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
      Wrappers_Compile.Result<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _3_valueOrError1 = (KeyDescription_Compile.__default.ToKeyDescription(_2_keyDescriptionJSON)).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>MapFailure(software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)(_4_e_boxed0) -> {
        dafny.DafnySequence<? extends Character> _4_e = ((dafny.DafnySequence<? extends Character>)(java.lang.Object)(_4_e_boxed0));
        return software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(software.amazon.cryptography.materialproviders.internaldafny.types.Error.create_AwsCryptographicMaterialProvidersException(_4_e));
      }));
      if ((_3_valueOrError1).IsFailure(software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
        return (_3_valueOrError1).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.GetKeyDescriptionOutput>PropagateFailure(software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.GetKeyDescriptionOutput._typeDescriptor());
      } else {
        software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription _5_keyDescription = (_3_valueOrError1).Extract(software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.KeyDescription._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
        return Wrappers_Compile.Result.<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.GetKeyDescriptionOutput, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>create_Success(software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.GetKeyDescriptionOutput._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.GetKeyDescriptionOutput.create(_5_keyDescription));
      }
    }
  }
  public static Wrappers_Compile.Result<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.SerializeKeyDescriptionOutput, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> SerializeKeyDescription(Config config, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.SerializeKeyDescriptionInput input)
  {
    Wrappers_Compile.Result<JSON_mValues_Compile.JSON, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _0_valueOrError0 = (KeyDescription_Compile.__default.ToJson((input).dtor_keyDescription(), java.math.BigInteger.valueOf(2L))).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>MapFailure(JSON_mValues_Compile.JSON._typeDescriptor(), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)(_1_s_boxed0) -> {
      dafny.DafnySequence<? extends Character> _1_s = ((dafny.DafnySequence<? extends Character>)(java.lang.Object)(_1_s_boxed0));
      return software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(software.amazon.cryptography.materialproviders.internaldafny.types.Error.create_AwsCryptographicMaterialProvidersException(_1_s));
    }));
    if ((_0_valueOrError0).IsFailure(JSON_mValues_Compile.JSON._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
      return (_0_valueOrError0).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.SerializeKeyDescriptionOutput>PropagateFailure(JSON_mValues_Compile.JSON._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.SerializeKeyDescriptionOutput._typeDescriptor());
    } else {
      JSON_mValues_Compile.JSON _2_json = (_0_valueOrError0).Extract(JSON_mValues_Compile.JSON._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
      Wrappers_Compile.Result<dafny.DafnySequence<? extends java.lang.Byte>, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error> _3_valueOrError1 = (JSON_mAPI_Compile.__default.Serialize(_2_json)).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>MapFailure(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), JSON_mErrors_Compile.SerializationError._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<JSON_mErrors_Compile.SerializationError, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>)(_4_e_boxed0) -> {
        JSON_mErrors_Compile.SerializationError _4_e = ((JSON_mErrors_Compile.SerializationError)(java.lang.Object)(_4_e_boxed0));
        return software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(software.amazon.cryptography.materialproviders.internaldafny.types.Error.create_AwsCryptographicMaterialProvidersException((_4_e).ToString()));
      }));
      if ((_3_valueOrError1).IsFailure(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor())) {
        return (_3_valueOrError1).<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.SerializeKeyDescriptionOutput>PropagateFailure(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.SerializeKeyDescriptionOutput._typeDescriptor());
      } else {
        dafny.DafnySequence<? extends java.lang.Byte> _5_jsonBytes = (_3_valueOrError1).Extract(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor());
        return Wrappers_Compile.Result.<software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.SerializeKeyDescriptionOutput, software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error>create_Success(software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.SerializeKeyDescriptionOutput._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.materialproviderstestvectorkeys.internaldafny.types.SerializeKeyDescriptionOutput.create(_5_jsonBytes));
      }
    }
  }
  @Override
  public java.lang.String toString() {
    return "KeysVectorOperations._default";
  }
}
