[package]
name = "aws-mpl-test-vectors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "1.8.6"
aws-lc-rs = {version = "1.14.0"}
aws-lc-sys = { version = "0.31", optional = true }
aws-lc-fips-sys = { version = "0.13", optional = true }
aws-sdk-dynamodb = "1.92.0"
aws-sdk-kms = "1.86.0"
aws-smithy-runtime-api = {version = "1.9.0", features = ["client"] }
aws-smithy-types = "1.3.2"
chrono = "0.4.42"
cpu-time = "1.0.0"
dafny_runtime = { path = "../../../smithy-dafny/TestModels/dafny-dependencies/dafny_runtime_rust", features = ["sync","small-int"]}
dashmap = "6.1.0"
pem = "3.0.5"
tokio = {version = "1.47.1", features = ["full"] }
uuid = { version = "1.18.1", features = ["v4"] }
ring = "0.17.14"

[dev-dependencies]
aws-mpl-test-vectors = { path = ".", features = ["wrapped-client"] }

[[bin]]
name = "test-vectors"
path = "src/main.rs"

[features]
wrapped-client = []
fips = ["aws-lc-rs/fips", "dep:aws-lc-fips-sys"]
non-fips = ["aws-lc-rs/aws-lc-sys", "dep:aws-lc-sys"]
default = ["non-fips"]
