# This workflow ensures rc-1.7.0 does not go to main until .NET testing is restored
name: rc-1.7.0-no-main

on:
  pull_request:
    branches:
      - main
jobs:
  forbid:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: exit 1
# When we revert this, we MUST revert/restore:
# .github/workflows/library_net_tests.yml#L27-L30
# .github/workflows/library_interop_tests.yml#L28-31
# .github/workflows/library_interop_tests.yml#L134-139
