# This workflow checks if specfic files were modified,
# if they were they require more than one approval from CODEOWNERS
name: Check Files

on:
  pull_request:
  pull_request_review:

jobs:
  checkRequiredApprovalsReleaseFiles:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check required approvals
        uses: weetbix/configurable-required-approvals@v1
        with:
          requirements: |
            - patterns:
                - ".github/**/**"
              requiredApprovals: 2
          github-token: ${{ secrets.GITHUB_TOKEN }}
