# This workflow checks if specfic files were modified,
# if they were they require more than one approval from CODEOWNERS
name: Check Files

on:
  pull_request:

jobs:
  checkFiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get Files changed
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run:
          FILES=$(git diff --name-only origin/main origin/${GITHUB_HEAD_REF})
          echo $FILES

      