# This workflow checks if specfic files were modified,
# if they were they require more than one approval from CODEOWNERS
name: Check Release Files

on:
  pull_request:
  pull_request_review:

jobs:
  required-approvals:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Check required approvals
        uses: weetbix/configurable-required-approvals@v1.0.1
        with:
          requirements: |
            - patterns:
                - "./.github/workflows/*release.yml"
              requiredApprovals: 2
          github-token: ${{ secrets.GITHUB_TOKEN }}
