name: PR Approval Workflow

on:
  pull_request:
    branches:
      - main
  pull_request_review:
    types: [submitted]

jobs:
  check-approvals:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: read
    steps:
      - name: Check for required approvals
        id: check-approvals
        uses: skymoore/required-approvals@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          read_org_scoped_token: ${{ secrets.GITHUB_TOKEN  }}
          org_name: aws
          min_approvals: 2
