# This workflow performs static analysis checks.
name: static analysis

on:
  workflow_call:
  workflow_dispatch:

jobs:
  not-grep:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: not-grep
        uses: mattsb42-meta/not-grep@1.0.0
