# This workflow reads the project.properties
# into the environment variables
# and then creates an output variable for `dafnyVersion`, `dafnyVerifyVersion`
# and `dafnyRustVersion`
name: Dafny Versions

on:
  workflow_call:
    outputs:
      version:
        description: "The dafny version"
        value: ${{ jobs.getDafnyVersion.outputs.version }}
      verifyVersion:
        description: "The dafny version for verification"
        value: ${{ jobs.getDafnyVersion.outputs.verifyVersion }}
      rustVersion:
        description: "The dafny version when translating to Rust"
        value: ${{ jobs.getDafnyVersion.outputs.rustVersion }}

jobs:
  getDafnyVersion:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.read_property.outputs.dafnyVersion }}
      verifyVersion: ${{ steps.read_property.outputs.dafnyVerifyVersion }}
      rustVersion: ${{ steps.read_property.outputs.dafnyRustVersion }}
    steps:
      - uses: actions/checkout@v4
      - name: Read version from Properties-file
        id: read_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: "./project.properties"
          properties: "dafnyVersion dafnyVerifyVersion dafnyRustVersion"
