name: MPL Fuzz Testing

on:
  # Run on main branch changes
  push:
    branches: [ main ]
  
  # Run on PRs
  pull_request:
    branches: [ main ]
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Runtime to test'
        required: true
        default: 'python'
        type: choice
        options:
          - python
          - java
          - net
          - rust
          - go
      num_vectors:
        description: 'Number of test vectors to generate'
        required: false
        default: '1000'
        type: string

  # Run scheduled tests (weekly on Sunday)
  schedule:
    - cron: '0 0 * * 0'

jobs:
  basic-fuzz-test:
    name: Basic Fuzz Tests (Python Runtime)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hypothesis pytest
      
      - name: Generate and run tests
        run: |
          chmod +x TestVectorsAwsCryptographicMaterialProviders/runtimes/python/test/run_fuzz_tests.sh
          chmod +x TestVectorsAwsCryptographicMaterialProviders/runtimes/python/test/generate_fuzz_vectors.py
          cd TestVectorsAwsCryptographicMaterialProviders/runtimes/python/test
          ./run_fuzz_tests.sh --runtime python --num-vectors 100 --verbose
      
      - name: Archive test artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: fuzz-test-artifacts
          path: |
            TestVectorsAwsCryptographicMaterialProviders/runtimes/python/fuzz_manifest.json
            TestVectorsAwsCryptographicMaterialProviders/runtimes/python/fuzz_failures.log
          retention-days: 7

  # This job only runs on manual trigger or scheduled run
  extended-fuzz-test:
    name: Extended Fuzz Tests (${{ github.event.inputs.runtime || 'python' }})
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hypothesis pytest
      
      - name: Set up Java (if needed)
        if: ${{ github.event.inputs.runtime == 'java' || github.event_name == 'schedule' }}
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Set up .NET (if needed)
        if: ${{ github.event.inputs.runtime == 'net' || github.event_name == 'schedule' }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      
      - name: Set up Rust (if needed)
        if: ${{ github.event.inputs.runtime == 'rust' || github.event_name == 'schedule' }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      
      - name: Set up Go (if needed)
        if: ${{ github.event.inputs.runtime == 'go' || github.event_name == 'schedule' }}
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: Generate and run tests
        run: |
          mkdir -p TestVectorsAwsCryptographicMaterialProviders/runtimes/python
          chmod +x TestVectorsAwsCryptographicMaterialProviders/runtimes/python/test/run_fuzz_tests.sh
          cd TestVectorsAwsCryptographicMaterialProviders/runtimes/python/test
          ./run_fuzz_tests.sh --runtime ${{ github.event.inputs.runtime || 'python' }} --num-vectors ${{ github.event.inputs.num_vectors || '1000' }} --verbose
      
      - name: Archive test artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: extended-fuzz-test-artifacts
          path: |
            TestVectorsAwsCryptographicMaterialProviders/runtimes/*/fuzz_manifest.json
            TestVectorsAwsCryptographicMaterialProviders/runtimes/*/fuzz_failures.log
          retention-days: 7
