# This workflow performs tests in Go using pre-built artifacts.
name: Library Go tests

on:
  workflow_call:
    inputs:
      dafny:
        description: "The Dafny version to run"
        required: true
        type: string
      regenerate-code:
        description: "Regenerate code using smithy-dafny"
        required: false
        default: false
        type: boolean

jobs:
  buildGo:
    uses: ./.github/workflows/library_go_build.yml
    with:
      dafny: ${{ inputs.dafny }}
      regenerate-code: ${{ inputs.regenerate-code }}

  testGo:
    needs: buildGo
    strategy:
      fail-fast: false
      matrix:
        library:
          [
            StandardLibrary,
            ComAmazonawsKms,
            ComAmazonawsDynamodb,
            AwsCryptographyPrimitives,
            AwsCryptographicMaterialProviders,
            TestVectorsAwsCryptographicMaterialProviders,
          ]
        go-version: ["1.24", "1.25"]
        # TODO fix Dafny-generated tests on Windows;
        # the sys.path workaround for generated Dafny doesn't work on Windows.
        # Note: only tests use the sys.path workaround, not source code.
        # Windows source code is tested downstream (ex. ESDK-Python CI).
        # windows-latest,
        os: [ubuntu-22.04, macos-14]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Support longpaths on Git checkout
        run: |
          git config --global core.longpaths true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::370957321024:role/GitHub-CI-MPL-Dafny-Role-us-west-2
          role-session-name: GoTests
          special-characters-workaround: "true" # Some environments (example: windowsOS) cannot tolerate special characters in a secret key.

      - uses: actions/checkout@v6
      - run: git submodule update --init libraries
      - run: git submodule update --init --recursive smithy-dafny

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Download generated Go source
        uses: actions/download-artifact@v8
        with:
          name: go-generated-${{ matrix.os }}-${{ github.sha }}
          path: .

      - name: Test ${{ matrix.library }}
        working-directory: ./${{ matrix.library }}
        run: |
          make test_go

      # This is only to test AwsCryptographicMaterialProviders which has local cmc test inside it.
      - name: Test local CMC
        if: matrix.library == 'AwsCryptographicMaterialProviders'
        working-directory: ./${{ matrix.library }}/runtimes/go/TestsFromDafny-go
        run: |
          go test
