# This workflow performs tests in Rust using pre-built artifacts.
name: Library Rust tests

on:
  workflow_call:
    inputs:
      dafny:
        description: "The Dafny version to run"
        required: true
        type: string
      regenerate-code:
        description: "Regenerate code using smithy-dafny"
        required: false
        default: false
        type: boolean

jobs:
  buildRust:
    uses: ./.github/workflows/library_rust_build.yml
    with:
      dafny: ${{ inputs.dafny }}
      regenerate-code: ${{ inputs.regenerate-code }}

  testRust:
    needs: buildRust
    strategy:
      fail-fast: false
      matrix:
        library:
          [
            StandardLibrary,
            ComAmazonawsDynamodb,
            ComAmazonawsKms,
            AwsCryptographyPrimitives,
            AwsCryptographicMaterialProviders,
            TestVectorsAwsCryptographicMaterialProviders,
          ]
        # removed windows-latest because somehow it can't build aws-lc in CI
        os: [ubuntu-22.04, macos-14]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    env:
      RUST_MIN_STACK: 404857600
    steps:
      - name: Support longpaths on Git checkout
        run: |
          git config --global core.longpaths true
      - uses: actions/checkout@v6
      - name: Init Submodules
        shell: bash
        run: |
          git submodule update --init libraries
          git submodule update --init --recursive smithy-dafny

      - name: Configure AWS Credentials
        uses: Wandalen/wretry.action@v3.8.0
        with:
          action: aws-actions/configure-aws-credentials@v6.1.2
          with: |
            aws-region: us-west-2
            role-to-assume: arn:aws:iam::370957321024:role/GitHub-CI-MPL-Dafny-Role-us-west-2
            role-session-name: RustTests
            special-characters-workaround: "true" # Some environments (example: windowsOS) cannot tolerate special characters in a secret key.
          attempt_limit: 5
          attempt_delay: 30000

      - name: Setup Rust Toolchain for GitHub CI
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          cache: false

      # Go is needed for aws-lc-FIPS
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ">=1.18"

      - run: echo "TIMESTAMP=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Download generated Rust source
        uses: actions/download-artifact@v8
        with:
          name: rust-generated-${{ env.TIMESTAMP }}-${{ matrix.os }}-${{ github.sha }}
          path: .

      - name: Test ${{ matrix.library }} Rust
        shell: bash
        working-directory: ./${{ matrix.library }}/runtimes/rust
        run: |
          cargo test --release -- --nocapture
          cargo test -- --nocapture

      - name: Test ${{ matrix.library }} Rust Fips
        if: matrix.library == 'AwsCryptographyPrimitives' || matrix.library == 'AwsCryptographicMaterialProviders' || matrix.library == 'TestVectorsAwsCryptographicMaterialProviders'
        shell: bash
        working-directory: ./${{ matrix.library }}/runtimes/rust
        run: |
          cargo test --release --features fips -- --nocapture
          cargo test --features fips -- --nocapture
