# This workflow performs MPL NET release
name: MPL-Release-Net-Lib

on:
  workflow_call:
    inputs:
      dafny:
        description: "The Dafny version to run"
        required: true
        type: string
      version:
          description: "The version being released"
          required: true
          type: string
      unique-id:
          description: "The unique signing id"
          required: true
          type: string
      project:
          description: "The project being released"
          required: true
          type: string
jobs:
  sign:
    strategy:
      matrix:
        dotnet-version: ["6.0.x"]
    runs-on: codebuild-AWS-MPL-Release-${{ github.run_id }}-${{ github.run_attempt }}-ubuntu-5.0-large
    permissions:
      id-token: write
      contents: read
    env:
      UNIQUE_ID: ${{inputs.unique-id}}
    steps:
      - name: Support longpaths on Git checkout
        run: |
          git config --global core.longpaths true
      
      - uses: actions/checkout@v4
      # The specification submodule is private so we don't have access, but we don't need
      # it to verify the Dafny code. Instead we manually pull the submodules we DO need.
      - run: git submodule update --init libraries
      - run: git submodule update --init smithy-dafny
      
      - name: Configure AWS Credentials for Tests
        uses: aws-actions/configure-aws-credentials@v4
        if: inputs.project == 'ComAmazonawsKms' || inputs.project == 'ComAmazonawsDynamodb' || inputs.project == 'AwsCryptographicMaterialProviders'
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::370957321024:role/GitHub-CI-MPL-Dafny-Role-us-west-2
          role-session-name: NetReleaseTests

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'     
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1.7.0
        with:
          dafny-version: ${{ inputs.dafny }}
      - name: Export signing ID
        shell: bash
        run: |
          export UNIQUE_ID=${{inputs.unique-id}};
      - name: make ${{inputs.project}}
        shell: bash
        working-directory: ./${{inputs.project}}
        run: |
          make transpile_net
          make test_net FRAMEWORK=net6.0
      - name: Unset AWS Creds
        shell: bash
        run: |
          echo "AWS_ACCESS_KEY_ID=" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=" >> $GITHUB_ENV
          echo "AWS_REGION=" >> $GITHUB_ENV
      - name: Build ${{inputs.project}}
        shell: bash
        working-directory: ./${{inputs.project}}
        run: |
          dotnet build runtimes/net /p:Configuration=Release -nowarn:CS0162,CS0168
      - name: Upload ${{inputs.project}} DLL to signing bucket
        shell: bash
        working-directory: ./${{inputs.project}}
        run: |
          pip install boto3
          export ASSEMBLY_NAME="AWS.Cryptography.Internal.StandardLibrary.dll"
          export BASE=../codebuild/net
          python $BASE/upload_assembly.py --target net6.0 --unique-id $UNIQUE_ID
          python $BASE/upload_assembly.py --target net48 --unique-id $UNIQUE_ID
          ## Retrieve the signed assembly. We're not going to use it, but this
          ## ensures that the signing process is complete
          python $BASE/retrieve_signed_assembly.py --target net6.0 --unique-id $UNIQUE_ID
          python $BASE/retrieve_signed_assembly.py --target net48 --unique-id $UNIQUE_ID
  
  verify:
    needs: sign
    strategy:
      matrix:
        dotnet-version: ["6.0.x"]
        dotnet-target: [net48, net6.0]
    env:
      UNIQUE_ID: ${{inputs.unique-id}}
    runs-on: codebuild-AWS-MPL-Release-${{ github.run_id }}-${{ github.run_attempt }}-windows-3.0-large
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Support longpaths on Git checkout
        run: |
          git config --global core.longpaths true
      
      - uses: actions/checkout@v4
      # The specification submodule is private so we don't have access, but we don't need
      # it to verify the Dafny code. Instead we manually pull the submodules we DO need.
      - run: git submodule update --init libraries
      - run: git submodule update --init smithy-dafny

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'     
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Check Signatures on ${{matrix.dotnet-target}}
        if: ${{inputs.project}} != 'AwsCryptographicMaterialProviders'
        run: |
          echo "FILE_NAME="AWS.Cryptography.Internal.${{inputs.project}}.dll" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "ASSEMBLY_NAME="AWS.Cryptography.Internal.${{inputs.project}}.dll" | Out-File -FilePath $env:GITHUB_ENV -Append
          pip install boto3
          mkdir ${{matrix.dotnet-target}}
          python codebuild/net/retrieve_signed_assembly.py --target ${{matrix.dotnet-target}} --unique-id $Env:UNIQUE_ID --output ${{matrix.dotnet-target}}
          $sig = Get-AuthenticodeSignature -FilePath ${{matrix.dotnet-target}}/$Env:FILE_NAME
          $sig | Format-List -Property *
      
      - name: Check Signatures on ${{matrix.dotnet-target}}
        if: ${{inputs.project}} == 'AwsCryptographicMaterialProviders'
        run: |
          echo "FILE_NAME="AWS.Cryptography.MaterialProviders.dll" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "ASSEMBLY_NAME="AWS.Cryptography.MaterialProviders.dll" | Out-File -FilePath $env:GITHUB_ENV -Append
          pip install boto3
          mkdir ${{matrix.dotnet-target}}
          python codebuild/net/retrieve_signed_assembly.py --target ${{matrix.dotnet-target}} --unique-id $Env:UNIQUE_ID --output ${{matrix.dotnet-target}}
          $sig = Get-AuthenticodeSignature -FilePath ${{matrix.dotnet-target}}/$Env:FILE_NAME
          $sig | Format-List -Property *        
  
  # releaseToCA:
  #   needs: verify
  #   strategy:
  #     matrix:
  #       dotnet-version: ["6.0.x"]
  #   runs-on: codebuild-AWS-MPL-Release-ubuntu-5.0-large
  #   permissions:
  #     id-token: write
  #     contents: read
  #   steps:
  #     - name: Support longpaths on Git checkout
  #       run: |
  #         git config --global core.longpaths true
  
  # releaseToProd:
  #   needs: releaseToCA
  #   strategy:
  #     matrix:
  #       dotnet-version: ["6.0.x"]
  #   runs-on: codebuild-AWS-MPL-Release-ubuntu-5.0-large
  #   permissions:
  #     id-token: write
  #     contents: read
  #   steps:
  #     - name: Support longpaths on Git checkout
  #       run: |
  #         git config --global core.longpaths true
  
  # testProd:
  #   needs: releaseToProd
  #   strategy:
  #     matrix:
  #       dotnet-version: ["6.0.x"]
  #   runs-on: codebuild-AWS-MPL-Release-ubuntu-5.0-large
  #   permissions:
  #     id-token: write
  #     contents: read
  #   steps:
  #     - name: Support longpaths on Git checkout
  #       run: |
  #         git config --global core.longpaths true
    
    