# This workflow performs MPL NET release
name: MPL-Release-Net-Lib

on:
  workflow_call:
    inputs:
      dafny:
        description: "The Dafny version to run"
        required: true
        type: string
      version:
          description: "The version being released"
          required: true
          type: string
      unique-id:
          description: "The unique signing id"
          required: true
          type: string
      project:
          description: "The project being released"
          required: true
          type: string
jobs:
  sign:
    strategy:
      matrix:
        dotnet-version: ["6.0.x"]
    runs-on: codebuild-AWS-MPL-Release-${{ github.run_id }}-${{ github.run_attempt }}-ubuntu-5.0-large
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Support longpaths on Git checkout
        run: |
          git config --global core.longpaths true
      
      - uses: actions/checkout@v4
      # The specification submodule is private so we don't have access, but we don't need
      # it to verify the Dafny code. Instead we manually pull the submodules we DO need.
      - run: git submodule update --init libraries
      - run: git submodule update --init smithy-dafny
      
      - name: Configure AWS Credentials for Tests
        uses: aws-actions/configure-aws-credentials@v4
        if: inputs.project == 'ComAmazonawsKms' || inputs.project == 'ComAmazonawsDynamodb' || inputs.project == 'AwsCryptographicMaterialProviders'
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::370957321024:role/GitHub-CI-MPL-Dafny-Role-us-west-2
          role-session-name: NetReleaseTests

      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1.7.0
        with:
          dafny-version: ${{ inputs.dafny }}
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Export signing ID
        shell: bash
        run: |
          export UNIQUE_ID=${{inputs.unique-id}};
      - name: Build ${{inputs.project}}
        shell: bash
        working-directory: ./${{inputs.project}}
        run: |
          make transpile_net
          make test_net FRAMEWORK=net6.0
  
  verify:
    needs: sign
    strategy:
      matrix:
        dotnet-version: ["6.0.x"]
    runs-on: codebuild-AWS-MPL-Release-${{ github.run_id }}-${{ github.run_attempt }}-ubuntu-5.0-large
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Support longpaths on Git checkout
        run: |
          git config --global core.longpaths true
  
  # releaseToCA:
  #   needs: verify
  #   strategy:
  #     matrix:
  #       dotnet-version: ["6.0.x"]
  #   runs-on: codebuild-AWS-MPL-Release-ubuntu-5.0-large
  #   permissions:
  #     id-token: write
  #     contents: read
  #   steps:
  #     - name: Support longpaths on Git checkout
  #       run: |
  #         git config --global core.longpaths true
  
  # releaseToProd:
  #   needs: releaseToCA
  #   strategy:
  #     matrix:
  #       dotnet-version: ["6.0.x"]
  #   runs-on: codebuild-AWS-MPL-Release-ubuntu-5.0-large
  #   permissions:
  #     id-token: write
  #     contents: read
  #   steps:
  #     - name: Support longpaths on Git checkout
  #       run: |
  #         git config --global core.longpaths true
  
  # testProd:
  #   needs: releaseToProd
  #   strategy:
  #     matrix:
  #       dotnet-version: ["6.0.x"]
  #   runs-on: codebuild-AWS-MPL-Release-ubuntu-5.0-large
  #   permissions:
  #     id-token: write
  #     contents: read
  #   steps:
  #     - name: Support longpaths on Git checkout
  #       run: |
  #         git config --global core.longpaths true
    
    