name: Rebase Mutations Branch

on:
  push:
    branches:
      - main

jobs:
  rebase:
    name: Rebase mutations branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git configuration
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'

      - name: Fetch all branches
        run: git fetch --all

      - name: Rebase mutations branch
        id: rebase
        run: |
          # Determine default branch name dynamically
          DEFAULT_BRANCH=${{github.event.repository.default_branch}}
          echo "Default branch is $DEFAULT_BRANCH"

          # Checkout mutations branch
          git checkout mutations/mutations

          # Attempt rebase
          if git rebase origin/$DEFAULT_BRANCH; then
            echo "Rebase successful"
            echo "rebase_status=success" >> $GITHUB_OUTPUT
          else
            echo "Rebase failed due to conflicts"
            git rebase --abort
            echo "rebase_status=failed" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Push rebased branch
        if: steps.rebase.outputs.rebase_status == 'success'
        run: git push --force-with-lease origin mutations

      - name: Create issue on rebase failure
        if: steps.rebase.outputs.rebase_status == 'failed'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Rebase failed for mutations branch',
              body: `The automatic rebase of the \`mutations\` branch failed due to conflicts.\n\n` +
                    `This happened after a push to the default branch by ${context.actor}.\n\n` +
                    `Please resolve the conflicts manually.`
            })
