# This workflow is triggered manually
name: MPL-Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "What version are you publishing"
        required: true
        type: string

jobs:
  allowList:
    runs-on: ubuntu-latest
    steps:
      - name: Is user allowlisted?
        id: allowList
        if: ${{ contains('["seebees","lucasmcdonald3","josecorella","imabhichow","rishav-karanjit","antonf-amzn","justplaz","ajewellamz"]', github.actor)}}
        run: |
          echo "User ${{github.actor}} is allowed to run this action"
      - name: Error if blocklisted
        if: ${{steps.allowList.conclusion ==  'failure' || steps.allowList.conclusion == 'skipped'}}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('User ${{github.actor}} is not allow listed to run this workflow')
  getVersion:
    needs: [allowList]
    uses: ./.github/workflows/dafny_version.yaml
  getUniqueId:
    needs: [allowList]
    uses: ./.github/workflows/create_unique_id.yml
  # java-release:
  #   needs: getVersion
  #   uses: ./.github/workflows/java-release.yml
  #   with:
  #     dafny: ${{needs.getVersion.outputs.version}}
  #     version: ${{inputs.version}}
  net-release:
    needs: [getVersion, getUniqueId]
    uses: ./.github/workflows/net-release.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}
      version: ${{inputs.version}}
      unique-id: ${{needs.getUniqueId.outputs.unique-id}}