# This workflow is triggered manually
name: MPL-Release

on:
  workflow_dispatch:
    inputs:
      dafny:
        description: "The Dafny version to use"
        required: true
        type: string

jobs:
  getVersion:
    uses: ./.github/workflows/dafny_version.yaml
  java-release:
    if: contains('["seebees","texastony","ShubhamChaturvedi7","lucasmcdonald3","josecorella","imabhichow","rishav-karanjit","antonf-amzn","justplaz","ajewellamz"]', github.actor)
    needs: getVersion
    uses: ./.github/workflows/java-release.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}
