# This workflow is triggered manually
name: TODO-MPL-Release

on:
  workflow_dispatch:
    inputs:
      dafny:
        description: "The Dafny version to use"
        required: true
        type: string

permissions:
  contents: read

jobs:
  getVersions:
    uses: ./.github/workflows/dafny_versions.yaml
  java-release:
    if: contains('["seebees","texastony","ShubhamChaturvedi7","lucasmcdonald3","josecorella","imabhichow","rishav-karanjit","antonf-amzn","kessplas","RitvikKapila","ajewellamz"]', github.actor)
    needs: getVersions
    uses: ./.github/workflows/todo-java-release.yml
    with:
      dafny: ${{needs.getVersions.outputs.version}}
